- config.go
- doc.go
- rpcserver.go
- sample-btcd.conf
This pull request introduces a new flag, `--notls`, which can be used to disable TLS for the RPC server.  However, the flag can only be used when the RPC server is bound to localhost interfaces.  This is intended to prevent the situation where someone decides they want to expose the RPC server to the web for remote management/access, but forgot they have TLS disabled.
Here is an example of the functionality:
**Disallowed**
> $ ./btcd --notls --rpclisten=whateverdomain.com
> loadConfig: the --notls option may not be used when binding to non localhost addresses: whateverdomain.com:8334
> Use btcd -h to show usage
> 
> $ ./btcd --notls --rpclisten=whateverdomain.com:12345
> loadConfig: the --notls option may not be used when binding to non localhost addresses: whateverdomain.com:12345
> Use …
> Allow disabling RPC server TLS for localhost only.

- rpcserver.go
This pull request modifies the getblocktemplate RPC to correctly handle the curtime field.
Currently, the RPC server will refuse to serve a block template if the current time is before the minimum allowed time for a block even though the real generated block template already accounted for it.
This consists of three changes:
- Remove the unnecessary and incorrect check in the RPC invocation for the current time against the min required time since it is already handled properly by the block template generation.
- Expose the network time source to the RPC work state and use the adjusted time for checking against the maximum allowed time instead of  the current time.
- Set the returned RPC result curtime field to the time of the generated block header.
> Correct RPC time handling for getblocktemplate.

- blockmanager.go
- log.go
- mempool.go
The mempool's MaybeAcceptTransaction methods have also been modified
to return a slice of transaction hashes referenced by the transaction
inputs which are unknown (totally spent or never seen).  While this is
currently used to include the first hash in a ProcessTransaction error
message if inserting orphans is not allowed, it may also be used in
the future to request orphan transactions from peers.
> Improve double spend error strings.

- sample-btcd.conf
The comment for the RPC listen section in the sample-btcd.conf incorrectly claimed that the default for the RPC server listener is to listen on all interfaces by default.  In reality, it only listens on localhost for IPv4 and IPv6 by default.
Closes #208.
> Correct sample-btcd.conf RPC listen comment.

- mempool.go
This pull request modifies the memory pool standard transaction dust check to exclude transactions with nulldata outputs so they may be considered standard.
> Don't treat nulldata tx outs as nonstandard dust.

- blockmanager.go
- peer.go
Only two operations are performed with this data structure: adding to
the back and removing from the front.  Because middle inserts and
deletions are never needed, a linked list results in overall worse
performance due to an extra allocation for each element's node, worse
cache locality, and the runtime cost of boxing/unboxing each item
during accesses.
On top of the performance gains, a slice is more type safe as it is a
true generic data structure making it is impossible to insert or
access an element with the wrong type.
> Switch peer.requestQueue from linked list to slice.

- rpcserver.go
This was previously hard-coded to zero instead of using the offset provided by the median time source which takes time samples from the other connected nodes.
> Return time offset in getinfo RPC.

- peer.go
Currently, the reference client bans peers that send alerts not signed
with its key.  We could verify against their key, but since the
reference client developers are currently unwilling to support other
implementations' alert messages, we will not relay theirs.
> Intentionally ignore alert messages.

- mining.go
This commit makes use of the new `ScriptDiscourageUpgradableNops` flag to reject execution of NOP1 through NOP10 for transactions that are considered standard.
This mirrors the behavior added to Bitcoin Core via pull request 5000.
> Make NOP1-NOP10 opcode execution non-standard.

- blockmanager.go
- mempool.go
- rpcserver.go
- server.go
When an inv is to be sent to the server for relaying, the sender already has access to the underlying data. So instead of requiring the relay to look up the data by hash, the data is now coupled in the relay request message.
Previously, forcing the relay to look up the data itself led to an occasional deadlock between the `mempool` and `server` as detailed in: #231. This PR purpotes to eliminate any possiblity for deadlock by implementing [davecgh's proposed solution](https://github.com/btcsuite/btcd/issues/231#issuecomment-71876668).
> Relay inv msgs now include underlying data object

- database/ldb/block.go
- database/ldb/tx.go
This change converts the leveldb database's ExistsSha() and
ExistsTxSha to use the goleveldb API.  Has() only returns if
the key exists and does not need to read the entire value into
memory resulting in less disk i/o and much less GC.
> Use goleveldb Has() API.

- blocklogger.go
- blockmanager.go
- btcd.go
- chainindexer.go
- cmd/btcctl/btcctl.go
- config.go
- doc.go
- docs/json_rpc_api.md
- log.go
- mempool.go
- rpcserver.go
- sample-btcd.conf
- server.go
This PR adds support for an optional `addrindex`. This PR depends on both conformal/btcdb#11 and conformal/btcjson#33. Additionally, this PR is the final pull request needed towards completion of conformal/btcd#190 (will also update `btcrpcclient` once `btcjson2` is in).
With the addition of this PR, `btcd` gains an additional service, the `addrIndexer`. Factoring in new the optional `--addrindex` flag, there are three possible operating modes w.r.t the address-based transaction index:
* `btcd` is fully synced, `addrindex` is activated `(chaintip > addrtip)`:
* In this mode, the `addrIndexer` enters "catch up" mode. While within this mode, the address index will be concurrently built up starting from the genesis block to the current best main chain height. 
* `btcd` is fully …
> Add support for an optional address-based transaction index

- btcec/genprecomps.go
- btcec/gensecp256k1.go
This pull request adds code which generates the linearly independent vectors used by the secp256k1 endomorphism code.  These values are hard-coded into the curve already, but having the code used to generate them is handy should any future curves be added which can also make use of the same class of endomorphism.
> [btcec] Add generation code for the endomorphism vectors.

- btcec/btcec.go
This pull request converts the initialization of the constants to use a function which panics on error instead of just ignoring the error.  This is acceptable since they are hard-coded constants and should never fail.
> [btcec] Don't ignore errs setting consts in btcec init.

- btcec/bench_test.go
- btcec/btcec_test.go
The benchmarks are still only compiled when running 'go test' so this has no effect on regular usage.  This is being done because benchmarks often need access to internal state.
Normal tests are kept in a separate package since they also serve to exercise the public API, and by intentionally making it more difficult to reach into the internals, it helps ensure the public API is sanely usable.
Since the benchmarks can now access the internals directly, this commit also removes the functions which exposed the internals to the test package from internal_test.go which were only used by the benchmarks.
Also, it removes a duplicate benchmark.
> [btcec] Move the btcec benchmarks into the main package.

- btcec/btcec.go
- btcec/field.go
- btcec/secp256k1.go
This pull request contains various modifications for code and comment consistency in the btcec package:
- Call out references at the top and reference them by their identifier in the other comments
- Remove a TODO that no longer applies
- Add comments to the fields in the KoblitzCurve struct and reorder them slightly
- Make comments wrap to 80
- Cleanup code that was far exceeding col 80 (only function declarations typically do this)
- Extend block comments to use as much of the 80 cols as available
- Add a bit more explanation in a couple of places
- Update copyright year on secp256k1.go
- Fix a couple of typos in the comments
> [btcec] Consistency and general cleanup in btcec. 

- blockchain/txlookup.go
For example, when performing a heap profile, this:
.          .    125:   fetchFunc := db.FetchUnSpentTxByShaList
.          .    126:   if includeSpent {
.          .    127:           fetchFunc = db.FetchTxByShaList
.          .    128:   }
.     9.11MB    129:   txReplyList := fetchFunc(txList)
Now becomes this:
.          .    125:   var txReplyList []*database.TxListReply
.          .    126:   if includeSpent {
.          .    127:           txReplyList = db.FetchTxByShaList(txList)
.          .    128:   } else {
.     8.75MB    129:           txReplyList = db.FetchUnSpentTxByShaList(txList)
.          .    130:   }
And it's clear where the majority of our allocations are coming from.
> Make profiling easier to follow with static dispatch.

- txscript/README.md
- txscript/example_test.go
This pull request adds a new example to the txscript package that demonstrates creating a new transaction which redeems funds and signing the referenced transaction output the SignTxOutput function.
> txscript: Add example for manully signing a txout.

- blockchain/blocklocator.go
We only care about the height, so just fetch the height instead of
the entire block.
> blockchain: Just fetch the height

- mining.go
- txscript/example_test.go
- txscript/opcode.go
- txscript/opcode_test.go
- txscript/script.go
- txscript/script_test.go
Remove ScriptCanonicalSignatures and use the new
ScriptVerifyDERSignatures flag.  The ScriptVerifyDERSignatures
flag accomplishes the same functionality.
> txscript: Remove ScriptCanonicalSignatures

- config.go
- mempool.go
By default, have the mempool reject free and low-fee transactions that
have insufficient priority to be mined in the next block.
Addtionally, add a new configuration option, -norelaypriority, to
disable the check.
> Reject free/low-fee transactions with insufficient priority.

- btcjson/v2/btcjson/chainsvrcmds.go
- btcjson/v2/btcjson/chainsvrcmds_test.go
- cmd/btcctl/btcctl.go
- cmd/btcctl/config.go
- cmd/btcctl/httpclient.go
- rpcserver.go
This pull request contains what is essentially a complete rewrite of the btcctl utility to make use of the new features provided by the latest version btcjson and improve several things along the way.  The following summarizes the changes:
- The supported commands and handling now come directly from btcjson, so it is no longer necessary to manually add new commands.  Once a command has been registered with btcjson, it will automatically become usable by btcctl complete with full error handling (once it is re-compiled of  course)
- Rather than dumping the entire list of commands on every error, the user now must specifically request the list of commands via the -l option
- The list of commands is now categorized by chain and wallet and alphabetized
- The help flag now only shows the help …
> cmd/btcctl: Rewrite btcctl to use the new features of btcjson.

- blockchain/accept.go
- blockchain/scriptval.go
- blockchain/scriptval_test.go
- blockchain/validate.go
This pull request moves the definition of the flags which are needed to check transaction scripts higher up the call stack to pave the way for adding support for v3 blocks.  While here, also spruce up a couple of sections.
There are no functional changes in this pull request.
> blockchain: Determine script flags sooner.

- blockmanager.go
- mempool.go
This modifies the recently added code which rejects free/low-fee transactions with insufficient priority to ignore resurrected transactions from disconnected blocks.  It also exempts resurrected transactions from the free/low-fee rate limiting.
> mempool: Loosen restrictions for resurrected txns.

- mempool.go
- mining.go
- txscript/internal_test.go
- txscript/script.go
- txscript/script_test.go
Additionally, drop HasCanoncialPushes as ScriptVerifyMinimalData
offers more complete checks.
> Use ScriptVerifyMinimalData

- mempool.go
- mining.go
- txscript/script.go
By exporting StandardVerifyFlags, clients can ensure they create
transactions that btcd will accept into its mempool.
This flag doesn't belong in txscript.  It belongs in a
policy package.  However, this is currently the least worse place.
> txscript: export StandardVerifyFlags

- btcjson/v2/btcjson/chainsvrwsntfns.go
- btcjson/v2/btcjson/chainsvrwsntfns_test.go
- rpcwebsocket.go
btcjson v2 switched an optional field to mandatory which resulted
in a nil deference.  This switches it back to optional.
> btcjson: Fix a bug in btcjson v2

- rpcserver.go
When the fields in the command for the getnetworkhashps RPC don't have the fields set, use the intended default values.
Since the btcjson package sets these fields to the default values when a command is unmarshaled from the wire, this typically isn't necessary. However, when the RPC server calls the handler internally with optional command fields set to nil, as is the case in getmininginfo, the defaults need to be set as well.
> rpcserver: Use default values for getnetworkhashps.

- wire/msgblock.go
- wire/msgtx.go
- wire/msgtx_test.go
This pull request provides a new function named PkScriptLocs on the MsgTx type which can be used to efficiently retrieve a list of offsets for the public key scripts for the serialized form of the transaction.
This is useful for certain applications which store fully serialized transactions and want to be able to quickly index into the serialized transaction to extract a give public key script directly thereby avoiding the need to deserialize the entire transaction.
> wire: Add func to get pkscript locs from a tx.

- blockmanager.go
- mempool.go
For every transaction in a newly accepted block, process the orphan
pool moving now no longer orphan transactions to the mempool.
Previously, no longer orphan transactions would remain in the orphan
pool.
> Process orphans on block acceptance.

- blockchain/bench_test.go
- blockchain/validate.go
This pull request adds a new function to the blockchain package named IsCoinBaseTx which performs the same function as IsCoinBase except it takes raw wire transactions as opposed to the higher level util transactions.
While here, it also adds a file for benchmarks along with a couple of benchmarks for the IsCoinBase and IsCoinBaseTx functions.
Finally, the function was very slightly optimized:
```
BenchmarkIsCoinBaseOld  100000000  10.7 ns/op  0 B/op  0 allocs/op
BenchmarkIsCoinBaseNew  200000000  6.05 ns/op  0 B/op  0 allocs/op
```
> blockchain: Provide new IsCoinBaseTx function.

- cmd/btcctl/btcctl.go
- cmd/btcctl/config.go
This pull request modifies the argument handling for btcctl to treat a parameter that is a single dash as an indicator to read that paramter from stdin instead.
This change allows commands, such as the submitblock, to accept data piped from stdin for any parameter.  This, in turn, allows large arguments, such as blocks, which can often be too big for a single argument due to Operating System limitations to be submitted by putting them into a file and redirecting stdin.
For example:
```bash
$ btcctl submitblock - <block.hex
$ cat block.hex | btcctl submitblock -
$ btcctl sendrawtransaction - <tx.hex
$ cat tx.hex | btcctl sendrawtransaction -
```
> btcctl: Support - argument to read from stdin.

- database/ldb/internal_test.go
- database/ldb/tx.go
- Use explicit index values for byte slices
- Fix a bug in FetchTxsForAddr that allocated an extra 10 bytes
for each address index
- Add missing iterator release in error path
- Check for iterator errors.
> Do a little addrindex database cleanup.

- database/db.go
- database/ldb/block.go
- database/ldb/internal_test.go
- database/ldb/leveldb.go
- database/ldb/tx.go
- mempool.go
- rpcserver.go
This fixes issue #346 and makes it so that transactions are returned in order. In order to do the latter, the integers in the address index are stored as big endian rather than little endian; this requires an index rebuild and the pull request does that automatically. Unfortunately, there is a bug exposed by the index rebuild which causes a shutdown (see issue #303), which I'll be working on fixing next.
> Addrindex fixes

- btcec/example_test.go
- btcec/internal_test.go
- btcec/privkey.go
- btcec/signature.go
- btcec/signature_test.go
See https://github.com/btcsuite/btcd/issues/358 for discussion.
The test vectors are the same as in [Trezor](https://github.com/trezor/trezor-crypto/blob/9fea8f8ab377dc514e40c6fd1f7c89a74c1d8dc6/tests.c#L432-L453) and [CoreBitcoin](https://github.com/oleganza/CoreBitcoin/blob/e93dd71207861b5bf044415db5fa72405e7d8fbc/CoreBitcoin/BTCKey%2BTests.m#L23-L49) implementations and cover both the raw nonce (k) and the complete DER-encoded signature (which must have canonical S).
> Deterministic signatures according to RFC6979

- blockchain/difficulty.go
- blockchain/merkle.go
- database/ldb/block.go
- database/ldb/leveldb.go
- database/ldb/tx.go
- server.go
- wire/bench_test.go
- wire/common.go
- wire/shahash.go
This pull request contains three classes of optimizations:
- Reduce the number of unnecessary hash copies
- Improve the performance of the DoubleSha256 function
- A couple of minor optimizations of the ShaHash functions
The first class is a result of the Bytes function on a ShaHash making a copy of the bytes before returning them.  It really should have been named CloneBytes, but that would break the API now.
To address this, a comment has been added to the function which explicitly calls out the copy behavior.  In addition, all call sites of .Bytes on a ShaHash in the code base have been updated to simply slice the array when a copy is not needed.  This saves a significant amount of data copying.
The second optimization modifies the DoubleSha256 function to directly use fastsha256.Sum256 …
> Minor hashing-related optimizations.

- blockchain/merkle.go
- wire/bench_test.go
- wire/blockheader.go
- wire/common.go
- wire/msgtx.go
This pull request adds a new function which is similar to the DoubleSha256 function except it returns a ShaHash copy instead of a byte slice.  It also adds a new benchmark for it.
This can be a slight optimization in certain cases where the caller ultimately wants a ShaHash since it can avoid a heap allocation and additional copy to convert the result to a ShaHash (the function simply performs a type cast against the returned array which is not possible against a []byte).
```
existing: DoubleSha256     500000   3081 ns/op   32 B/op   1 allocs/op
new: DoubleSha256SH   500000   2939 ns/op    0 B/op   0 allocs/op
```
The hashing functions for blocks and transactions have also been updated to make use of the new function since they directly return the ShaHash. The transaction change in …
> wire: Add new DoubleSha256SH function.

- blockmanager.go
- mining.go
Because FetchTransactionStore in GetBlockTemplate occasionally accesses
the internal blockchain memory structure while it is being read or modified,
a race can occur. To prevent this, FetchTransactionStore is instead
routed through the internal channel for blockchain requests.
> Fix race from direct access of FetchTransactionStore

- addrmgr/knownaddress.go
This change was suggested as Countermeasure 2 in Eclipse Attacks on
Bitcoin's Peer-to-Peer Network, Ethan Heilman, Alison Kendler, Aviv
Zohar, Sharon Goldberg. ePrint Archive Report 2015/263. March 2015.
This mimics Bitcoin Core commit
f68ba3f67bd500a64fb8932c6b41924ddc31d76f
> addrmgr: Do not bias toward fresh addresses.

- addrmgr/addrmanager.go
- addrmgr/addrmanager_test.go
- server.go
This change was suggested as Countermeasure 2 in
Eclipse Attacks on Bitcoin's Peer-to-Peer Network, Ethan
Heilman, Alison Kendler, Aviv Zohar, Sharon Goldberg. ePrint Archive
Report 2015/263. March 2015.
This mimics Bitcoin Core commit c6a63ceeb4956933588995bcf01dc3095aaeb1fc
> addrmgr: Always use a 50% chance between tried and new entries.

- addrmgr/addrmanager.go
- peer.go
This change reduces fingerprinting via timestamps in addr messages.
Previously, the last seen time for an address was updated when
certain protocol commands were received.  Now, the last seen time
is set when the peer disconnects if the peer had sent a verack
message and was connected for more than 20 minutes.
This mimics Bitcoin Core commit:
9c2737901b5203f267d21d728019d64b46f1d9f3
Also, add additional sanity checking before updating the peer's
timestamp.  These include:
- Do not mark a peer as connected if we never received
a version message.
- Disconnect a peer for sending a verack before btcd
sent a version
- Disconnect a peer for sending multiple verack's
> Reduce fingerprinting.

- peer.go
This change reduces fingerprinting attacks and
mimics Bitcoin Core commit
dca799e1db6e319fdd47e0bfdb038eab0efabb85
> Ignore getaddr requests from outbound peers.

- goclean.sh
This commit makes the goclean script print every line it is executing so any failures are more obvious where they're coming from.
Closes #361.
> build: Make goclean.sh script output more verbose.

- btcjson/v2/btcjson/btcdextcmds.go
- btcjson/v2/btcjson/btcdextcmds_test.go
- docs/json_rpc_api.md
- rpcserver.go
- rpcserverhelp.go
- server.go
This PR adds new JSON-RPC command: `node`. `node` allows a node operator full control over the peers their node is connect to.
A call to the new `node` RPC can take the following forms:
* `btcctl node connect <addr> perm` (will attempt connect to a peer and mark it was permanent) 
* `btcctl node connect <addr> temp` (will attempt to connect to a peer)
* `btcctl node disconnect <addr or ID>` (will attempt to remove an outgoing or incoming peer)
* `btcctl node remove <addr or ID>` (will attempt to remove a permanent peer)
This PR replaces #336. 
This aims to fix #79 by adding a new command that can disconnect any (inbound or outbound) non-persistent peer.
> Add new 'node' RPC command

- blockchain/common_test.go
- blockmanager.go
- chaincfg/genesis_test.go
- cpuminer.go
- database/ldb/insertremove_test.go
- database/ldb/operational_test.go
- database/ldb/tx.go
- database/memdb/memdb.go
- database/memdb/memdb_test.go
- log.go
- rpcserver.go
- txscript/example_test.go
- txscript/internal_test.go
- wire/blockheader.go
- wire/msgblock.go
- wire/msgblock_test.go
- wire/msgtx.go
- wire/msgtx_test.go
This pull request removes the error returns from the `BlockHeader.BlockSha`, `MsgBlock.BlockSha`, and `MsgTx.TxSha` functions since they can never fail and end up causing a lot of unneeded error checking throughout the code base.
It also updates all call sites for the change.
> wire: Remove errs from BlockHeader/MsgBlock/MsgTx.

- blockchain/scriptval.go
- txscript/example_test.go
- txscript/internal_test.go
- txscript/opcode_test.go
- txscript/script.go
- txscript/script_test.go
This pull request removes the unnecessary sigScript parameter from the txscript.NewScript function.  This has bothered me for a while because it can and really should be obtained from the provided transaction and input index.  The way it was, the passed script could technically be different than what is in the transaction.  Obviously that would be an improper use of the API, but it's safer and more convenient to simply pull it from the provided transaction and index.
Also, since the function signature is changing anyways, make the input index parameter come after the transaction which it references.
> txscript: Remove unneeded param from NewScript.

- txscript/error.go
- txscript/script.go
This is more consistent with the rest of the code base and also will make it easier to improve the errors to provide more details at a later date.
> txscript: Move error definitions to error.go.

- txscript/engine.go
- txscript/internal_test.go
- txscript/opcode.go
Rather than storing a separate bool for whether or not each flag is set in every script engine instance, store the flags and check if the relevant flag is set from each specific location.
This reduces the memory needed by each script engine instance and means future flags will not require new fields.
> txscript: Store flags in instance versus bools.

- addrmgr/internal_test.go
- addrmgr/knownaddress.go
- addrmgr/knownaddress_test.go
I have made tests for knownaddresses.go. This meant making an internal_test.go file to expose chance() and isBad(). I have tested both functions in accordance with the comments given for each of them. Both functions turned out to be buggy and required fixes. 
A comment for chance() says "Very recent attempts are less likely to be retried." However, the if clause below only affects c if the last attempt was NOT very recent, or greater than 10 minutes. The way this function works now is that very recent attempts are MORE likely to be retried! 
The next comment for chance() says "Failed attempts deprioritise." However, the for loop says "for i := ka.attempts; i < 0; i++" However, ka.attempts is supposed to be zero or greater. It will not ordinarily be negative. This means that the loop never …
> Added tests for addrmgr.KnownAddress

- txscript/engine.go
- txscript/opcode.go
This pull request improves the way the conditional execution stack is handled in a few ways.
First, the current execution state is now pushed onto the end of the slice rather than the front of it.  This has been done because it results in fewer allocations and is therefore more efficient.
Second, the need for allocating and setting an initial true in the conditional stack has been eliminated.  The vast majority of scripts don't contain any conditionals, so there is no reason to allocate a slice when
it isn't needed.
Third, a new function has been added to the engine to determine if the current conditional branch is executing named `isBranchExecuting` which handles the fact the conditional execution stack can now be empty and
improves the readability of the code.
Finally, it removes a …
> txscript: Improve conditional stack.

- btcjson/v2/btcjson/chainsvrwscmds.go
- btcjson/v2/btcjson/chainsvrwscmds_test.go
This pull request removes the `NewOutPointFromWire` function from the `btcjson` version 2 package so it can be used without needing the wire package as a dependency.  It also updates the tests accordingly.
This results in the package only depending on core Go packages.
Closes #401.
> btcjson: Remove NewOutPointFromWire and wire dep.

- rpcserver.go
- server.go
* The cases for the 'addnode' command were previously
stacked on top the new cases for the 'node' command.
The intended behavior was to create a fall through and
handle both commands. However, trying to use this
syntax with a type switch caused the first case to be
ignored.
* The 'addnode' cases are now handled separately from the
'node' commands in the server.
> Fix 'add/delnode' type switch evaluation in server

- txscript/engine.go
- txscript/stack.go
- txscript/stack_test.go
This pull request unexports the `txscript.Stack` type since it is only intended to be used internally during script execution.  Further, the engine exposes the `{G,S}etStack` and `{G,S}etAltStack` functions which return the items as a slice of byte slices ([][]byte) for caller access while stepping.
> txscript: Unexport Stack type.

- txscript/opcode.go
This pull request very slightly optimizes the cryptographic hashing performed by the script opcodes by calling the hash sum routines directly (for those that support it) rather than allocating a new generic hash.Hash
hasher instance for them.
> txscript: Slight crypto hash optimizations.

- txscript/engine.go
- txscript/opcode.go
This pull request moves the opcode execution logic from the opcode type to the engine type because execution of an opcode modifies the engine state (primarily the main and alternate data stacks) as opposed to the state of the opcode.  Making the engine the receiver more clearly indicates this fact.
> txscript: Move opcode execution logic to engine

- txscript/engine.go
- txscript/opcode.go
- txscript/script.go
- txscript/script_test.go
- txscript/sign.go
- txscript/stack.go
This pull request contains a lot of cleanup on the txscript code to make it more consistent with the code throughout the rest of the project.  It doesn't change any operational logic.
The following is an overview of the changes:
- Add a significant number of comments throughout in order to better explain what the code is doing
- Fix several comment typos
- Move a couple of constants only used by the engine to engine.go
- Move a variable only used by the engine to engine.go
- Fix a couple of format specifiers in the test prints
- Reorder functions so they're defined before/closer to use
- Make the code lint clean with the exception of the opcode definitions
> txscript: Code consistency and doco improvements.

- btcjson/v2/btcjson/walletsvrcmds.go
- btcjson/v2/btcjson/walletsvrcmds_test.go
- btcjson/v2/btcjson/walletsvrwscmds.go
- btcjson/v2/btcjson/walletsvrwscmds_test.go
btcwallet will need to check whether these requests were unset, so defaults cannot be automatically filled in by btcjson.
~~This currently depends on several unmerged btcwallet PRs so it cannot be merged at this time.~~ ready
> Remove account defaults for wallet requests.

- mining.go
- txscript/engine.go
- txscript/opcode.go
- txscript/scriptbuilder.go
- txscript/scriptbuilder_test.go
- txscript/scriptnum.go
- txscript/scriptnum_test.go
- txscript/stack.go
- txscript/stack_test.go
NOTE: Depends on #408.
This pull request implements a new type, named scriptNum, for handling all numeric values used in scripts and converts the code over to make use of it.  This is being done for a few of reasons.
First, the consensus rules for handling numeric values in the scripts require special handling with subtle semantics.  By encapsulating those details into a type specifically dedicated to that purpose, it simplifies the code and generally helps prevent improper usage.
Second, the new type is quite a bit more efficient than big.Ints which are designed to be arbitrarily large and thus involve a lot of heap allocations and additional multi-precision bookkeeping.  Because this new type is based on an int64, it allows the numbers to be stack allocated thereby eliminating a lot of …
> txscript: Convert to new scriptnum type.

- rpcserver.go
This commit increases the precision of the difficulty field of the getblock RPC to 8 to match Bitcoin Core.
Closes #414.
> rpcserver: Increase getblock difficulty prec to 8.

- txscript/engine_test.go
- txscript/internal_test.go
- txscript/reference_test.go
- txscript/script_test.go
- txscript/scriptbuilder_test.go
- txscript/sign_test.go
- txscript/stack_test.go
- txscript/standard.go
- txscript/standard_test.go
- Move reference tests to test package since they are intended to exercise the engine as callers would
- Improve the short form script parsing to allow additional opcodes: DATA_#, OP_#, FALSE, TRUE
- Make use of a function to decode hex strings rather than manually defining byte slices
- Update the tests to make use of the short form script parsing logic rather than manually defining byte slices
- Consistently replace all []byte{} and [][]byte{} with nil
- Define tests only used in a specific function inside that func
- Move invalid flag combination test to engine_test since that is what it is testing
- Remove all redundant script tests in favor of the JSON-based tests in the data directory.
- Move several functions from internal_test.go to the test files associated with what the tests …
> txscript: Test consistency and cleanup.

- btcjson/chainsvrwscmds.go
- btcjson/chainsvrwscmds_test.go
- docs/json_rpc_api.md
- rpcserverhelp.go
- rpcwebsocket.go
This PR aims to address #122 by providing JSON-RPC methods allowing clients to cancel received and spent notifications. 
Note: before this can be properly integrated into `btcwallet`, `btcrpcclient` will need to be updated to use `btcjsonv2`.
> Allow clients to cancel transaction notifications

- btcjson/helpers.go
- btcjson/walletsvrresults.go
- btcjson/walletsvrwsntfns_test.go
The following changes were made to ListTransactionsResult (which
models the long result format used by listtransactions,
listsinceblock, etc.):
- Fee made optional (float64 -> *float64 + omitempty)
- BlockIndex made optional (int64 + omitempty -> *int64 + omitempty)
- InvolvesWatchOnly added (bool + omitempty)
- Vout added (uint32)
The following changes were made to GetTransactionDetailsResult (which
models the short result format of listtransactions):
- InvolvesWatchOnly added (bool + omitempty)
- Fee added (*float64 + omitempty)
- Vout added (uint32)
The combination of pointer types and the omitempty struct tag allow
excluding the field from the JSON object, or including it with the
zero value.  This is useful in particular for the fee fields, which
should be included whenever the …
> Fix listtransactions/gettransaction result structs.

- btcjson/chainsvrresults.go
- btcjson/chainsvrwsntfns_test.go
This pull request omits the confirmations field from the `getrawtransactions` RPC result when it's zero.
Closes #420.
> rpcserver: Omit empty getrawtransaction->confirmations.

- btcjson/walletsvrresults.go
This mimics Bitcoin Core commit 8ac2a4e1788426329b842eea7121b8eac7875c76
> Add additional fields to the SignRawTransaction RPC result.

- blockchain/accept.go
- blockchain/validate.go
This pull request refactors the consensus rule checks for block headers and blocks in the blockchain package into separate functions.  These changes contain no modifications to consensus rules and the code still passes all block consensus tests.  It is only a refactoring.
This is being done to help pave the way toward supporting concurrent downloads.  While the package already supports headers-first mode up through the latest checkpoint through the use of the BFFastAdd flag and hard-coded checkpoints, it currently only works when downloading from a single peer.  In order to support concurrent downloads from multiple peers, the ability for the caller to do things such as independently checking a block header (both context-free and full-context checks) will be needed.
There are several more …
> blockchain: Split block and header validation.

- config.go
- doc.go
- docs/configuring_tor.md
- sample-btcd.conf
Tor stream isolation randomizes proxy user credentials resulting in
Tor creating a new circuit for each connection.  This makes it more
difficult to correlate connections.
Idea from Wladimir J. van der Laan via Bitcoin Core.
> Add new option --torisolation

- btcec/ciphering.go
A side channel attack vector in btcec.Decrypt has been closed. bytes.Equal returns false as soon as the first byte fails to match. An attacker could guess the correct HMAC using careful timing analysis and then spoof it. Changing it to hmac.Equal, which has a constant run time, ensures that this doesn't happen.
> btcec: Mitigate timing attacks while using btcec.Decrypt

- blockmanager.go
This pull request corrects an issue where the reject message sent in response to rejected transactions had the Cmd field set to "block" instead of "tx".
Fixes #436.
> mempool: Correct cmd field for rejected txns.

- btcjson/chainsvrcmds.go
- btcjson/chainsvrcmds_test.go
From Bitcoin Core commit 59ed61b3895b022f61970ea7aac0c20e8ba38886
> Add gettxoutproof and verifytxoutproof JSON-RPC infrastructure.

- README.md
This commit adds an additional step to the README.md install section to run the go version command and check the version so people that are installing it for the first time and ensure they are running a high enough version.
> Update README.md install section.

- config.go
The configured onion proxy was not being used due to checking if the
passed string had suffix '.onion', which never matched because the
port number is part of the string.
> Fix --onion.

- docs/json_rpc_api.md
- rpcwebsocket.go
This allows clients watching for both to know when all mined
transaction notifications for the block have been received.
Otherwise, clients would be aware that there is a new block, see the
exact same block hash/height in the next tx notifications, but never
know when all txs from the block have been received and processed.
This fixes a synchronization issue in btcwallet where the wallet would
mark itself synced to some block height before any of those blocks
transactions were processed.  If the RPC connection is lost between
sending the blockconnected notification and receiving the last
transaction notification, the wallet would not know of this and
continue with missing transactions.
> Notify mined transactions before connected block.

- blockchain/validate.go
- log.go
- txscript/consensus.go
Move lockTimeThreshold to txscript and export it.  This is a
consensus value which txscript will need in an upcoming diff.
> txscript: Move lockTimeThreshold to txscript

- peer.go
When trickling inv's to peers, allocate for the number of inv's
in the queue instead of the default 1000.  This should save on
memory.
> Use NewMsgInvSizeHint when we know the size.

- blockchain/validate.go
- mempool.go
- mining.go
- txscript/consensus.go
This change moves IsFinalizedTransaction to txscript and also changes
the first argument to take a wire.MsgTx instead of btcutil.Tx.  This
is needed for an upcoming diff in which txscript will require
IsFinalizedTransaction and we do not want to import the btcd/blockchain.
> Move IsFinalizedTransaction to txscript.

- blockchain/validate.go
- mempool.go
- mining.go
- txscript/consensus.go
This reverts commit 17da2ba7fa691c666d70948217ffcd5b6ac148f8.
This was done prematurely.  This will be revisited when a code
restructure is more urgent.
> Revert "Move IsFinalizedTransaction to txscript."

- txscript/sign.go
Only minor documentation changes.
> Fixed erroneous txscript.KeyClosure documentation.

- docs/json_rpc_api.md
This pull request corrects the JSON-RPC API doc return to overview links for the Websocket Extension Method Details section.
> docs: Correct JSON-RPC API overview return links.

- peer.go
- server.go
This pull request correctly replaces persistent peers that are being retried in the list of persistent peers so it will continue to be retried as intended.
Also, it limits the maximum retry interval for persistent peers to 5 minutes.
Fixes #463.
> Correct reconnect handling for persistent peers.

- wire/msgtx_test.go
This pull request updates the wire tests for transactions which force serialization and deserialization errors to force an error in the the transaction lock time path.
This brings the wire test coverage back up to 100%.
> wire: Update tests to force error in tx lock time.

- wire/blockheader.go
- wire/blockheader_test.go
At the current time, there is no difference between the wire encoding
at protocol version 0 and the stable long-term storage format.  These
methods are simply for consistency with the other types.
> Implmement BlockHeader BtcEncode/BtcDecode.

- txscript/script.go
These copies were likely left over from when MsgTx had no deep copy
functionality.
> txscript: Remove unneeded signature hash copies

- peer.go
This pull request updates the merkle block handling to for the latest changes to the `btcutil` API and optimizes it along the way.
Previously, the code was inefficiently reloading the transactions for the matched hashes from the database instead of simply pulling them from the full block that was used to create the merkle block.
Depends on btcsuite/btcutil#55
> peer: Optimize merkle block handling.

- rpcserver.go
- rpcwebsocket.go
This pull request modifies the `createTxRawResult` code path along with callers to work with block headers as opposed to `btcutil.Block`s.  This in turn allows the code in `handleGetRawTransaction` and `handleSearchRawTransactions` to perform a much cheaper block header load as opposed to a full block load.
While here, also very slightly optimize the `createVinList` function to avoid creating a `util.Tx` wrapper and to take advantage of the `btcutil.Amount` type added after the function was originally written
> rpcserver: Allow tx result creation without block.

- server.go
The comment says "only allow recent nodes (10mins) after we failed 30 times", but the server actually did the opposite and allowed only recent nodes before 30 failed connection attempts. This corrects the server's behavior.
https://golang.org/pkg/time/#Time.After 
"(t Time) After(u Time) After reports whether the time instant t is after u. "
So, previously, if now is AFTER the last connect attempt + ten minutes, in other words, if the last connect attempt was greater than ten minutes ago, don't bother trying to connect!
> Fix incorrect ip connection attempt logic.

- mempool.go
- txscript/script.go
- txscript/script_test.go
IsUnspendable takes a public key script and returns whether it is
spendable.
Additionally, hook this into the mempool isDust function, since
unspendable outputs can't be spent.
This mimics Bitcoin Core commit 0aad1f13b2430165062bf9436036c1222a8724da
> txscript:  New function IsUnspendable

- blockmanager.go
btcd currently does not notify miners waiting for new block templates via longpolling when a block is pushed via submitblock RPC. It does when a block is received via the P2P protocol.
This is due to the code paths for connecting the block being different. The fix adds a call to NotifyBlockConnected in the submitblock code path, as in handleBlockMsg. 
This bug is hard to see in regular conditions: mainnet difficulty is too high, and regtest/simnet is way too low. Maybe it'd be possible to reproduce it in testnet. In the logs below I'm solo mining on a test blockchain with a target of 0000000ffff000.., 16x easier than the Bitcoin difficulty.
Logs before the fix:
btcd:
````
dirbaio@saturn:~$ btcd -u test -P test
16:51:51 2015-08-21 [WRN] BTCD: open /home/dirbaio/.btcd/btcd.conf: no such …
```
> Fix longpoll getblocktemplate not getting notified if a block is pushed via submitblock

- wire/protocol.go
- wire/protocol_test.go
This does not add BIP0064 (getutxos/utxos) support to btcd.
> Recognize the BIP0064 service bit.

- mruinvmap.go
- mruinvmap_test.go
This pull request improves the most-recently used inventory map human readable string to only show the inventory vectors. and adds tests for the entire structure to bring its coverage to 100%.
In addition, removes the type assertion check in the Add function since the internal inventory list is only managed by the type itself and the tests would now catch any mistakes in the type of entries in the list.
> Improve mru inventory map and test cov to 100%.

- database/db.go
- database/ldb/operational_test.go
- database/ldb/tx.go
- database/memdb/memdb.go
- rpcserver.go
Currently, skip is not being applied properly to mempool transactions in searchrawtransactions. This PR fixes that.
I had to change FetchTxsForAddr to additionally return the number of transactions skipped, to properly calculate how many transactions in mempool to skip. (For example, if FetchTxsForAddr returns an empty array, I need to know whether there was no transactions at all, or there were some but they were all skipped).
> Fix skip not being applied to mempool txns in searchrawtransactions

- .travis.yml
- goclean.sh
This pull request updates TravisCI to use the most recent versions of Go and also modifies the `goclean.sh` script to quote the test command arguments and update the vet test to exclude recent false positives.
> Update TravisCI to test against golang 1.5.1.

- wire/common.go
- wire/common_test.go
- wire/msgversion.go
The Bitcoin wire protocol includes several fields with their lengths encoded according to a variable length integer encoding scheme that does not enforce a unique encoding for all numbers.
This can lead to a situation where deserializing and re-serializing the same data can result in different bytes.  There are no currently known issues due to this, but it is safer to reject such subtle differences as
they could potentially lead to exploits.
Consequently, this pull request modifies the varint decoding function to error when the value is not canonically encoded which effectively means that all messages with varints that are not canonically encoded will now be rejected.  This will not cause issues with old client versions in regards to blocks and transactions since the data is deserialized …
> wire: Reject non-canonically encoded varints.

- txscript/script.go
This pull request modifies the `DisasmString` function to use a bytes buffer for constructing the disassembled string instead of naive string concatenation.  This makes a huge difference when disassembling scripts with large numbers of opcodes.
> txscript: Optimize DisasmString function.

- config.go
- doc.go
- peer.go
- sample-btcd.conf
- server.go
- wire/doc.go
- wire/msgversion.go
- wire/protocol.go
- wire/protocol_test.go
SFNodeBloom is a new service flag that a node is required to use to indicate that it supports bloom filtering.  This includes a protocol version bump to 70011 and a wire version bump to 0.3.0.
btcd:
The SFNodeBloom flag is set by default.  A new configuration option `--nopeerbloomfilters` has been added to to disable bloom filtering.
Any node advertising a version greater than or equal to 70011 that attempts to use bloom filtering will be disconnected if bloom filtering is disabled.
This mimics Bitcoin Core commit afb0ccaf9c9e4e8fac7db3564c4e19c9218c6b03
> Implement SFNodeBloom.

- txscript/scriptnum.go
- txscript/scriptnum_test.go
- txscript/stack.go
While current existing numeric opcodes are limited to 4 bytes, new
opcodes may need different limits.
This mimics Bitcoin Core commit 99088d60d8a7747c6d1a7fd5d8cd388be1b3e138
> txscript: Change makeScriptNum take a length argument

- blockchain/chain.go
- blockchain/common_test.go
- blockchain/example_test.go
- blockchain/scriptval.go
- blockchain/scriptval_test.go
- blockchain/validate.go
- blockmanager.go
- cmd/addblock/import.go
- cmd/findcheckpoint/findcheckpoint.go
- config.go
- cpuminer.go
- doc.go
- mempool.go
- mining.go
- rpcserver.go
- sample-btcd.conf
- server.go
- txscript/engine.go
- txscript/engine_test.go
- txscript/example_test.go
- txscript/opcode.go
- txscript/reference_test.go
- txscript/sigcache.go
- txscript/sigcache_test.go
- txscript/sign_test.go
This PR proposes the addition of an ECDSA signature verification cache
with a randomized entry eviction policy into btcd. 
The benefits of SigCache are two fold. Firstly, usage of SigCache mitigates 
a DoS attack wherein an attacker causes a victim's client to hang due to worst-case 
behavior triggered while processing attacker crafted invalid transactions. A 
detailed description of the mitigated DoS attack can be found [here](https://bitslog.wordpress.com/2013/01/23/fixed-bitcoin-vulnerability-explanation-why-the-signature-cache-is-a-dos-protection/). 
Secondly, usage of the SigCache introduces a signature verification 
optimization which speeds up the validation of transactions within a block, 
if they've already once been seen and verified within the mempool.
Implementation wise: 
The …
> Implement and integrate an ECDSA signature verification cache into btcd

- btcjson/chainsvrresults.go
The getinfo RPC will now include the errors attribute in the
result.
> btcjson: Add errors to InfoChainResult

- txscript/standard.go
We've already been generating lowS sigs for quite a while.  This removes
the malleability vector.
This mimics Bitcoin Core commit 49dd5c629df0a08cf3b1ea8085c03312d1a81696
> txscript:  Add ScriptVerifyLowS to the standard flags

- wire/bench_test.go
- wire/common.go
- wire/common_test.go
- wire/internal_test.go
- wire/msgalert.go
- wire/msgreject.go
- wire/msgversion.go
This pull request exports the `ReadVarString` and `WriteVarString` functions so they are available for callers to use.
A variable length string is encoded as a variable length integer containing the length of the string followed by the bytes that representthe string itself.
> wire: Export var length string serialization funcs.

- goclean.sh
- rpcserver.go
- server.go
- wire/blockheader.go
- wire/common.go
- wire/shahash.go
Also, update TravisCI goclean script to remove the special casing which ignored `Id` from the lint output since that exception is no longer needed.  It was previously required due to the old version of `btcjson`,
but that is no longer in the repo.
> Correct a few style related issues found by golint.

- config.go
- doc.go
- mempool.go
- mining.go
- rpcserver.go
- sample-btcd.conf
--minrelaytxfee allows the user to specify the minimum transaction
fee in BTC/kB in which the fee is considered a non-zero fee.
> config: New option --minrelaytxfee

- txscript/standard.go
- txscript/standard_test.go
isMultiSig was not verifying the number of pubkeys specified matched
the number of pubkeys provided.  This caused certain non-standard
scripts to be considered multisig scripts.
However, the script still would have failed during execution.
NOTE: This only affects whether or not the script is considered
standard and does NOT affect consensus.
> txscript: fix isMultiSig bug.

- peer/README.md
- peer/doc.go
- peer/peer.go
This fleshes out the doc.go documentation which is shown on godoc, the README.md shown on github, and improves a couple of comments for the fields in the Config struct.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/528)
> peer: Improve documentation.

- peer/peer.go
**NOTE: Requires pull request #445**
This pull request modifies the ping logic in the peer to ping on an interval regardless of what other messages are being sent versus the previous method of delaying the ping each time a message that is expected to receive data is sent.
This helps improve the ping statistics and simplifies its logic.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/517)
> peer: Ping on interval instead of delayed timer.

- peer/peer.go
**Requires #445**
*This is an alternative approach to #501 that is a more general solution and also fixes some concurrency-related issues with that PR as a side effect.*
This pull request implements stall detection logic at the peer level to detect and disconnect peers that are either not following the protocol in regards to expected response messages or have otherwise stalled.  This
is accomplished by setting deadlines for each message type which expects a response and periodically checking them while properly taking into account processing time.
There are an increasing number of nodes on the network which claim to be full nodes, but don't actually properly implement the entire p2p protocol even though they implement it enough to cause properly implemented nodes to make data requests to …
> peer: Implement stall detection.

- blockchain/README.md
- btcec/README.md
- btcjson/README.md
- chaincfg/README.md
- database/README.md
- peer/README.md
- txscript/README.md
- wire/README.md
First, it removes the documentation section from all the `README.md` files and instead puts a web-based godoc badge and link at the top with the other badges.  This is being done since the local godoc tool no longer ships with Go by default, so the instructions no longer work without first installing godoc. Due to this, pretty much everyone uses the web-based godoc these days anyways.  Anyone who has manually installed godoc won't need instructions.
Second, it makes sure the ISC license badge is at the top with the other badges and removes the textual reference in the overview section.
Finally, it's modifies the `Installation` section to `Installation and Updating` and adds a `-u` to the `go get` command since it works for both and thus is simpler.
[<img …
> docs: Make various README.md files consistent.

- peer/peer.go
**Requires #445**
This pull request modifies the peer logging so that it will not log an error when it's due to the remote peer disconnecting or the peer being forcibly disconnected or shutdown.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/524)
> peer: Don't log write errs due to disconnect.

- mempool.go
- policy.go
- policy_test.go
No functional change. Add tests.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/525)
> Move non-mempool specific functions to new file.

- blockchain/validate.go
- mining.go
- wire/blockheader.go
This commit implements the changeover logic for version 4 blocks as
described by BIP0065.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/535)
> Implement BIP0065 changeover logic for v4 blocks.

- policy.go
- policy_test.go
Specifically the number of KB is no longer rounded down to next integer.
Since this changes slightly the meaning of the 'minRelayTxFee' variable it has been renamed to 'relayTxFeeRate' and have deprecated the old config value associated with it and have added a new one.
See issue: https://github.com/btcsuite/btcd/issues/521
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/537)
> Altered min fee calculation function to match current Core behavior.

- blockmanager.go
- mempool.go
There's a bug in the logic that processes new blocks that causes txs to be unnecessarily dropped from mempool.
Basically:
There are two txs A and B in mempool. Tx B uses an output from A.
A new block is received that contains A but not B. 
RemoveTransaction(A) will be called on the mempool, which will recursively remove B. However, B should not be removed because it's not orphan, its parent is now on the blockchain.
This fixes the bug by not recursively removing depending transactions when processing blocks.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/539)
> Fix mempool transactions disappearing if a parent tx is confirmed.

- blockchain/validate.go
Removes a TODO by improving the error message.
In the presence of overflow, the actual output sum is still not negative and should not be reported as so.
I also realize that for bitcoin the overflow would have never occurred to begin with, but in other cryptocurrencies 2*MaxBaseUnits (whatever they call them) may overflow an int64 and the total in the error message would be negative.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/540)
> blockchain: Finish TODO by improving error message.

- server.go
This modifies the IP parsing code to work with IPv6 zone ids.  This is needed since the `net.ParseIP` function does not allow zone ids even though `net.Listen` does.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/538)
> server: Allow IPv6 addresses with zone id.

- chaincfg/params.go
- params.go
- server.go
This allows API users access to the DNS Seeds for use with SPV
clients, seeders, etc.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/544)
> chaincfg: Move DNS Seeds to chaincfg.

- peer/peer_test.go
In rare cases, the build fails with the error:
--- FAIL: TestPeerConnection (0.01s)
peer_test.go:296: Running 2 tests
peer_test.go:155: testPeer: wrong TimeOffset - got -1, want 0
https://travis-ci.org/btcsuite/btcd/jobs/87692240#L542
One reason this might happen is when the current timestamp is `1s` ahead of the message timestamp and the tick happens when the message is in transit.
Since the protocol is limited to one second precision, we do not have enough data to compare the timestamps any further. Therefore, I guess there will be some peer connections which inadvertently have an offset of `1s`. Updated the test case to handle this.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/543)
> Fix failing test case because of wrong TimeOffset

- mempool.go
ProcessTransaction could have accepted a new transaction into mempool
but could have returned a reject message if a no-longer-orphan
transaction failed to be accepted.  This would also skip any
additional no-longer-orphans, keeping them in the orphan pool.
Instead of returning an error incorrectly, log the error and skip
the no-longer-orphan transaction.  This allows the rest of the
no-longer-orphans to be processed as well.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/546)
> mempool: Remove returned error from ProcessOrphans

- mempool.go
- policy.go
- policy_test.go
This refactors the `checkTransactionStandard` function, along with related constants, from the mempool to the `policy.go` file since it is strictly related to policy.
In addition, it adds tests for the function which cover all code paths.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/548)
> mempool: Move checkTransactionStandard to policy.

- btcjson/chainsvrcmds.go
- btcjson/chainsvrcmds_test.go
- btcjson/chainsvrresults.go
- rpcserver.go
- rpcserverhelp.go
The new filteraddrs parameter enables the caller to pass a list of addresses to the searchrawtransactions API. Only inputs and outputs that match addresses in the list will be returned.
Additionally, if at least 1 filter address is passed then the (loooong) Hex attribute of the transaction will be empty.  ( though key is still present. )
To increase efficiency of the API particularly in terms of bandwidth usage, processing overhead for the caller, and overall roundtrip time.    The API is presently returning datasets that are 20+ MB for some addresses when the application may need only a tiny fraction of that.
My application displays a transaction history for one or more addresses.  To do this, it calls searchrawtransaction once per address.  It only needs to see the vin/vout entries that …
> adds filteraddrs param to searchrawtransactions API

- peer/peer.go
This defines the peer stat fields directly in the Peer struct instead of defining them in a separate struct and embedding them.  It is slightly more efficient this way and there is really no reason to have them
defined separately anyways since they are not passed around or otherwise used independently.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/556)
> peer: Combine stats struct into peer struct.

- peer/mruinvmap.go
- peer/mruinvmap_test.go
- peer/peer.go
This unexports the `mruInventoryMap` type since it is only needed within the peer package.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/557)
> peer: Unexport the mru inventory map.

- mempool.go
- mining.go
- policy.go
- rpcserver.go
This does three things:
- Splits the priority calculation logic from the `TxDesc` type
- Modifies the `calcPriority` function to perform the value age calculation instead of accepting it as a parameter
- Changes the starting priority to be calculated when the transaction is added to the pool
The first is useful as it is a step towards decoupling the mining code from the internals of the memory pool.  Also, the concept of priority is related to mining policy, so it makes more sense to have the calculations separate than being defined on the memory pool tx descriptor.
The second change has been made because everywhere that uses the `calcPriority` function first has to calculate the value age anyways and by making it part of the function it can be avoided altogether in
certain circumstances …
> mempool/mining: Decouple and optimize priority calcs.

- cpuminer.go
- mempool.go
- mining.go
- rpcserver.go
**This pull request requires #559 and #566.**
This introduces the concept of a new interface named `TxSource` which aims to generically provide a concurrent safe source of transactions to be considered for inclusion in a new block.  This is a step towards decoupling the mining code from the internals of btcd.  Ultimately the intent is to create a separate `mining` package.
The new `TxSource` interface relies on a new struct named `miningTxDesc`, which describes each entry in the transaction source.  Once this code is refactored into a separate mining package, the mining prefix can simply be dropped leaving the type exported as `mining.TxDesc`.
To go along with this, the existing `TxDesc` type in the mempool has been renamed to `mempoolTxDesc` and changed to embed the new `miningTxDesc …
> mempool/mining: Introduce TxSource interface.

- cpuminer.go
- mempool.go
- mining.go
- mining/README.md
- mining/mining.go
- mining/policy.go
- rpcserver.go
- server.go
**This pull request requires #563.**
This creates a skeleton mining package that simply contains a few of the definitions used by the mining and mempool code.
This is a step towards decoupling the mining code from the internals of btcd and ultimately will house all of the code related to creating block templates and CPU mining.
The main reason a skeleton package is being created before the full blown package is ready is to avoid blocking mempool separation which relies on these type definitions.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/567)
> mining: Create skeleton package.

- peer/peer.go
- server.go
DisableRelayTx sets the DisableRelayTx value in the version
message which informs the remote peer on whether to send
inv messages for transactions.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/574)
> peer: Add DisableRelayTx to config.

- server.go
The CPU miner relies on the mempool, so the mempool has to be created before calling the function to create the CPU miner.  When PR #568 introduced the mempool config struct, it moved the mempool creation
after the miner creation, which leads to the CPU miner crashing due to trying to access a nil mempool.
This move the CPU miner creation after the mempool creation appropriately.
Once the mempool and miner separation is done this won't matter anymore since the miner config will require a `mining.TxSource` which effectively enforces its creation first.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/578)
> server: Correct mempool/cpu miner initialize order.

- peer/peer.go
In case of an error during protocol negotiation in `handleVersionMsg`,
immediately break out and prevent further processing of `OnVersion`
listener which generally depends upon peer attributes like `NA` to be set
during the negotiation.
Fixes #579.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/580)
> peer: fix panic due to err in handleVersionMsg

- blockchain/validate.go
Tiny change: the substitution was wrong, causing a confusing error message.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/585)
> blockchain: Fix serialized coinbase height error message

- peer/peer.go
The getaddr msg is usually replied to with an addr msg, but if
the other peer does not have any addresses to share it will not
reply at all (instead of replying with an addr msg with 0 addresses).
Therefore, the getaddr msg is not guaranteed a reply, so this commit
removes it from stall detection to avoid incorrectly kicking
such peers.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/586)
> peer: remove getaddr msg from stall detection.

- server.go
The issue is that when the new connection is established, handleAddPeerMsg will be called later when the connection is established, the same way as regular (non-retry) connections. So the old peer needs to be deleted anyway, and the new one doesn't need to be added now. Otherwise entries from dead peers in the peerState stack up and hit the maxPeers limit.
I'm not sure if this is the best way to fix the issue since I'm not very familiar with the peer/server code. I'm open to alternate suggestions.
I'm able to reliably reproduce #577 in my setup, and I have tested this PR reliably fixes the issue: setting maxPeers to 1, using --connect, and causing the connection to fail and retry does not trigger the bug anymore, btcd will keep happily retrying forever.
Fixes #577.
[<img …
> server: remove peer from peerState even when doing a retry. Fixes #577

- txscript/sigcache_test.go
Changed the order of return values described in the docs to be
consistent with the function’s actual return value signature.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/590)
> txscript: Fix docs to match function.

- server.go
Updated `peerHandler` to drain `newPeers` before exiting so that any pending peers don't cause a hang on shutdown.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/584)
> peer: drain chans before exiting peerHandler

- btcjson/chainsvrcmds_test.go
- txscript/reference_test.go
For `btcjson`, it modifies the test for `createrawtransaction` to specify the constant size passed as an `int64`.  This is necessary because the `NewCmd` function accepts the parameters as interfaces in order to support varargs and a raw numeric constant is treated as an integer.  Since the constant value is larger than an `int32`, this causes certain platforms like ARM which treat a raw integer as a 32-bit integer to fail to compile.
For `txscript`, it modifies the conversion of the output index from the JSON-based test data for valid and invalid transactions to first convert to a signed int and then to an unsigned int.  This is necessary because the result of a direct conversion of a float to an unsigned int is implementation dependent and doesn't result in the expected value on all …
> Update btcjson and txscript tests to work properly on ARM

- wire/doc.go
- wire/message.go
- wire/msgsendheaders.go
- wire/msgsendheaders_test.go
- wire/msgversion.go
- wire/protocol.go
This implements the wire protocol encoding portion of a new sendheaders message as described by BIP0130.  It purpose is to request that a peer sends header commands instead of inv commands when announcing new blocks.  This includes a protocol version bump to 70012 and a wire version bump to 0.4.0.
Note that this does not implement logic to handle the command in btcd, rather it only makes the command available at the wire protocol level.  A future commit which honors the command and therefore provides full BIP0130 support is still required.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/572)
> wire: Implement sendheaders command (BIP0130)

- peer/doc.go
- peer/example_test.go
- peer/peer.go
- peer/peer_test.go
- server.go
This commit does not change functionality. It makes the creation of inbound and outbound peers more homogeneous. As a result the Start method of peer was removed as it was found not to be necessary. This is the first of several pull requests/commits designed to make the peer public API and internals less complex.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/617)
> peer: Consolidate Connect, Disconnect, Start, Shutdown public methods.

- server.go
This updates a couple of logging statements to use the `serverPeer` instance instead of the embedded `peer.Peer` so they are consistent with all of the other log statements.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/622)
> server: Make consistent use of server peer stringer.

- txscript/opcode.go
Change 'opcodeReserved' to 'opcodeInvalid'
Cherry-picked from downstream decred/dcrd#19.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/624)
> Fix documentation for opcodeInvalid

- txscript/opcode.go
This commit improves and corrects a few comments in `txscript` to ensure they match reality.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/625)
> txscript: Comment improvements and fixes

- config.go
- doc.go
- dynamicbanscore.go
- dynamicbanscore_test.go
- rpcserver.go
- sample-btcd.conf
- server.go
Dynamic ban scores consist of a persistent and a decaying component. The
persistent score can be used to create simple additive banning policies
simlar to those found in other bitcoin node implementations. The
decaying score enables the creation of evasive logic which handles
misbehaving peers (especially application layer DoS attacks) gracefully
by disconnecting and banning peers attempting various kinds of flooding.
Dynamic ban scores allow these two approaches to be used in tandem.
This pull request includes the following:
- Dynamic ban score type & functions, with tests for core functionality
- Ban score of connected peers can be queried via rpc (getpeerinfo)
- Example policy with decaying score increments on mempool and getdata
- Logging of misbehavior once half of the ban threshold …
> Implement banning based on dynamic ban scores

- .travis.yml
- README.md
Now that Go 1.6 has been released, update the required Go version in the `README` to 1.5 and add Go 1.6 to the configurations tested by TravisCI.
Also, while here, update the Go 1.4 and 1.5 versions tested by TravisCI to the latest point releases.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/638)
> Update TravisCI and README for Go 1.6.

- README.md
- docs/README.md
This commit updates the main `README.md` and `docs/README.md` files to replace the references to the now dead btcgui project with the Windows-only Paymetheus project.
While here, it also updates some information to make it more current and accurately describe the current status.
Closes #647.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/648)
> docs: Update READMEs with current details.

- .travis.yml
Since the latest `golint` no longer works with on Go 1.4 and Go 1.4 is no longer officially supported by btcsuite, remove it from the configurations tested by TravisCI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/651)
> TravisCI: Remove Go 1.4.3 tests.

- peer/peer.go
- server.go
This ensures the channel passed to QueueMessage is writable and that
QueueMessage will not read from the channel (write-only).
This change is merely a safety change.  If a user of the API passes
a read-only channel to QueueMessage, it will now be caught at compile
time instead of panicking during runtime.
Also update internal functions.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/594)
> peer: declare QueueMessage()'s doneChan as send only.

- peer/peer.go
- peer/peer_test.go
- server.go
This modifies the `peer` package to add support for the `sendheaders` protocol message introduced by `BIP0030`.
NOTE: This does not add support to btcd itself. That requires the server and sync code to make use of the new functionality exposed by these changes.  As a result, btcd will still be using protocol version 70011.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/618)
> peer: Implement sendheaders support (BIP0130).

- .travis.yml
The vet tool moved into the Go source tree as of Go 1.5.  Its previous location in the `x/tools` repo was deprecated at that time and has now been removed.
This updates the `.travis.yml` configuration to avoid fetching vet from the old location and to simply use the version now available as part of the standard Go install.
Also, while here, remove the check for changing to tool path since it is no longer needed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/655)
> TravisCI: Remove external go vet reference.

- config.go
- doc.go
- peer/peer.go
- sample-btcd.conf
- server.go
--blocksonly essentially disables the mempool.  Transactions will
not be accepted nor relayed.
Idea from Bitcoin Core.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/553)
> Add new configuration option --blocksonly

- blockmanager.go
This prevents the node from repeatedly requesting and rejecting the
same transaction as different peers inv the same transaction.
Idea from Bitcoin Core commit 0847d9cb5fcd2fdd5a21bde699944d966cf5add9.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/484)
> Keep track of recently rejected transactions.

- cpuminer.go
- mining.go
- rpcserver.go
This simply exports and adds some comments to the fields of the `BlockTemplate` struct.
This is primarily being done as a step toward being able to separate the mining code into its own package, but also it makes sense on its own because code that requests new block template necessarily examines the returned fields which implies they should be exported.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/659)
> mining: Export block template fields.

- blockmanager.go
This optimizes the way in which the maps are limited by the block manager.
Previously the code would read a cryptographically random value large enough to construct a hash, find the first entry larger than that value, and evict it.
That approach is quite inefficient and could easily become a bottleneck when processing transactions due to the need to read from a source such as `/dev/urandom` and all of the subsequent hash comparisons.
Luckily, strong cryptographic randomness is not needed here. The primary intent of limiting the maps is to control memory usage with a secondary concern of making it difficult for adversaries to force eviction of specific entries.
Consequently, this changes the code to make use of the pseudorandom iteration order of Go's maps along with the preimage …
> server: Optimize map limiting in block manager.

- chaincfg/params.go
- chaincfg/params_test.go
This modifies the `chaincfg` package to register the default network params via the `init` function instead of manually hard coding their data into the maps.  This is less error prone when adding new default networks.
A new function named `MustRegister` has been introduced that panics if there are any errors when registering the network that the new code makes use of and appropriate tests have been added.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/660)
> chaincfg: Register networks instead of hard coding.

- config.go
- mempool.go
- server.go
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/571)
> mempool:  Add a skeleton mempool pkg

- mining_test.go
This adds a test to ensure the priority queue works properly both for sorting by fee per KB and priorities.
Thanks to @ceejep for the original test code and idea which was subsequently modified and cleaned up a bit to the code here.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/666)
> mining: Add tests for prio queue.

- blockchain/chainio.go
The current code is needlessly checking the number of bytes needed to serialize the unspentness bitmap in the utxo against a maximum value that could never be returned because the function takes a `uint32` output index which is treated as a bit offset, and converts it bytes, which will necessarily be less than a max `uint32`.
This check also causes a compile error on arm where native integers are 32 bits.
This simply removes the unneeded check.
Fixes #664.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/665)
> blockchain: Remove unneeded unspentness size check.

- server.go
having 3 int32s above the uint64s in the struct
will cause mis-alignment for some 32-bit architectures.
see https://golang.org/pkg/sync/atomic/#pkg-note-BUG
This alligns bytesReceived and bytesSent.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/668)
> fix memory alignment for 32-bit architectures

- mining_test.go
This improves the tests of the priority queue to include the secondary sort ordering as well as adds some manual entries to ensure the edge conditions are properly tested.
This also brings the priority queue test coverage up to 100%.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/667)
> mining: Improve tests for prio queue.

- blockmanager.go
- mempool.go
- rpcserver.go
- server.go
It is not the responsibility of mempool to relay transactions, so
return whether the newly accepted transaction is an orphan to the
caller.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/547)
> mempool: Have ProcessTransaction return orphan status.

- log.go
This removes the logging functions that are now implemented in the peer package as they are no longer used by `btcd` itself and should have been removed when they were copied into the peer package.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/675)
> btcd: Remove peer-specific logging funcs.

- txscript/script.go
This changes the script template parsing function to use a pointer into the constant global opcode array for parsed opcodes as opposed to making a copy of the opcode entries which causes unnecessary allocations.
Profiling showed that after roughly 48 hours of operation, this copy was the culprit of 207 million unnecessary allocations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/677)
> txscript: Reduce script parse opcode allocs.

- blockchain/chain.go
- blockchain/chainio.go
This removes the root field and all references to it from the `BlockChain` struct since it is no longer required.
It was previously required because the chain state was not initialized when the instance was created.  However, that is no longer the case, so there is no reason to keep it around any longer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/680)
> blockchain: Remove unused root field.

- wire/bench_test.go
NOTE: This requires #678 in order for the reported allocation statistics to be correct.
This modifies the benchmarks in the wire package to avoid creating a new reader for each iteration.  This is useful since it means that showing the memory allocations will only show the function under test instead of the allocation for the benchmark setup as well.
The following is a before and after comparison of the allocations with the benchmarks that did not change removed:
```
benchmark              old allocs     new allocs     delta
------------------------------------------------------------
ReadVarInt1            2              1              -50.00%
ReadVarInt3            2              1              -50.00%
ReadVarInt5            2              1              -50.00%
ReadVarInt9            2 …
```
> wire: Don't allocate new readers in benchmarks.

- wire/bench_test.go
This adds decode benchmarks for several of the messages that profiling has identified to cause a lot of allocations in addition to those that already exist.  By adding these benchmarks, it makes it easier to get allocation and speed statistics which can in turn be used to compare future improvements.
The following bencharmarks have been added:
`DecodeGetHeaders`, `DecodeHeaders`, `DecodeGetBlocks`, `DecodeAddr`, `DecodeInv`,
`DecodeNotFound`, and `DecodeMerkleBlock`
For reference, here is the benchmark data as of this commit.
```
DecodeGetHeaders     93261 ns/op     24120 B/op     1004 allocs/op
DecodeHeaders      2071263 ns/op    368399 B/op    18002 allocs/op
DecodeGetBlocks      92486 ns/op     24120 B/op     1004 allocs/op
DecodeAddr          850608 ns/op    136202 B/op     9002 …
```
> wire: Add several decode benchmarks.

- blockmanager.go
- server.go
This adds support for serving headers instead of inventory messages in accordance with BIP0130.  btcd itself does not yet make use of the feature when receiving data.
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/671)
> btcd: sendheaders server support

- mining.go
Type feePerKB is an int64 and therefore is not correctly interpreted by format verb f.
> mining: Correctly format log messages.

- signal.go
- signalsigterm.go
When an OS reboots or shuts down, it sends all processes SIGTERM before
sending SIGKILL.  This allows btcd to do a proper shutdown which most
importantly closes the database.
> btcd: handle signal SIGTERM

- btcd.go
This reduces the target ratio of freshly allocated data to live data to 10% in order to limit excessive overallocations by the garbage collector during data bursts such as processing complex blocks or rapidly receiving a lot of large transactions.
This is part of the work towards addressing #649.
> main: Limit garbage collection percentage.

- .gitignore
- .travis.yml
- README.md
- glide.lock
- glide.yaml
- goclean.sh
This converts the project to allow `btcd` to be used with the `glide` package manager in order to provide stable and reproducible builds without the user having to jump through all of the hoops as they do today.
It consists of adding a `glide.yaml` file which identifies the project dependencies and locations along with a `glide.lock` file which contains the complete dependency tree pinned to specific versions.  Glide uses these files to download the packages (or updates) to a local `vendor` directory and checkout the correct pinned versions.  The go tool, in turn, is used to build/install `btcd` and will use the pinned versions in the `vendor` directory.
This also updates TravisCI to build using glide, removes some of the exceptions in the lint checks which are no longer required, and …
> build: Convert project to use glide.

- btcec/ciphering.go
This really bothered me when I read it for some reason...
> btcec: Minor correction to GenerateSharedSecret documentation.

- docs/README.md
The main README.md file had newer installation that uses Glide, while these did not.
> Update installation instructions using Glide

- cmd/addblock/addblock.go
- cmd/addblock/config.go
- cmd/addblock/import.go
This adds two new flags, `--txindex` and `--addrindex`, to the `addblock` utility which mirror the flags on `btcd`.  They serve to to specify that the transaction index and/or address index, respectively, should be
built while importing from the bootstrap file.
This is technically not 100% required since `btcd` will build the indexes on the first load (when enabled) if they aren't already built, however it is much faster to build the indexes as the blocks are being validated (particularly for the address index), so this makes the capability available.
> addblock: Add support for generating indexes.

- wire/bench_test.go
- wire/blockheader.go
- wire/common.go
- wire/msgaddr.go
- wire/msggetblocks.go
- wire/msggetdata.go
- wire/msggetheaders.go
- wire/msgheaders.go
- wire/msginv.go
- wire/msgmerkleblock.go
- wire/msgnotfound.go
- wire/msgtx.go
- wire/msgversion.go
- wire/netaddress.go
Live profiling data pulled from an instance of btcd running for a week shows that the vast majority of in-use (aka live) objects were the result of the deserialization process in wire.  In particular, the following were the top two entries of live objects when the memory pool contained 46,396 transactions:
```
4,637,941 39.44% 39.44%  wire.(*MsgTx).BtcDecode
4,511,685 38.37% 77.81%  wire.ReadVarBytes
```
This clearly shows that `77.81%` of all live allocations were allocated by transaction decoding and amounted to a total of `9,149,626` allocations.  Combining this with the fact there were `46,396` transactions in the memory pool, the average number of live allocations per deserialized transaction can be calculated as `196`.
Also, as shown by the following graph, the runtime overhead of …
> wire: Significantly reduce decoding allocs.

- cmd/btcctl/config.go
- config.go
- config_test.go
Implements #120 
When running btcd, if no configuration file is found, the sample-btcd.conf file is copied to the default path, with the rpcuser and rpcpass lines populated with random base64 encoded values.
When running btcctl, if no configuration file is found, it attempts to read the btcd.conf file at its default path, and create a basic btcctl.conf file by copying the rpcuser and rpcpass.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/609)
> Add automatic RPC configuration.

- peer/example_test.go
- peer/peer.go
- peer/peer_test.go
- server.go
This commit does not change functionality other than adjusting some logging messages. It moves version negotiation from the main read/write loops to initial Connect. This simplifies the message flow logic somewhat and will enable a simplified stall handler implementation in a future commit.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/626)
> peer: Extract protocol negotiation from main read and write loops.

- blockchain/chain.go
- blockchain/chain_test.go
- blockchain/common_test.go
- blockchain/example_test.go
- blockchain/process.go
- blockchain/reorganization_test.go
- blockmanager.go
- cmd/addblock/import.go
Rather than making the caller pass in the median time source on `ProcessBlock` and `IsCurrent`, modify the `Config` struct to include the median time source and associate it with the chain instance when it is
created.
This is being done because both the `ProcessBlock` and `IsCurrent` functions require access to the `blockchain` state already, it is a little bit safer to ensure the time source matches the chain instance state, it simplifies the caller logic, and it also allows its use within the logic of the `blockchain` package itself which will be required by upcoming rule change warning logic that is part of BIP9.
> blockchain: Associate time src with chain instance.

- blockchain/chain.go
If a block is known to exist in the memory chain or database then
there is no need to check the orphan pool.
> blockchain: optimize HaveBlock

- chaincfg/chainhash/README.md
- chaincfg/chainhash/doc.go
- chaincfg/chainhash/hash.go
- chaincfg/chainhash/hash_test.go
- chaincfg/chainhash/hashfuncs.go
- chaincfg/chainhash/hashfuncs_test.go
**This PR requires #728.**
This is a backport of the `chainhash` package made in Decred along with a few additional things cleaned up, finished test coverage, and rewording of some documentation to make it more generic.
In particular, the new package provides the definition of the hash type and associated hashing functions which will allow the rest of the code to be agnostic to the specific hash algorithm.
This only implements the package and does not change any of the code base over to use it.
> chainhash: Implement a new chainhash package.

- .travis.yml
This sets the `GO15VENDOREXPERIMENT` environment variable before glide is installed so vendoring is used when installing it as well.
> TravisCI: Set vendor experiment variable earlier.

- blockchain/chain.go
- blockchain/chain_test.go
- blockchain/common_test.go
- blockchain/difficulty.go
- blockchain/internal_test.go
- blockchain/reorganization_test.go
- blockchain/validate.go
- chaincfg/params.go
- mempool.go
- mining.go
- rpcserver.go
This moves several of the chain constants to the `Params` struct in the `chaincfg` package which is intended for that purpose.  This is mostly a backport of the same modifications made in `Decred` along with a few additional things cleaned up.
The following is an overview of the changes:
- Comment all fields in the `Params` struct definition
- Add locals to `BlockChain` instance for the calculated values based on the provided chain params
- Rename the following param fields:
- `SubsidyHalvingInterval` -> `SubsidyReductionInterval`
- `ResetMinDifficulty` -> `ReduceMinDifficulty`
- Add new Param fields:
- `CoinbaseMaturity`
- `TargetTimePerBlock`
- `TargetTimespan`
- `BlocksPerRetarget`
- `RetargetAdjustmentFactor`
- `MinDiffReductionTime`
> chaincfg/blockchain: Parameterize more chain consts.

- btcd.go
- rpcserver.go
- server.go
- service_windows.go
- signal.go
- signalsigterm.go
This rewrites the shutdown logic to simplify the shutdown signalling.  All cleanup is now run from deferred functions in the main function and channels are used to signal shutdown either from OS signals or from
other subsystems such as the RPC server and windows service controller.
The RPC server has been modified to use a new channel for signalling shutdown that is exposed via the `RequestedProcessShutdown` function instead of directly calling `Stop` on the server as it previously did.
Finally, it adds a few checks for early termination during the main start sequence so the process can be stopped without starting all the subsystems if desired.
This is a backport of the equivalent logic from Decred with a few slight modifications.  Credits go to @jrick.
> btcd: Simplify shutdown signal handling logic.

- txscript/scriptbuilder.go
- txscript/scriptbuilder_test.go
- txscript/sign.go
This exposes a new function on the `ScriptBuilder` type named `AddOps` that allows multiple opcodes to be added via a single call and adds tests to exercise the new function.
Finally, it updates a couple of places in the signing code that were abusing the interface by setting its private script directly to use the new public function instead.
Implements and closes #715
> txscript: Expose AddOps on ScriptBuilder.

- server.go
This reduces the mempool lock contention by removing an unnecessary check when responding to a `mempool` request.
In particular, the code first gets a list of all transactions from the mempool and then iterates them in order to construct the inventory vectors and apply bloom filtering if it is enabled.  Since it is possible that the transaction was removed from the mempool by another thread while that list is being iterated, the code was checking if each transaction was still in the mempool.  This is a pointless check because the transaction might still be removed at any point after the check anyways.  For example, it might be removed after the mempool response has been sent to the remote peer or even while the loop is still iterating.
> server: Remove superfluous check in OnMemPool.

- blockmanager.go
- config.go
- log.go
- mempool/README.md
- mempool/error.go
- mempool/log.go
- mempool/mempool.go
- mempool/policy.go
- mempool/policy_test.go
- mining.go
- rpcserver.go
- server.go
This does the minimum work necessary to refactor the mempool code into its own package.  The idea is that separating this code into its own package will greatly improve its testability, allow independent
benchmarking and profiling, and open up some interesting opportunities for future development related to the memory pool.
There are likely some areas related to policy that could be further refactored, however it is better to do that in future commits in order to keep the changeset as small as possible during this refactor.
Overview of the major changes:
- Create the new package
- Move several files into the new package:
- `mempool.go` -> `mempool/mempool.go`
- `mempoolerror.go` -> `mempool/error.go`
- `policy.go` -> `mempool/policy.go`
- `policy_test.go` -> `mempool/policy_test.go`
- …
> mempool: Refactor mempool code to its own package.

- wire/msgversion.go
- wire/msgversion_test.go
The protocol was silently upgrade in Core some time ago to enforce a limit of 256 for the user agent in version messages.  This updates wire to coincide with that change and consequently includes a wire version bump to 0.4.1.
Fixes #743.
> wire: Lower MaxUserAgentLen to 256.

- .travis.yml
- glide.lock
- glide.yaml
- rpcserver_test.go
- rpctest/README.md
- rpctest/blockgen.go
- rpctest/doc.go
- rpctest/memwallet.go
- rpctest/node.go
- rpctest/rpc_harness.go
- rpctest/rpc_harness_test.go
- rpctest/utils.go
This PR addresses #116 by creating a new package (`rpctest`) which provides functionality for writing automated black-box tests to exercise the RPC interface. 
An instance of a `rpctest` consists of an active `btcd` process running in (typically) `--simnet` mode, a `btcrpcclient` instance connected to said node, and finally an embedded in-memory wallet instance (the `memWallet`) which manages any created coinbase outputs created by the mining `btcd` node. 
As part of the `SetUp` process for an RPC test, a test author can optionally opt to have a test blockchain created. The second argument to `SetUp` dictates the number of mature coinbase outputs desired. The `btcd` process will then be directed to generate a test chain of length: `100 + numMatureOutputs`. 
The embedded `memWallet` …
> Create new rpctest packaged for rpc driven integration testing. 

- server.go
If you have a small number of nodes in a test network (e.g. two nodes where one is pending) then the number of tries may not get incremented resulting in a tight loop that spins essentially endlessly.
> don't spin forever looking for peers

- rpcserver_test.go
This PR adds a `defer` statement at the top of  `TestRpcServer`
which will attempt a `recover` which tears down all active harnesses in
the event that one of the tests causes a panic in the main goroutine.
Before this PR, if a buggy test caused a panic while all
integration tests were being executed, then any active harnesses would
fail to be properly torn down. This would cause the running btcd
processes to be leaked, possibly interfering with future test runs until
the process was manually killed. This PR fixes such behavior.
In order to aid in debugging, when a test panics, the test # is 
printed out along with a full stack-trace from the start of the test 
to the panic point.
> rpctest: prevent leaking processes in integration tests due to panics

- blockchain/chain.go
- blockchain/chainio.go
This adds a new field to the best chain state snapshot for the calculated past median time as returned by the `calcPastMedianTime` function.  This is useful since it provides fast access to it without having to acquire the chain lock which is needed to recalculate it.
This will ultimately allow the associated exported function to be removed since it only exists to be able to calculate this exact value, however this commit only introduces the new field in order to keep the changes minimal.
> blockchain: Add median time to state snapshot.

- mempool/mempool.go
- server.go
This modifies the config for the new `mempool` package such that it takes a callback function to obtain the best chain height instead of requiring a fully initialized `blockchain.BlockChain` instance.
This will make it much easier to test the `mempool` since the tests will be able to provide their own height function to test various functionality without having create and manipulate full blocks and chain instances.
> mempool: Break dependency on chain instance.

- blockchain/utxoviewpoint.go
- mempool/mempool_test.go
This adds a basic test harness infrastructure for the mempool package which aims to make writing tests for it much easier.
The harness provides functionality for creating and signing transactions as well as a fake chain that provides utxos for use in generating valid transactions and allows an arbitrary chain height to be set.  In order to simplify transaction creation, a single signing key and payment address is used throughout and a convenience type for spendable outputs is provided.
The harness is initialized with a spendable coinbase output by default and the fake chain height set to the maturity height needed to ensure the provided output is in fact spendable as well as a policy that is suitable for testing.
Since tests are in the same package and each harness provides a unique pool …
> mempool: Add basic test harness infrastructure.

- config.go
- doc.go
- mempool/mempool.go
- rpcserver_test.go
- sample-btcd.conf
- server.go
This PR adds two new cli flags: one for accepting non-std transactions, and the other for rejecting non-std transactions.
The two flag are rejected when used concurrently. Config parsing is set up such that, the desired policy expressed via the config always overrides the policy set by default for a particular chain.
The `mempool`'s `Policy` config has been modified to add a new `RelayNonStd` bool which is checked when validating transactions rather than the policy as dicated by the current `ChainParams` instance. 
Finally, the current set of integration tests has been modified to ensure the main harness always rejects non-standard transactions. With this change, although we're using `simnet` parameters, the harness' transaction validation/acceptance should reflect that policy on mainnet,
> config: introduce new flags to accept/reject non-std transactions

- mempool/policy.go
This changes the transaction input standardness checks as follows:
- Allow any script in a pay-to-script-hash transaction to be relayed and mined so long as it has no more than 15 signature operations
- Remove the obsolete checks which naively calculated the number of expected inputs in favor of the more accurate `ScriptVerifyCleanStack` and `ScriptVerifySigPushOnly` functionality of the script engine that was added after these checks.
> mempool: Improve tx input standard checks.

- config.go
> config: Replace log outputs with fmt.Fprintln.

- rpcserver_test.go
- rpctest/rpc_harness_test.go
This modifies the `rpctest` harness to call the `TearDown` function in the `SetUp` error path.  This ensures any resources, such as temp directories, that were created during setup before whatever the failure that caused the error are properly cleaned up.
Fixes #762.
> rpctest: Cleanup resources on failed setup.

- blockchain/scriptval_test.go
1. Return early when failing on `len(blocks) > 1`.
2. Check for `len(blocks) == 0` so we can fail on that condition with an error message instead of a panic.
> blockchain: make scriptval_test fail more nicely

- goclean.sh
This commit modifies the goclean.sh to execute all the tests amongst
the packages serially. The default behavior of the `go test` command is
to execute all tests in parallel amongst the listed packages. This
behavior can at times cause tests which use the `rpctest` package to
fail due to multiple `btcd` nodes attempting to bind to the same port
simultaneously. As only one node can successfully bind to the port, the
btcd processes for the other concurrent harness instances exit silently
causing the RPC clients to fail with connection timeouts as their
target process no longer exists. Executing all tests serially
eliminates such a race condition which can cause non-deterministic test
failures.
Fixes #766.
> build: execute tests across all packages serially

- goclean.sh
- rpctest/rpc_harness.go
- rpctest/rpc_harness_test.go
- rpctest/utils.go
This modifies the ports that are selected for use for the p2p and rpc ports to start with a port that is based on the process id instead of a hard-coded value.  The chosen ports are incremented for each running instance similar to the previous code except the p2p and rpc ports and now split into ranges instead of being 2 apart.
This is being done because the previous code only worked for a single process which means it prevented the ability to run tests in parallel.
The new approach will work with multiple processes, however it must be stated that there is still a very small probability that the stars could align resulting in the same ports being selected.
Finally, this also reverts the recent change to run tests serially since this fixes the underlying cause for that change.
Fixes #766.
> rpctest: Use ports based on the process id.

- rpctest/rpc_harness.go
Use os.Getpid() to get the process ID, not os.Getppid(), which returns
the parent process ID.  This resulted in multiple calls to
generateListeningAddresses() getting the same listening ports.
> rpctest: Fix typo

- goclean.sh
- rpcserver_test.go
- rpctest/rpc_harness_test.go
This adds a new build tag named `rpctest` which must be set in order for `rpctest`-based tests to be executed.  The new build tag is also added to the `goclean.sh` script which is executed by Travis during continuous integration builds.
This change is being made because the `rpctest` framework requires additional careful user configuration to ensure the version of `btcd` under test can be programmatically launched from the system path with
all of the necessary ports open whereas all of the other tests are self-contained within the test binary itself.
Since said additional configuration is typically not done, it leads to a lot of false positives.  Putting the tests behind a build tag allows them to remain to be available and run during continuous integration without imposing the additional …
> rpctest: Gate rpctest-based behind a build tag.

- addrmgr/addrmanager.go
allAddr was being allocated with counters instead of the actual size
of the address map.  This led to the possibility of including nils
in the returned slice, which resulted in a panic.
> addrmgr: Fix AddressCache to not include nils

- blockchain/accept.go
- blockchain/chain.go
- blockchain/chain_test.go
- blockchain/example_test.go
- blockchain/process.go
- blockchain/reorganization_test.go
- blockmanager.go
- cmd/addblock/import.go
This modifies the `blockchain.ProcessBlock` function to return an additional boolean as the first parameter which indicates whether or not the block ended up on the main chain.
This is primarily useful for upcoming test code that needs to be able to tell the difference between a block accepted to a side chain and a block that either extends the main chain or triggers a reorganize that causes it to become the main chain.  However, it is also useful for the `addblock` utility since it allows a better error in the case a file with out of order blocks is provided and will also be useful for the eventual multi-peer code.
> blockchain: Expose main chain flag on ProcessBlock.

- peer/peer.go
- server.go
This makes the enforcement of the bloom filter service bit much more strict.  In particular, it does the following:
- Moves the enforcement of the bloom filter service bit out of the `peer` package and into the server so the server can ban as necessary
- Disconnect peers that send filter commands when the server is configured to disable them regardless of the protocol version
- Bans peers that are a high enough protocol version that they are supposed to observe the service bit is disabled, but ignore it and send filter commands regardless.
As an added bonus, this fixes the old logic which had a bug in that it was examining the *remote* peer's supported services in order to choose whether or not to disconnect instead of the *local* server's supported services.
> peer: Strictly enforce bloom filter service bit.

- mempool/mempool_test.go
**This PR requires #750**
This adds a test to the mempool for ensuring that orphans are evicted when exceeding the max orphan policy setting as expected.
> mempool: Add test for max orphan entry eviction.

- blockchain/chain.go
- blockmanager.go
This removes the exported `CalcPastTimeMedian` function from the `blockchain` package as it is no longer needed since the information is now available via the `BestState` snapshot.
Also, update the only known caller of this, which is the chain state in block manager, to use the snapshot instead.  In reality, now that everything the block manager chain state provides is available via the
`blockchain` `BestState` snapshot, the entire thing can be removed, however that will be done in a separate to commit to keep the changes targeted.
> blockchain: Remove exported CalcPastTimeMedian func.

- wire/doc.go
- wire/message.go
- wire/msgfeefilter.go
- wire/msgfeefilter_test.go
- wire/protocol.go
feefilter is used to request the receiving peer does not announce any
transactions below the specified minimum fee rate.
NOTE: This only implements the new message type in the `wire` package.  Further PRs will be needed to the `peer` package and `btcd` itself to implement and respond to the message.
> wire: implement feefilter message

- peer/peer.go
- peer/peer_test.go
Requires #753 
NOTE: This only implements the new message type in the `peer` package. Further PRs will be needed to btcd itself to implement and respond to the message.
> peer: Implement feefilter p2p message (bip0133)

- btcec/field.go
- btcec/field_test.go
As noted in issue #706, the existing code had an issue where the normalized result was > P when both the first and second words of the field representation being normalized were BOTH greater than or equal to the first and second words of P.  Although this condition is rare in practice, it needs to be handled properly.
This resolves the issue by comparing the low words in the final reduction step against the normalized low order prime bits to ensure the final subtraction occurs correctly any time they're > P.  This approach
retains the constant time property as well.
Also, it merges and squashes in the additional commits with tests provided by @jimmysong in #707 to help prevent regressions.  It is being done this way to ensure master stays green.
Fixes #706.
> btcec: Ensure reduction when > P in all cases.

- blockchain/chain.go
- mempool/mempool.go
- peer/mruinvmap.go
- peer/mrunoncemap.go
- peer/peer.go
- rpcwebsocket.go
- server.go
defer's are nice for readability but they do add overhead.  This
gets rid of defer's where it is just as easy as not to use one.
> Optimize by removing defers

- mempool/mempool.go
- mempool/mempool_test.go
- mempool/policy.go
- mempool/policy_test.go
- server.go
This PR implements [BIP 113](https://github.com/bitcoin/bips/blob/master/bip-0113.mediawiki) which modifies the time-lock threshold Bitcoin nodes use to determine if a transaction's lock-time has been satisfied or not. Before BIP 113, simply the time stamp within the blockheader of the block including a candidate transaction was consulted. However, this allows miners to fiddle with the timestamp on their blocks in order to include transactions which haven't yet matured by wall-clock time, thereby collecting more fees. 
After this PR, the MTP of the prior 11 blocks will be used in order to calculate the currently lock-time threshold for all transactions accepted into the mempool. 
A brief summary of this PR follows: 
* A new closure within the `mempool`'s Policy config has been added which …
> Mempool-only BIP 113: Median Time Past for lock-time calculations

- btcjson/chainsvrresults.go
- rpcserver.go
- rpcserverhelp.go
Only return the p2sh address if the script is not a
pay-to-scripthash.
> rpcserver: avoid nested decodescript p2sh addrs

- txscript/standard.go
- txscript/standard_test.go
This corrects the `isNullData` standard transaction type test to work properly with canonically-encoded data pushes.  In particular, single byte data pushes that are small integers (0-16) are converted to the
equivalent numeric opcodes when canonically encoded and the code failed to detect them properly.
It also adds several tests to ensure that both canonical and non-canonical nulldata scripts are recognized properly and modifies the test failure print to include the script that failed.
This does not affect consensus since it is just a standardness check.
> txscript: Correct nulldata standardness check.

- rpctest/node.go
- rpctest/rpc_harness.go
This modifies the `rpctest` framework to start `btcd` with the appropriate network flags depending on the provided parameters.
Previously, it always started `btcd` with `--simnet` even if other parameters, such as those for the regression test network, were provided.
> rpctest: Choose flags based on provided params.

- config.go
- rpcwebsocket.go
There are two possible designs that can be used for throttling: fanout with a set number of goroutines that are always running, or a semaphore with a new goroutine started each time.  I am in favor of using the semaphore as it allows easily bumping up the max number of concurrent requests without paying a higher constant overhead for the added goroutines.
Fixes #504.
> Concurrently handle websocket client JSON-RPC requests

- txscript/standard.go
- txscript/standard_test.go
NullDataScript takes a byte array and constructs a null data output script. This is used for constructing transactions that contain extra data in provably prunable outputs. 
There is also a bug fix in isNullData.
> txscript: Add null data script creator

- txscript/standard.go
- txscript/standard_test.go
This modifies the recently-added `NullDataScript` function in several ways in an effort to make them more consistent with the tests in the rest of the code base and improve/correct the logic:
- Use the `hexToBytes` and `mustParseShortForm` functions
- Consistently format the test errors
- Replace the `valid` bool flag with an expected error and test against it
- Ensure the returned script type is the expected type in all cases
> txscript: Cleanup and improve NullDataScript tests.

- peer/example_test.go
- peer/peer.go
- peer/peer_test.go
- server.go
As mentioned in #653 the renamed the method which associates the connection to the peer as `AssociateConnection` rather than `Connect` for clarity.
> peer: rename peer.Connect to AssociateConnection

- chaincfg/params.go
- connmgr/seed.go
- server.go
DNSSeed defines a DNS Seed with a hostname and whether it supports
filtering by service flag bits.
> chaincfg: Introduce new type DNSSeed

- mempool/mempool.go
- server.go
This renames the `mempool.Config.RelayNonStd` option to `AcceptNonStd` which more accurately describes its behavior since the `mempool` was refactored into a separate package.
The reasoning for this change is that the `mempool` is not responsible for relaying transactions (nor should it be).  Its job is to maintain a pool of unmined transactions that are validated according to consensus and policy configuration options which are then used to provide a source of transactions that need to be mined.
Instead, it is the server that is responsible for relaying transactions.  While it is true that the current server code currently only relays txns that were accepted to the `mempool`, this does not necessarily have to be the case.  It would be entirely possible (and perhaps even a good idea as …
> mempool: Rename RelayNonStd config option.

- mempool/mempool.go
This optimizes the way in which the mempool oprhan map is limited in the same way the server block manager maps were previously optimized.
Previously the code would read a cryptographically random value large enough to construct a hash, find the first entry larger than that value, and evict it.
That approach is quite inefficient and could easily become a bottleneck when processing transactions due to the need to read from a source such as `/dev/urandom` and all of the subsequent hash comparisons.
Luckily, strong cryptographic randomness is not needed here. The primary intent of limiting the maps is to control memory usage with a secondary concern of making it difficult for adversaries to force eviction of specific entries.
Consequently, this changes the code to make use of the …
> mempool: Optimize orphan map limiting.

- config.go
- doc.go
- rpcserver.go
- rpcwebsocket.go
- sample-btcd.conf
This PR aims to improve JSON-RPC compatibility with software that relies on the behavior of the reference implementation. The PR itself consists of two commits which resolve two separate compatibility issues reported under #632. 
In order to avoid interoperability issues with software that relies on Core's behavior, terminate HTTP POST JSON-RPC responses with a newline.
Core always terminates the response with a newline. While this is not mandated by the specification, the lack of a closing newline may cause undesired side effects with software sharing code for handling JSON-RPC over HTTP and raw socket transports (e.g. stratum). It certainly causes issues with ckpool.
This commit intentionally limits the scope of this compatibility improvement to only affect HTTP POST, not WebSocket. …
> rpcserver: Improve JSON-RPC compatibility

- mempool/mempool_test.go
This introduces a new pool membership test function to the mempool testing infrastructure and refactors the tests to make use of it.
It is useful since it is common logic that is not only needed in the existing tests, but will be needed by most mempool-related tests.
> mempool: Refactor pool membership test logic.

- blockmanager.go
- mempool/mempool.go
- mempool/mempool_test.go
**This requires PR #805**
This modifies the way orphan removal and processing is done to more aggressively remove orphans that can no longer be valid due to other transactions being added or removed from the primary transaction pool.
The net effect of these changes is that orphan pool will typically be much smaller which greatly improves its effectiveness.  Previously, it would typically quickly reach the max allowed worst-case usage and effectively stay there forever.
The following is a summary of the changes:
- Modify the map that tracks which orphans redeem a given transaction to instead track by the specific outpoints that are redeemed
- Modify the various orphan removal and processing functions to accept the full transaction rather than just its hash
- Introduce a new flag on …
> mempool: Stricter orphan evaluation and eviction.

- mempool/log.go
- mempool/mempool.go
**This requires PR #806**
This implements orphan expiration in the `mempool` such that any orphans that have not had their ancestors materialize within 15 minutes of their initial arrival time will be evicted which in turn will remove any other orphans that attempted to redeem it.
In order to perform the evictions with reasonable efficiency, an opportunistic scan interval of 5 minutes is used.  That is to say that there is not a hard deadline on the scan interval and instead it runs when a new orphan is added to the pool if enough time has passed.
The following is an example of running this code against the main network for around 30 minutes:
> 23:05:34 2016-10-24 [DBG] TXMP: Expired 3 orphans (remaining: 254)
> 23:10:38 2016-10-24 [DBG] TXMP: Expired 112 orphans (remaining: 231)
> …
> mempool: Implement orphan expiration.

- mining.go
This prevents the ability for duplicate transactions to be added to the mining priority heap when a transaction spends multiple outputs from the same input transaction by converting the dependency tracking to use a map keyed by the transaction hash instead of a linked list.
It follows up the discussion in #692 and updates the diff provided in the comments there to use the `chainhash` package.
Fixes #691
> mining: fix duplicate transactions in prio heap

- mining.go
This fixes a bug where a transaction would loose reference to other transactions dependant on it when being considered for inclusion in a new block template. The issue only occurs when the transaction being considered triggers a change of priority queue ordering to ordering by fee. It results in none of the dependant transactions being considered for inclusion in the new block template.
> mining: Stop transactions losing their dependants.

- mempool/mempool.go
- mempool/policy.go
- mining.go
- mining/policy.go
This moves the priority-related code from the `mempool` package to the mining package and also exports a new constant named `UnminedHeight` which takes the place of the old unexported `mempoolHeight`.
Even though the mempool makes use of the priority code to make decisions about what it will accept, priority really has to do with mining since it influences which transactions will end up into a block.  This change also has the side effect of being a step towards enabling separation of the mining code into its own package which, as previously mentioned, needs access to the priority calculation code as well.
Finally, the `mempoolHeight` variable was poorly named since what it really represents is a transaction that has not been mined into a block yet.  Renaming the variable to more …
> mining/mempool: Move priority code to mining pkg.

- blockmanager.go
- cpuminer.go
- mining.go
- rpcserver.go
This removes the block manager chain state in favor of using the `blockchain.BlockChain` instance now that it is safe for concurrency.
> bmgr: Remove block manager chain state.

- cpuminer.go
- mining.go
- rpcserver.go
- server.go
**This requires PR #809**
This introduces a new type named `BlkTmplGenerator` which encapsulates the various state needed to generate block templates.
This is useful since it means code that needs to generate block templates can simply accept the generator rather than needing access to all of the additional state which in turn will ultimately make it easier to split the mining code into its own package.
> mining: Introduce a block template generator.

- blockchain/accept.go
- blockchain/chain.go
- blockchain/chain_test.go
- blockchain/validate.go
- blockchain/validate_test.go
- mempool/mempool.go
- mempool/mempool_test.go
- mempool/policy.go
- mempool/policy_test.go
- mining.go
- server.go
- wire/msgtx.go
This commit implements [BIP 68](https://github.com/bitcoin/bips/blob/master/bip-0068.mediawiki) which repurposes the sequence number as defined within the `wire.TxIn`'s of a transaction. This repurposing allows for consensus enforced _relative_ lock-times based on the set sequence numbers of all inputs within a transaction. Transactions which violate the required input maturity governed by sequence numbers are not allowed into the mempool, rejected when found within a block, and skipped over when assembling blocks. This PR currently only enforces the behavior when accepting candidate transaction to the mempool. 
This PR is dependent on #712 as it rebases on top of the latest changes to that branch. By *default* all checks for input maturity based on sequence numbers must use the MTP of …
> Mempool-only BIP 68: relative lock-time via consensus-enforced sequence numbers

- cpuminer.go
- server.go
This introduces a `cpuminerConfig` type which contains the necessary information to break the direct dependency on the main server instance.
This change is a step towards being able to separate the cpu miner into its own subpackage.  No functional change.
> cpuminer: Introduce cpuminerConfig.

- mining/policy_test.go
This adds some basic tests for the priority calculation code in the mining policy.
> mining: Add basic priority calculation tests.

- blockchain/fullblocktests/generate.go
- blockchain/validate_test.go
- glide.lock
- mempool/mempool_test.go
- mining/mining.go
- peer/peer_test.go
- rpcserver.go
- rpctest/blockgen.go
- rpctest/memwallet.go
- txscript/example_test.go
- txscript/reference_test.go
- txscript/sign_test.go
- wire/message_test.go
- wire/msgtx.go
- wire/msgtx_test.go
**Requires PR btcsuite/btcutil#82**
This modifies the `NewMsgTx` function to accept the transaction version as a parameter and updates all callers.
The reason for this change is so the transaction version can be bumped in wire without breaking existing tests and to provide the caller with the flexibility to create the specific transaction version they desire.
> wire: Make NewMsgTx accept the tx version.

- peer/peer.go
This adds a new field to the peer struct which stores the protocol version advertised by the remote peer and updates `StatsSnapshot` to return the advertised version instead of the negotiated version.
> peer: Track and return advertised protocol version

- peer/peer.go
- server.go
This corrects a few issues introduced with the connection manager where the server was not notifying the connection manager when a connection request is available again.
The cases resolved are:
- Unable to initialize a server peer instance in response to the connection
- Failure to associate the connection with the server peer instance
- Disconnection of a non-persistent outbound peer
It also changes the log message to a debug in the former case because it's not something that should be shown to the user as an error given it's not due to anything the user has misconfigured nor is it even unexpected if an invalid address is provided.
Finally, it also changes the log message in peer for inability to start a peer to debug since the inability for a peer to negotiate is not something that …
> server: Notify connmgr of available connection requests.

- cpuminer.go
- log.go
- mining/cpuminer/README.md
- mining/cpuminer/cpuminer.go
- mining/cpuminer/log.go
- rpcserver.go
- server.go
This does the minimum work necessary to refactor the CPU miner code into its own package.  The idea is that separating this code into its own package will improve its testability and ultimately be useful to other parts of the codebase such as the various tests which currently effectively have their own stripped-down versions of this code.
The API will certainly need some additional cleanup and changes to make it more usable outside of the specific circumstances it was originally designed to support (namely the generate RPC), however it is better to do that in future commits in order to keep the changeset as small as possible during this refactor.
Overview of the major changes:
- Create the new package
- Move `cpuminer.go` -> `cpuminer/cpuminer.go`
- Update mining logging to use the new …
> cpuminer: Refactor code to its own package.

- blockmanager.go
- log.go
- mempool/mempool.go
- mempool/mempool_test.go
- rpcserver.go
- server.go
This removes any remaining orphan transactions that were sent by a peer when it disconnects since it is extremely unlikely that the missing parents will ever materialize from elsewhere.
In order to achieve this, there are three individual commits.  The first commit modifies `mempool` to allow a tag to be associated with orphan transactions and uses the peer ID as the tag for each transaction.
The second commit modifies `mempool` to provide a `RemoveOrphansByTag` which, as its name implies, allows callers to remove all orphans associated with a given tag (and also any orphans that depend on the removed orphans, recursively).
The final commit modifies server to invoke the new `RemoveOrphansByTag` function with the peer ID as each peer disconnects.
The following shows the PR is action (IP …
> server/mempool: Evict orphans on peer disconnect

- config.go
- doc.go
- mempool/policy.go
- mempool/policy_test.go
- sample-btcd.conf
The current max orphan transaction size causes problems with dependent transaction relay due to its artificially small size in relation to the max standard transaction size.
Consequently, this modifies the orphan transaction policy by increasing the max size of each orphan to the same value allowed for standard non-orphan transactions and reducing the default max allowed number of orphans to 100.
From a memory usage standpoint, the worst case max mem usage prior to this change was 5MB plus structure and tracking overhead (1000 max orphans * 5KB max each).  With this, that is raised to 10MB (100 max orphans * 100KB max each) in the worst case.
It is important to note that the values were originally implemented as a naive means to control the size of the orphan pool before several of the …
> mempool: Modify default orphan tx policy.

- server.go
The number of max outbound connections cannot be more max peers, so we cap that at max peers.
> server: Cap max outbound at max peers

- .travis.yml
- goclean.sh
This switches goclean to use gometalint instead of running each
checking tool one at a time.
This runs them concurrently.
More importantly it will allow us to easily add additional
linters as desired.
> Switch to gometalint in goclean

- addrmgr/knownaddress_test.go
- upgrade.go
This makes two modifications based on the results of `staticcheck`.
The first is to use a simplified zero value for the time in the `addrmgr` package tests.
The second is check any errors when opening a directory while attempting to perform old version upgrades.
> addrmgr/btcd: Updates for staticcheck results.

- addrmgr/network.go
- blockchain/chain.go
- blockchain/validate.go
- blockmanager.go
- config.go
- database/ffldb/blockio.go
- peer/peer.go
- rpcserver.go
- rpctest/memwallet.go
- rpctest/rpc_harness.go
- rpcwebsocket.go
- txscript/scriptbuilder.go
- wire/msgalert.go
This removes all unnecessary typecast conversions as found by the [unconvert](https://github.com/mdempsky/unconvert) linter.
> multi: Remove unnecessary convs found by unconvert.

- goclean.sh
**This PR requires #837**
#This modifies the `goclean.sh` script to include the [gosimple](https://github.com/dominikh/go-simple) lint tool to the `gometalinter` configuration.
> build: Add gosimple linter to goclean.sh.

- goclean.sh
**This PR requires #836**
This modifies the `goclean.sh` script to include the [unconvert](https://github.com/mdempsky/unconvert) lint tool in the `gometalinter` configuration.
> build: Add unconvert linter to goclean.sh.

- connmgr/connmanager.go
- connmgr/connmanager_test.go
- server.go
By default `connmgr` maintains a fixed number of connections (defaults to 8). In addition to this, connections can be added using the `node connect` rpc. Therefore it is more accurate to refer to the limit as a target rather than max. Accordingly renamed references in the code from max to target.
In case we already have more than the default number of target connections, we should be able to drop a connection without triggering a auto retry. This has been fixed.
If we have hit max peers, we cannot accommodate any new outbound peers. Therefore it's better to exit early and avoid making an unnecessary connection.  This has been fixed.
> connmgr: Retry only if below target outbound conns

- wire/message_test.go
- wire/msgaddr_test.go
- wire/msgversion_test.go
- wire/netaddress.go
- wire/netaddress_test.go
**This PR requires #841**
Rather than accepting a `net.Addr` interface and returning an error when it's not specifically a `*net.TCPConn`, just accept a `*net.TCPConn` directly so the compiler will assert it.  Also, remove the error return since it can no longer occur.
> wire: Change NewNetAddress to accept a *net.TCPConn.

- connmgr/connmanager.go
- connmgr/connmanager_test.go
- server.go
This modifies the connection manager to provide support for accepting inbound connections on a caller-provided set of listeners and notify the caller via a callback.
This is only the minimum work necessary to get inbound support into the connection manager.  The intention for future commits is to move more connection-related logic such as limiting the maximum number of overall connections and banned peer tracking into the connection manager.
It is split into 3 commits:
* The first commit removes the type definitions for the callback functions in favor of declaring them directly in the `Config` struct. since it is more consistent with the rest of the code base and is preferred since it means callers reviewing the documentation don't have to follow another level of indirection to figure out …
> connmgr: Implement inbound connection handling.

- config.go
- connmgr/connmanager.go
- connmgr/connmanager_test.go
- server.go
This commit modifies the ConnManager to use the `net.Addr interface through the package instead of a plain string to represent and manipulate addresses. This change makes the package much more general as users of the package can possibly utilize custom implementations of the net.Addr interface to establish connections.
More precisely, the `ConnReq` struct has been modified to use a net.Addr instance explicitly, and the `DialFunc` type has also been modified to take a `net.Addr` directly. This latter change gives functions that adhere to the `DialFunc` type more flexibility as to exactly how the connection is established.
My motivation for this change is that I'd like to use the `connmgr` package within [`lnd`](https://github.com/lightningnetwork/lnd) to manage attempting to establish …
> connmgr: switch to using net.Addr interface throughout for addresses

- peer/peer.go
This modifies the error handling path in the peer read loop such that it will no longer log an error when the error is `io.ErrUnexpectedEOF`.  This is being done because that error is almost always the result of a peer
being remotely disconnected and thus it isn't useful information to log.
However, since it might actually be due to a malformed message, a reject message is still queued up to be sent back to the peer (which will simply be discarded if the peer disconnected) before it is disconnected.
While it would be ideal to only log if it's not due to a disconnect, and the code already attempts to handle that, it's not 100% possible to detect upon the read returning an error without attempting to read again
which will not happen until the next loop iteration.
> peer: No error log on unexpected EOF.

- peer/peer.go
The check in `LocalAddr` was stricter than necessary, causing it to return `nil` for a disconnected peer. Updated to only return `nil` if the peer never connected. 
Fixes #846.
> peer: disconnected peer - return non-nil LocalAddr

- addrmgr/addrmanager.go
- addrmgr/addrmanager_test.go
- server.go
addrmgr.GetAddress() had a parameter `class string` originally intended
to support looking up addresses according to some type of filter such as
IPv4, IPv6, and only those which support specific wire.ServiceFlags
(full nodes, nodes that support bloom filters, nodes that support
segwit, etc). But currently the parameter is unused and also has an
inappropriate type `string`.
If it would ever be used, it's easy to add back and should then get an
appropriate type such as something that allows bitflags to be set so
that the caller could request combinations such as peers that support
IPv6, are full nodes, and support bloom filters.
> addrmgr: Remove unused param from GetAddress()

- docs/code_contribution_guidelines.md
Add a paragraph about prefixing commit message summaries with the
package/subsystem that they're changing to
code_contribution_guidelines.md.
> docs: Clarify model commit message summary

- goclean.sh
This modifies the `goclean.sh` script to expand the deadline for the linters to run to 4 minutes and ensures the comments match reality.
> build: Give linters longer and cleanup goclean.sh.

- server.go
I came across this, not sure if that was intended behavior, but it could currently break without having added any messages.
> btcd: fix error in mempool response inv counting

- blockchain/chain.go
- blockchain/chainio.go
- blockchain/error.go
- blockchain/error_test.go
- blockchain/thresholdstate.go
- blockchain/thresholdstate_test.go
- blockchain/versionbits.go
- chaincfg/params.go
- integration/bip0009_test.go
- mining/mining.go
- peer/peer_test.go
- rpctest/rpc_harness.go
- rpctest/rpc_harness_test.go
- wire/bench_test.go
- wire/blockheader.go
- wire/blockheader_test.go
- wire/message_test.go
- wire/msgblock_test.go
- wire/msgheaders_test.go
- wire/msgmerkleblock_test.go
This adds all of the infrastructure needed to support BIP0009 soft forks.
The following is an overview of the changes:
- Add new configuration options to the chaincfg package which allows the rule deployments to be defined per chain
- Implement code to calculate the threshold state as required by BIP0009
- Use threshold state caches that are stored to the database in order to accelerate startup time
- Remove caches that are invalid due to definition changes in the params including additions, deletions, and changes to existing entries
- Detect and warn when a new unknown rule is about to activate or has been activated in the block connection code
- Detect and warn when 50% of the last 100 blocks have unexpected versions.
- Remove the latest block version from wire since it no longer …
> Implement infrastructure for BIP0009.

- blockchain/chain.go
- blockchain/fullblocktests/params.go
- blockchain/validate.go
- chaincfg/params.go
**NOTE: This depends on #792**
Now that all softforking is done via BIP0009 versionbits, replace the old `isMajorityVersion` deployment mechanism with hard coded historical block heights at which they became active.
Since the activation heights vary per network, this adds new parameters to the `chaincfg.Params` struct for them and sets the correct heights at which each softfork became active on each chain.
It should be noted that this is a technically hard fork since the behavior of alternate chain history is different with these hard-coded activation heights as opposed to the old `isMajorityVersion` code.  In
particular, an alternate chain history could activate one of the soft forks earlier than these hard-coded heights which means the old code would reject blocks which violate the new …
> blockchain: Remove isMajorityVersion code.

- txscript/opcode.go
The CSV consensus rules dictate that the opcode fails when the transaction version is not at least version 2, however that only applies if the disable flag is not set in the sequence.
This is not an issue at the current time because we do not yet enforce CSV at a consensus level, however, I noticed this discrepancy when doing a thorough audit of the CSV paths due to the ongoing work to add full
consensus-enforced CSV support.
As a result, this must be merged prior to enabling consensus enforcement for CSV or it would open up the potential for a hard fork.
> txscript: Only do CSV txver check if enabled.

- blockchain/chainio.go
- blockchain/thresholdstate.go
- blockchain/versionbits.go
The `thresholdState` and `deploymentState` functions expect the block node for the block prior to which the threshold state is calculated, however the startup code which checked the threshold states was using the current best node instead of its parent.
While here, also update the comments and rename a couple of variables to help make this fact more clear.
> blockchain: Correct startup threshold state warns.

- addrmgr/addrmanager.go
- addrmgr/addrmanager_test.go
- addrmgr/knownaddress_test.go
- addrmgr/network_test.go
- connmgr/seed.go
- peer/peer.go
- wire/netaddress.go
Replace assignments to individual fields of wire.NetAddress with
creating the entire object at once, as one would do if the type was
immutable.
> wire: Treat NetAddress more like immutable

- btcjson/chainsvrresults.go
- glide.lock
- rpcserver.go
- rpcserverhelp.go
This commit implements the `getblockchaininfo` as it's defined in BC to the best of btcd's current capabilities. Due to some differences in header storage, and `BIP0009` state storage between `btcd` and BC, some of the information within the call isn't readily or easily accessible to `btcd`, therefore they are currently blank within the PR.
> rpc: implement getblockchaininfo 

- integration/bip0009_test.go
- rpctest/rpc_harness.go
- rpctest/utils.go
** This PR requires #871 **
This adds tests which exercise the BIP0009 state transitions using the newly available soft fork status information in the `getblockchaininfo` RPC.
The following is an overview of the tests added:
- Assert the chain height is 0 and the state is `ThresholdDefined`
- Generate 1 fewer blocks than needed to reach the first state transition
- Assert chain height is expected and state is still `ThresholdDefined`
- Generate 1 more block to reach the first state transition
- Assert chain height is expected and state moved to `ThresholdStarted`
- Generate enough blocks to reach the next state transition window, but only signal support in 1 fewer than the required number to achieve `ThresholdLockedIn`
- Assert chain height is expected and state is still …
> integration: Add BIP0009 state transition tests

- server.go
Change the order of conditions to avoid calling fmt.Sprintf
unnecessarily.
> server.go: Optimize newAddressFunc

- goclean.sh
Fail fast if glide or gometalinter isn't available.
And also fail if running glide or gometalinter fails.
Before goclean.sh could pass even if glide or gometalinter wasn't
available at all. It seems that even though we use `set -ex`, their
failure was hidden either inside the $() or behind the pipe.
> goclean.sh: Make it more robust

- LICENSE
- btcjson/btcdextcmds.go
- btcjson/btcdextcmds_test.go
- btcjson/btcdextresults.go
- btcjson/btcdextresults_test.go
- docs/json_rpc_api.md
- rpcserver.go
- rpcserverhelp.go
This pull request is a backport of the `version` JSON-RPC API command from dcrd. It permits the JSON-RPC API to have its own semantic versioning scheme separate from the underlying software. The initial version is 1.0.0. This pull request resolves issue #886.
> Add `version` command to JSON-RPC API for API versioning

- btcjson/btcdextcmds.go
- btcjson/btcdextcmds_test.go
- btcjson/btcdextresults.go
- btcjson/btcdextresults_test.go
- chaincfg/chainhash/hash.go
- docs/json_rpc_api.md
- rpcserver.go
- rpcserverhelp.go
- server.go
This pull request is the backport of the `getheaders` JSON-RPC API command from Decred's dcrd. It allows a client to download headers for an arbitrary range of blocks.
This PR resolves issue #883.
> Port `getheaders` JSON-RPC command from dcrd

- config.go
If a host is down and doesn't send a TCP RST, the net.Dial function
blocks until the OS times out the connection.  Convert to using
DialTimeout with a 30 second default timeout.
> btcd: use DialTimeout.

- LICENSE
- txscript/doc.go
- txscript/engine.go
- txscript/engine_test.go
- txscript/error.go
- txscript/error_test.go
- txscript/opcode.go
- txscript/opcode_test.go
- txscript/script.go
- txscript/script_test.go
- txscript/scriptbuilder.go
- txscript/scriptbuilder_test.go
- txscript/scriptnum.go
- txscript/scriptnum_test.go
- txscript/stack.go
- txscript/stack_test.go
- txscript/standard.go
- txscript/standard_test.go
This converts the majority of script errors from generic errors created via `errors.New` and `fmt.Errorf` to use a concrete type that implements the error interface with an error code and description.
This allows callers to programmatically detect the type of error via type assertions and an error code while still allowing the errors to provide more context.
For example, instead of just having an error that reads `disabled opcode` as would happen prior to these changes when a disabled opcode is encountered, the error will now read `attempt to execute disabled opcode OP_FOO`.
While it was previously possible to programmatically detect many errors due to them being exported, they provided no additional context and there were also various instances that were just returning errors created on …
> txscript: Significantly improve errors.

- txscript/data/script_tests.json
- txscript/engine.go
- txscript/error.go
- txscript/error_test.go
- txscript/opcode.go
- txscript/reference_test.go
- txscript/standard.go
ScriptVerifyNullFail defines that signatures must be empty if a
CHECKSIG or CHECKMULTISIG operation fails.
This also enables `ScriptVerifyNullFail` at the mempool policy level.
> txscript: Implement ScriptVerifyNullFail

- blockchain/chain.go
- blockchain/chain_test.go
- blockchain/checkpoints.go
- blockchain/common_test.go
- blockchain/reorganization_test.go
- blockchain/validate.go
- blockmanager.go
- config.go
- doc.go
- sample-btcd.conf
Adds a config option and cmd line flag `--checkpoint` that allows for defining custom checkpoints that will be used for verifying the active chain.
It also changes the way `--nocheckpoints` is handled: instead of keeping a flag to indicate checkpoint support, the built-in checkpoints and possible custom checkpoints are copied into the blockchain struct. This allows for overwriting the built-in ones as well.
I did not add tests for testing the flag, I wouldn't know where to start, but I can give it a shot if it's preferred!
> Add support for defining additional checkpoints

- goclean.sh
The most recent version of glide creates a working directory named `.glide` that includes .go files and thus must be excluded from the find operation that generates merged test coverage of all packages.
> build: Exclude .glide from test coverage.

- blockchain/chain.go
- blockchain/chain_test.go
- blockchain/checkpoints.go
- blockchain/reorganization_test.go
- blockmanager.go
- config.go
- doc.go
This contains a bit of cleanup and additional logic to improve the recently-added ability to specify additional checkpoints via the `--addcheckpoint` option.
In particular:
- Improve error messages in the checkpoint parsing
- Correct the `mergeCheckpoints` function to weed out duplicate height checkpoints while using the most-recently provided one as described by its comment
- Add an assertion to `blockchain.New` that the provided checkpoints are sorted as required
- Keep comments to 80 columns and use two spaces after periods in them to be consistent with the rest of the code base
- Make the entry in `doc.go` match the actual `btcd -h` output
> multi: Improvements to configurable checkpoints.

- .travis.yml
This modifies the `.travis.yml` file to install a release version of glide instead of using its latest master branch.  This will prevent upstream changes from inadvertently breaking the CI builds.
> TravisCI: Use release version of glide.

- btcjson/chainsvrwscmds.go
- btcjson/chainsvrwscmds_test.go
- btcjson/chainsvrwsntfns.go
- btcjson/chainsvrwsntfns_test.go
- btcjson/chainsvrwsresults.go
- btcjson/chainsvrwsresults_test.go
- docs/json_rpc_api.md
- rpcserver.go
- rpcserverhelp.go
- rpcwebsocket.go
This PR adds backported versions of `loadtxfilter` and `rescanblocks` commands from `dcrd` along with new `relevanttxaccepted`, `filteredblockconnected` and `filteredblockdisconnected` notifications which include additional information including the full block header and serialized transactions that match the loaded filter for the websocket client.
This is a complete replacement for old spend and receive transaction notification system which has been marked deprecated and will be removed in a future release.  In particular, the `rescan`, `notifyreceived`, `stopnotifyreceived`, `notifyspent`, and `stopnotifyspent` commands and the associated notifications `recvtx`, `redeemingtx`, `rescanprogress`, and `rescanfinished` have been deprecated in favor of the new filter-based approach.  In …
> Backport filter-based JSON-RPC commands from dcrd

- blockchain/accept.go
- blockchain/chain.go
This modifies the `blockchain` code to store all blocks that have passed proof-of-work and contextual validity tests in the database even if they may ultimately fail to connect.
This eliminates the need to store those blocks in memory, allows them to be available as orphans later even if they were never part of the main chain, and helps pave the way toward being able to separate the download logic from the connection logic.
> blockchain: Store side chain blocks in database.

- glide.lock
- rpctest/memwallet.go
- rpctest/rpc_harness.go
This modifies the `rpctest` harness and its associated `memwallet` to make use of the new filter-based notifications since the old notifications are now deprecated.
It also updates the `glide.lock` file to require the necessary `btcrpcclient` version.
> rpctest: Update to use new filtered block ntfns.

- blockchain/chain.go
- blockchain/chainio.go
- blockchain/difficulty.go
- blockchain/internal_test.go
- blockchain/timesorter.go
- blockchain/timesorter_test.go
- blockchain/validate.go
This modifies the block nodes used in the `blockchain` package for keeping track of the block index to use `int64` for the timestamps instead of `time.Time`.
This is being done because a `time.Time` takes 24 bytes while an `int64` only takes 8 and the plan is to eventually move the entire block index into memory instead of the dynamically-loaded version, so cutting the number of bytes used for the timestamp by a third is highly desirable.
Also, the consensus code requires working with unix-style timestamps anyways, so switching over to them in the block node does not seem unreasonable.
Finally, this does not go so far as to change all of the `time.Time` references, particularly those that are in the public API, so it is purely an internal change.
> blockchain: Use int64 timestamps in block nodes.

- blockchain/chain.go
This removes the `CalcPastMedianTime` since it is now exposed much more efficiently via the `MedianTime` field of the `BestState` snapshot returned from the `BestSnapshot` function.
> blockchain: Remove unused median time calc func.

- btcjson/chainsvrcmds.go
- btcjson/chainsvrcmds_test.go
- btcjson/chainsvrresults.go
- rpcserver.go
> btcjson: Add getmempoolentry API

- blockchain/chain.go
- rpcserver.go
- server.go
**This PR requires #911**
This modifies the block node structure to include a couple of extra fields needed to be able to reconstruct the block header from a node, and exposes a new function from chain to fetch the block headers which takes advantage of the new functionality to reconstruct the headers from memory when possible.  Finally, it updates both the p2p and RPC servers to make use of the new function.
This is useful since many of the block header fields need to be kept in order to form the block index anyways and storing the extra fields means the database does not have to be consulted when headers are requested if the associated node is still in memory.
The following timings show representative performance gains as measured from one system:
```
new: Time to fetch 100000 headers: …
```
> blockchain: Reconstruct headers from block nodes.

- blockchain/process.go
Since the code base is currently in the process of changing over to decouple download and connection logic, but not all of the necessary parts are updated yet, ensure blocks that are in the database, but do
not have an associated main chain block index entry, are treated as if they do not exist for the purposes of chain connection and selection logic.
> blockchain: Ignore side chains in exists check.

- blockchain/blockindex.go
- blockchain/blocklocator.go
- blockchain/chain.go
- blockchain/chainio.go
- blockchain/fullblocks_test.go
- blockchain/thresholdstate.go
- blockchain/thresholdstate_test.go
- blockchain/validate.go
- blockmanager.go
- cmd/findcheckpoint/findcheckpoint.go
- mining/cpuminer/cpuminer.go
- mining/mining.go
- rpcserver.go
- rpcwebsocket.go
- server.go
**This PR requires #916**
This modifies the `blockNode` and `BestState` structs in the `blockchain` package to store hashes directly instead of pointers to them and updates callers to deal with the API change in the exported `BestState` struct.
In general, the preferred approach for hashes moving forward is to store hash values in complex data structures, particularly those that will be used for cache entries, and accept pointers to hashes in arguments to functions.
Some of the reasoning behind making this change is:
- It is generally preferred to avoid storing pointers to data in cache objects since doing so can easily lead to storing interior pointers into other structs that then can't be GC'd
- Keeping the hash values directly in the block node provides better cache locality
> blockchain: Use hash values in structs.

- rpcserver.go
This PR adds the `getblockheader` RPC call to the `rpcLimited` map to allow the limited user access to the command.
> rpcserver: Allow limited user access to `getblockheader` command.

- blockchain/fullblocktests/generate.go
- blockchain/validate.go
- btcec/signature.go
- goclean.sh
- mining/cpuminer/cpuminer.go
- txscript/stack.go
- wire/fixedIO_test.go
- wire/msgtx.go
This simplifies the code based on the recommendations of the [gosimple](https://github.com/dominikh/go-simple) lint tool.
Also, it increases the deadline for the linters to run to 10 minutes and reduces the number of threads that is uses. This is being done because the Travis environment has become increasingly slower and it also seems to be hampered by too many threads running concurrently.
> multi: Simplify code per gosimple linter.

- goclean.sh
This modifies the `goclean.sh` script that is executed on Travis to only run the tests once.
While it is nice to see coverage reports in the log, unfortunately it appears that both the `-race` and `-cover` flags can't be used together, and the tests have grown in complexity such that they are starting to get close to TravisCI time limits.
> TravisCI: Only run tests once.

- rpctest/rpc_harness.go
This PR creates a `P2PAddress()` function for `Harness` to allow tests to connect directly to the P2P port of harness `btcd` instances. This is useful for, e.g., SPV client testing.
> rpctest: Add P2PAddress() for Harness to get P2P listen address

- glide.lock
- glide.yaml
- rpcwebsocket.go
- txscript/opcode.go
Now that glide is used for version management and a specific commit of the upstream repository can be locked it is no longer necessary to maintain a fork of the package specifically to keep a stable dependency.
While here, update the glide dependency for `btcutil` as well since it was switched to use the upstream path as well.
> multi: Switch to upstream golang.org/x/crypto.

- blockchain/chain.go
- blockchain/chain_test.go
- blockchain/thresholdstate.go
- blockchain/validate.go
- chaincfg/params.go
- integration/csv_fork_test.go
- rpcserver.go
- rpctest/blockgen.go
- rpctest/rpc_harness.go
This commit fully implements the CSV-package soft-fork. The CSV-package soft-fork bundles the deployment of the following BIPs: [68](https://github.com/bitcoin/bips/blob/master/bip-0068.mediawiki), [112](https://github.com/bitcoin/bips/blob/master/bip-0112.mediawiki), and [113](https://github.com/bitcoin/bips/blob/master/bip-0113.mediawiki). The activation logic of the soft-fork is governed by [BIP 9](https://github.com/bitcoin/bips/blob/master/bip-0009.mediawiki), VersionBits. 
This PR currently is built upon a combined branch includes #713, #628, #712, and #755. Therefore, **only the last 3 commits** should be examined during code-review. As the aforementioned pending PR's re merged into master, this PR will be updated accordingly to increasingly reflect the final diff. 
A summary of …
> Implement the CSV-Package soft-fork via BIP0009 VersionBits

- peer/peer.go
This removes the field that tracks whether the version has been sent since it is no longer used after the version negotiation was separated from the main read and write code.
> peer: Remove unused version sent field.

- peer/peer.go
This changes the nonce generated to detect self connections over to use pseudo randoms instead of a cryptographically random nonce.
There is really not a good reason for it to be cryptographically strong, using the prng is much faster, and the prng also doesn't burn entropy.
> peer: Use prng to generate self detection nonce.

- config.go
- doc.go
- peer/peer.go
- peer/peer_test.go
- sample-btcd.conf
- server.go
Just like Core's -uacomment, this flag allows to specify user agent
comments like defined in BIP 14.
> config: Add user agent comments flag --uacomment

- chaincfg/params.go
This DNS seed does not appear to resolve IPv6 and the returned addresses rarely seem correspond to functioning nodes.
> chaincfg: Remove bitseed.xf2.org DNS seed.

- btcjson/chainsvrresults.go
This updates the `GetNetworkInfoResult` structure to include the latest fields added to Core for compatibility purposes.
While here, also move the definitions of the subtypes for the result before their use for consistency.
> btcjson: Update GetNetworkInfoResult.

- database/doc.go
This updates the overview documentation to remove reference of the outside Namespace bits.
> database: Update overview documentation in doc.go.

- README.md
- blockchain/README.md
- blockchain/fullblocktests/README.md
- blockchain/indexers/README.md
- btcec/README.md
- btcjson/README.md
- chaincfg/README.md
- chaincfg/chainhash/README.md
- connmgr/README.md
- database/README.md
- database/ffldb/README.md
- database/internal/treap/README.md
- docs/README.md
- docs/code_contribution_guidelines.md
- docs/configuring_tor.md
- docs/json_rpc_api.md
- docs/using_bootstrap_dat.md
- integration/README.md
- integration/rpctest/README.md
- mempool/README.md
- mining/README.md
- mining/cpuminer/README.md
- peer/README.md
- txscript/README.md
- wire/README.md
The github markdown interpreter has been changed such that it no longer allows spaces in between the brackets and parenthesis of links and now requires a newline in between anchors and other formatting.  This
updates all of the markdown files accordingly.
While here, it also corrects a couple of inconsistencies in some of the `README.md` files.
> multi: Update markdown files for GFM changes.

- addrmgr/addrmanager.go
- addrmgr/addrmanager_test.go
- addrmgr/doc.go
- addrmgr/network.go
- blockchain/thresholdstate.go
- blockchain/validate.go
- blockmanager.go
- btcjson/help.go
- config.go
- database/driver.go
- peer/peer.go
- server.go
- upnp.go
- wire/protocol.go
There's no typos in variables, so it should be just comments.
> Fix a ton of typos accumulated over time

- addrmgr/knownaddress.go
- connmgr/tor.go
- server.go
- txscript/script.go
- txscript/sign.go
Some suggestions by [ineffassign](https://github.com/gordonklaus/ineffassign) that looks for unnecessary assignments.
I left two at the end of fullblocktest, since I suspected the unused
variable assignments there were set for the possibility of extending the
tests.
```
btcd/connmgr/tor.go
Line 107: warning: err assigned and not used (ineffassign)
btcd/server.go
Line 2227: warning: err assigned and not used (ineffassign)
btcd/txscript/script.go
Line 352: warning: idx assigned and not used (ineffassign)
btcd/txscript/sign.go
Line 193: warning: err assigned and not used (ineffassign)
btcd/addrmgr/knownaddress.go
Line 45: warning: lastSeen assigned and not used (ineffassign)
btcd/blockchain/fullblocktests/generate.go
Line 2131: warning: chain1TipName assigned and not used (ineffassign)
```
> Fix warnings from ineffassign

- btcec/bench_test.go
- btcec/btcec.go
- btcec/btcec_test.go
- btcec/field.go
- btcec/field_test.go
This modifies the normalize function of the internal field value to both optimize it and address an issue where the reduction could lead to an incorrect result with a small range of values along with some tests to ensure the behavior is correct.
It also contains contributions from @jimmysong to optimize NAF to avoid returning the unneeded bit when there is not a carry and adds a bunch of unit tests.
The following benchmark shows the relative speedups as a result of the optimization on my system.  In particular, the changes result in approximately a 14% speedup in Normalize, which ultimately translates to a 2% speedup in signature verifies.
```
benchmark                        old ns/op     new ns/op     delta
-------------------------------------------------------------------- …
```
> btcec: Optimize normalize and NAF, correct normalize, and add tests.

- blockchain/chain.go
- blockchain/chainio.go
- blockchain/chainio_test.go
- blockchain/reorganization_test.go
- blockchain/utxoviewpoint.go
- btcjson/cmdparse.go
- database/ffldb/blockio.go
- peer/mruinvmap.go
- peer/mrunoncemap.go
- wire/msgaddr_test.go
- wire/msgblock_test.go
- wire/msgfeefilter_test.go
- wire/msgfilteradd_test.go
- wire/msgfilterclear_test.go
- wire/msgfilterload_test.go
- wire/msggetaddr_test.go
- wire/msggetblocks_test.go
- wire/msggetdata_test.go
- wire/msggetheaders_test.go
- wire/msgheaders_test.go
- wire/msginv_test.go
- wire/msgmempool_test.go
- wire/msgnotfound_test.go
- wire/msgping_test.go
- wire/msgpong_test.go
- wire/msgsendheaders_test.go
- wire/msgtx_test.go
- wire/msgverack_test.go
- wire/msgversion_test.go
**This PR builds on #964**
This corrects the assertion in the `decodeSpentTxOut` function so it does not improperly cause a panic when unwinding transactions during a reorg under certain circumstances.  In particular, the provided transaction
version that is passed when a stxo entry does not exist is now -1 in order to properly distinguish it from the zero value.
It also updates the tests accordingly.
This was discovered by the reorg on testnet from block `00000000000018c58c2d2816f03dac327d975a18af6edf1a369df67ecddaf816` to `0000000000001c1161a367156465cc6226e9f862d9c585f94db5779fdf5455ff`.
> blockchain: Correct invalid assertion.

- goclean.sh
This modifies the `goclean.sh` script that is executed on Travis to only run the tests without the race detector.
While it is nice to run the race detector on the tests, unfortunately there is a limit to the number of goroutines that can be launched while running it.  Since Travis is now much slower than it once was, this
causes a ton of false positive failures.
> TravisCI: Don't run tests with race.

- btcjson/chainsvrcmds.go
- btcjson/chainsvrcmds_test.go
- rpcserver.go
- rpcserverhelp.go
- server.go
Hello,
I have implemented a new RPC command that will be [available on version 0.15.0](https://github.com/bitcoin/bitcoin/commit/1680ee0edf46aa22c4d00c8ff4f3d0bcc235bc68) of the Bitcoin Core client.
The command allows the user to check how long (in seconds) the server has been running for. I have used btcsuite in the past so I decided to implement this change here as well.
Please review this PR and let me know of any changes/improvements required. I will also implement the command in the `btcrpcclient` package at a later date.
Thank you,
Ricardo Velhote
> New RPC command to display the uptime of the server

- peer/peer.go
This changes fixes shuffling algorithm in PushAddrMsg to select a uniformly random subset of the given addresses using Fisher-Yates. As currently implemented, I'm pretty sure it does not produce a uniformly sampled permutation.
> peer: Improve address sampling in PushAddrMsg.

- mempool/mempool.go
This removes the standardness check to reject transactions with a lock time greater than a maxint32 because the old bitcoind nodes which it was designed to protect against are no longer valid for other reasons and
thus there are no longer any of them on the network to worry about.
> mempool: Remove potential negative locktime check.

- blockchain/chain.go
- blockchain/notifications.go
- blockchain/notifications_test.go
- blockmanager.go
The BlockChain struct emits notifications for various events, but it is only possible to register one listener. This changes the interface and implementations to allow multiple listeners.
https://github.com/btcsuite/btcd/pull/979/files#diff-34c6b408d72845d076d47126c29948d1R2419
> blockchain: Allow multiple subscribers to notifications.

- blockmanager.go
- rpcserver.go
- server.go
This PR removes some unnecessary references from blockManager to server.
The blockManager uses the server to obtain a reference to the txMemPool, which it interacts with many times. Since one of the responsibilities of the blockManager is to keep the mempool in sync, it should have store its own reference. 
The blockManager also sends notifications to the RPC server, in response to chain events. I don't think the blockManager should know anything about the RPC server, so instead the RPC server will listen directly to notifications emitted from the BlockChain.
https://github.com/btcsuite/btcd/issues/978
> blockmanager: Decouple from server.

- rpcadaptors.go
- rpcserver.go
- rpcwebsocket.go
- server.go
**NOTE:  This will most certainly conflict with #656 and #979, so it will need to be rebased and updated accordingly after those are merged**
This decouples the RPC server from the internal btcd server to move closer to being able to split it out into a separate package.
In order to accomplish this, it introduces an `rpcserverConfig` type and several new interfaces, named `rpcserverPeer`, `rpcserverConnManager`, and `rpcserverBlockManager`, which are necessary to break the direct dependencies on the main server and block manager instances.
It also adds concrete implementations of the new interfaces and uses them to configure the RPC server.
Ultimately, the RPC server should ideally be decoupled even more such that all of the types in the configuration struct use interfaces instead of the …
> rpcserver: Decouple from server.

- rpcserver.go
- server.go
**This PR requires on #981 and is currently rebased on top of #982**.
This refactors the RPC server to accept and take ownership of already configured listeners and refactors the logic to setup those listeners to the server.  This mirrors the logic used by the connection manager and is desirable since it is another step closer to being able to split the RPC server code out into a separate package and will make it much easier to internally test since it allows creating mock listeners.
> rpcserver: Refactor listener logic to server.

- blockchain/chain.go
- blockchain/notifications.go
- blockchain/notifications_test.go
This takes care of a few minor nits on the recently merged subscribe code.  In particular:
- Avoid extra unnecessary allocation on notifications slice
- Avoid defer overhead on notification mutex in `sendNotifications`
- Make test function comment start with the name of the function per Effective Go guidelines
- Use constant for number of subscribers in test
- Don't exceed column 80 in test print
> blockchain: Consistency pass on subscribe code.

- blockmanager.go
- server.go
Instead of having both server and blockManager be aware of the txProcessed and blockProcessed channels, now the server passed them as method arguments to blockProcessor.
Works towards https://github.com/btcsuite/btcd/issues/978.
> main: Reduce shared state between server and blockManager.

- blockchain/accept.go
- blockchain/blockindex.go
- blockchain/blocklocator.go
- blockchain/chain.go
- blockchain/chainio.go
- blockchain/difficulty.go
- blockchain/process.go
- blockchain/thresholdstate.go
- blockchain/validate.go
- blockchain/versionbits.go
- mining/mining.go
**This requires PR #917**
This reworks the block index code such that it loads all of the headers in the main chain at startup and constructs the full block index accordingly.
Since the full index from the current best tip all the way back to the genesis block is now guaranteed to be in memory, this also removes all code related to dynamically loading the nodes and updates some of the logic to take advantage of the fact traversing the block index can longer potentially fail.  There are also more optimizations and simplifications that can be made in the future as a result of this.
Due to removing all of the extra overhead of tracking the dynamic state, and ensuring the block node structs are aligned to eliminate extra padding, the end result of a fully populated block index now takes quite …
> blockchain: Convert to full block index in mem.

- blockchain/chain.go
- blockchain/checkpoints.go
- blockchain/process.go
- blockchain/validate.go
**This requires PR #919**
This modifies the code that determines the most recently known checkpoint to take advantage of recent changes which make the entire block index available in memory by only storing a reference to the specific node in the index that represents the latest known checkpoint.
Previously, the entire block was stored and new checkpoints required loading it from the database.
> blockchain: Optimize checkpoint handling.

- blockchain/chainview.go
- blockchain/chainview_test.go
This implements a new type in the `blockchain` package that takes advantage of the fact that all block nodes are now in memory to provide a flat view of a specific chain of blocks (a specific branch of the
overall block tree) from a given tip all the way back to the genesis block along with several convenience functions such as efficiently comparing two views, quickly finding the fork point (if any) between two
views, and O(1) lookup of the node at a specific height.
The view is not currently used, but the intent is that the code will be refactored to make use of these views to simplify and optimize several areas such as best chain selection and reorg logic and finding successor nodes.  They will also greatly simplify the process of disconnecting the download logic from the connection …
> blockchain: Implement new chain view.

- blockchain/chainview.go
- blockchain/chainview_test.go
This modifies the function to set the tip in the new chainview code to bulk copy existing nodes when it needs to expand the cap rather than simply creating a new empty slice and allowing the walk code below it to repopulate it.  This is a nice optimization since, in practice, most of the time expanding the cap is only required when the active chain is being extended after having run for a while which means the end result is that it will be able to bulk copy all the nodes and just add the most recent one versus having to walk them all and add them back.
Also, while here expand the tests for setting the tip to ensure the nodes contained in the resulting view are correct after forcing the resizes and correct a bug they exposed where changing between a longer-shorter-longer chain where the …
> blockchain: Improve and correct chainview set tip.

- blockchain/chain_test.go
- blockchain/internal_test.go
**NOTE: The linter error is resolved by #1018.  It can be ignored.**
This introduces the concept of a synthetic block chain that can be used in the tests to avoid needing setup a full blown chain instance with a database and generate valid blocks and converts the sequence lock tests in `TestCalcSequenceLock` to use it.
Not only does this speed up the test execution time, but it allows the dependency on `rpctest` to be removed which will allow the sequence locks tests to be consolidated into the main package without creating a circular dependency.
> blockchain: Convert seq lock tests to synthetic.

- blockchain/blocklocator.go
This significantly optimizes and simplifies the generation of block locators by making use of the fact that all block nodes are now in memory and therefore it is no longer necessary to consult the database
for the hashes or worry about issues related to dynamic loading of nodes.
Also, it slightly modifies the algorithm so that the doubling doesn't start for one additional iteration in order to mirror other prominent clients on the network.  Due to the way block locators are used, this
does not change any semantics in terms of requesting and locating blocks.
Finally, the semantics of `BlockLocatorFromHash` have been changed to return a locator for the current tip in the case the hash is unknown. This is far preferable since only including the passed block hash, when
it isn't known, could …
> blockchain: Optimize block locator generation.

- blockchain/chainview.go
- blockchain/chainview_test.go
**This PR depends on #1012**.
This exposes the ability to more efficiently create a block locator from a chain view for a given block node by using their ability to do O(1) lookups.
It also adds tests to ensure the behavior is correct.
> blockchain: Faster chain view block locator.

- blockchain/chain.go
- blockchain/validate.go
This removes the `DisableVerify` function and related state since nothing uses it anymore since the command line option was removed.  It is a remnant of initial development.
> blockchain: Remove unused verify disable code.

- blockmanager.go
- rpcadaptors.go
- rpcserver.go
- server.go
The purpose is to remove the dependency of blockmanager on serverPeer, which is defined in the main package. Instead, we split out some of the fields from serverPeer into a separate struct called peerSyncState in blockmanager.go. While they are in the same package now, this change makes it easier to move blockManager into its own package along with peerSyncState. The blockManager tracks a map of Peer pointers to the peer state and keeps it updated as peers connect and disconnect.
This further decouples blockManager from server on the path to https://github.com/btcsuite/btcd/issues/978.
> blockmanager: Remove serverPeer references.

- blockchain/chain.go
- blockchain/chain_test.go
- rpcadapters.go
- rpcserver.go
- server.go
**This relies on several outstand PRs.  #1017, #1018, #1012, #1013, #1014**.
This refactors the code that locates blocks (inventory discovery) out of server and into `blockchain` where it can make use of the new much more efficient chain view and more easily be tested.  As an aside, it really belongs in `blockchain` anyways since it's purely dealing with the block index and best chain.
Since the majority of the network has moved to header-based semantics, this also provides an additional optimization to allow headers to be located directly versus needing to first discover the hashes and then fetch the headers.
The new functions are named `LocateBlocks` and `LocateHeaders`.  The former returns a slice of located hashes and the latter returns a slice of located headers.
Finally, it also …
> blockchain: Refactor inv discovery for chain view.

- server.go
The btcd logs contain a typo "segwit segwit enabled". This fixes it.
> rm extra word segwit, s/segwit segwit/segwit

- .travis.yml
- README.md
- server.go
Also, make the `gosimple` linter happy while here, and update `README.md` to call out the Go 1.8 minimum version requirement.
> travis: Update to go 1.8 and 1.9.

- btcjson/chainsvrresults.go
- rpcserver.go
The modifies the encoding of witness stacks in JSON responses to use a slice of strings instead of a single space-separated string for compatibility with Core.
Fixes #1036
> btcjson/rpcserver: Encode witness stack as slice.

- blockchain/accept.go
- blockchain/blockindex.go
- blockchain/chain.go
This has the same effect but makes it clearer that all blocks written to the database end up in the block index.
> blockchain: Add node to block index in maybeAcceptBlock.

- blockchain/chain.go
This removes the `minMemoryNodes` field from the `BlockChain` struct since it is no longer used anywhere.
> blockchain: Remove unused min memory nodes field.

- config.go
- doc.go
- sample-btcd.conf
- server.go
--whitelist specifies IP networks and IPs of remote peers that will not
be banned for misbehaving.
> config: Add --whitelist support.

- blockchain/chain.go
- blockchain/indexers/addrindex.go
- blockchain/indexers/common.go
- blockchain/indexers/manager.go
- blockchain/indexers/txindex.go
- btcd.go
- server.go
This propagates the interrupt channel through to `blockchain` and the indexers so that it is possible to interrupt long-running operations such as catching up indexes.
> blockchain/indexers: Allow interrupts.

- btcjson/walletsvrcmds.go
- btcjson/walletsvrcmds_test.go
These commits implement objects and functions to build addwitnessaddress JSON-RPC commands within the btcjson package.  I have added a test to prove out the marshalling of the object.
> btcjson: Implement addwitnessaddress functionality.

- blockchain/accept.go
- blockchain/chain.go
- blockchain/error.go
- blockchain/error_test.go
- blockchain/process.go
- blockchain/validate.go
- blockchain/validate_test.go
- mining/mining.go
- rpcserver.go
This is only used to test block proposals. That has been changed to instead use a new(ish) CheckConnectBlockTemplate function in the blockchain package. The flag complicated the implementation of some chain processing routines and would be difficult to implement with headers-first syncing. Block proposals now may only connect to the tip of the main chain, which is the behavior implemented in Bitcoin Core, bcoin, and possibly other implementations of getblocktemplate.
> blockchain: Remove BFDryRun behaviour flag.

- integration/rpctest/btcd.go
- integration/rpctest/node.go
- integration/rpctest/rpc_harness.go
Previously, rpctest would start a btcd node using the btcd executable in the environment PATH. This caused difficult-to-find issues where the code would be tested against an older version of btcd, or another fork entirely. Now it compiles btcd the first time it is needed and uses that fresh version when launching nodes.
Testing by running in the btcsuite/btcd project as well as in lnd, where roasbeef/btcd is installed as a vendored package.
> rpctest: Compile current version of btcd and run that.

- blockchain/accept.go
- blockchain/blockindex.go
- blockchain/chain.go
- blockchain/chainio.go
- blockchain/error.go
- blockchain/error_test.go
- blockchain/validate.go
- rpcserver.go
Each node in the block index records some flags about its validation state. This is just stored in memory for now, but can save effort if attempting to reconnect a block that failed validation or was
disconnected. In a subsequent change, we will store this in the block index bucket created by https://github.com/btcsuite/btcd/pull/1049.
This field provides little value now, is required for headers-first syncing.
> blockchain: Track block validation status in block index.

- rpcserver.go
"mine a block" instead of "main a block"
> rpcserver: Fix typo in generate handler.

- txscript/script.go
- txscript/sign.go
This is a useful function for users of this library, and deserves to
be public.
> txscript: export calcSignatureHash

- sample-btcd.conf
`addrindex` was present twice.
> Remove duplicate setting in sample config file

- blockchain/chainio.go
This fixes a bug introduced by #1066 where newly initialized database are missing the genesis block. Databases migrated from a btcd version before that change are fine.
@davecgh
> blockchain: Initialize database with genesis block.

- docs/README.md
btcjson and btcrpcclient sub-packages already merged into btcd repo.
> Fix sub packages links

- rpcclient/infrastructure.go
Go 1.10 made some changes such that `json.Unmarshal` can no longer unmarshal into exported fields that are themselves embedded via an uninitialized unexported pointer.
Since `rpcclient` previously relied on this behavior, this updates the client to create the pointers before unmarshalling into the struct.
> rpcclient: Update for go1.10 breaking changes.

- chaincfg/params.go
Initially was observed in `lnd` project for this issue https://github.com/lightningnetwork/lnd/issues/882
if to try to generate invoice for `regtest` net, we get encoded invoice with wrong prefix in human readable part
> Wrong BOLT11 prefix in regtest

- glide.lock
In this commit, we update the glide.lock file to be pinned against the
latest btcutil commit hash. btcutil has recently been updated to pull in
all changes from roasbeef's fork. Notably, it now includes the code
necessary for creating GCS filters (BIP 158).
> build: update glide to point to latest btcutil

- btcec/pubkey.go
- btcec/signature_test.go
Fixes issue discussed in #709 and adds the test cases used in https://github.com/fjl/btcec-issue to btcec's unit coverage.
> btcec: verify square root during point decompression

- blockchain/chain.go
- blockchain/chainio.go
- blockchain/chainio_test.go
- blockchain/indexers/addrindex.go
- blockchain/indexers/cfindex.go
- blockchain/indexers/common.go
- blockchain/indexers/manager.go
- blockchain/indexers/txindex.go
- blockchain/utxoviewpoint.go
- blockchain/validate.go
- btcjson/chainsvrcmds_test.go
- btcjson/cmdparse_test.go
- btcjson/help_test.go
In this PR, we modify the set of indexers to use the stxo set for a block as a performance optimization. Before this commit, when indexing a block the IndexManager had to re-create the entire utxo view for the new block being connected. In practice, this was very slow due to all the random reads required to construct the UTXO set. We optimize this away by first observing that atm, we only really need the prev output scripts for each input being spent. As a result, we can get away with only passing in the stxo set.
In order to implement the above changes, we've now exported the spentTxOut struct, and also a method to fetch the stxo for a particular block.
> blockchain: modify indexers to use the stxo set for a block rather than the utxo set

- peer/peer.go
In this commit, we patch a goroutine leak within the peer struct. This
goroutine leak can happen, if the remote side fails to actually finish
negotiation the protocol before our timeout ticker ticks. In this case,
the goroutine will be blocked on a send, as the channel is unfired. An
example trace from a btcd node I had on testnet showed:
```
3183 @ 0x42e78a 0x42e83e 0x40540b 0x4051a5 0x872f76 0x45bfc1
```
So, all instances of the goroutine failing to exit due to the remote
peer not finishing the p2p version negotiation handshake.
Our fix is simple: make the `negotiateErr' channel unbuffered. With this
simple change, we ensure that the goroutine will always exit even in the
case that the parent goroutine exists due to a timeout.  # Please enter
the commit message for your changes. Lines …
> peer: ensure the version negotiation goroutine will always exit

- server.go
backport of https://github.com/decred/dcrd/pull/1295
> server: always reply with get headers

- blockchain/chain.go
- rpcserver.go
backport of https://github.com/decred/dcrd/pull/1273
Notable difference being that btcd mainline currenlty
doesn't have a blockchain/blockindex_test file, so
those changes are ommitted.
Great work @davecgh :)
> blockchain: Backport optimize exported header access.

- config.go
- peer/example_test.go
- peer/peer.go
- peer/peer_test.go
- server.go
Useful for speeding up tests etc.
> config/peer: make trickleTimeout configurable

- integration/csv_fork_test.go
- integration/rpctest/memwallet.go
- integration/rpctest/node.go
- integration/rpctest/rpc_harness.go
- integration/rpctest/rpc_harness_test.go
In this commit, we disable the txindex by default as the flag cannot be
overwritten by btcd once set.
> integration/rpctest: disable the txindex by default and allow sending txs without change outputs

- peer/peer.go
Backported from decred/dcrd#1247.
This rearranges some of the function definitions that pertain to initial peer version negotiation and bringup so they are more consistent with the preferred order used throughout the codebase.  In particular, the functions are defined before they're first used and generally as close as possible to the first use when they're defined in the same file.
There are no functional changes.
> peer: Minor function definition order cleanup.

- btcjson/chainsvrresults.go
- rpcserver.go
This PR modifies the parsed fields in GetBlockVerbose
and GetBlockHeaderVerbose from a uint64 to an int64.
bitcoind will return -1 if the requested block is not in
the main chain, which causes a panic when trying to
serialize into a uint.
> btcjson: use int64 for GetBlockHeader[Verbose] confirmations

- blockchain/indexers/manager.go
In this commit, we fix an existing bug in the re-org catch up logic for
the `IndexManager`. Before this commit, we would assign the block to the
_local_ scope rather than the outer scope. As a result, we would never
properly bisect the chain to find the fork point to be able to reconcile
the index state to the main chain only after a re-org occurs.
Fixes #1261
> blockchain/indexers: fix bug in indexer re-org catch up

- glide.lock
- glide.yaml
In this commit, we update the siphash lib we use to the latest version
as it was discovered that the assembly for certain ARM machines has a
flaw which causes it to compute an _incorrect_ siphash function. The
upstream lib has since disabled the assembly after this was discovered.
We update as well in order to ensure that ARM machines will produce the
proper GCS filters.
> build: update siphash lib to latest version w/ ARM fix

- server.go
In this commit, we modify the locking scheme when serving cf checkpoints
for peers to allow the server to serve multiple peers at the same time.
Before this commit, we would first grab the write lock, check to see for
expansion, then release the read lock. In this commit we reverse this
and instead will grab the read lock, and upgrade to the write lock if we
need to actually expand the size of the cache.
We also fix a panic bug that can arise when we attempt to
process a cf checkpoint message from a remote peer. Before this commit,
if the size of the checkpoint cache was large than the number of
checkpoints requested by the peer, we would panic with an out of bounds
error. In order to prevent, this we'll now use the size of the requested
set of hashes as our bound to ensure that we don't …
> server: allow for read concurrency when serving cf checkpoints, fix bug in checkpoint serving

- server.go
the comment for struct `simpleAddr` is mismatched. 
Maybe simple copy.
> server: Fix struct name mismatch

- addrmgr/addrmanager.go
- peer/example_test.go
- peer/peer.go
- peer/peer_test.go
- server.go
**This requires #1255**.
Backported from decred/dcrd#1258.
This modifies the `OnVersion` handler for server peers to use a local variable for the remote address of the peer in order to avoid grabbing the mutex multiple times.
There are no functional changes.
> server: Use local addr var in version handler.

- peer/peer.go
- peer/peer_test.go
**This relies on #1247**
Backported from decred/dcrd#1248.
This adds a test to ensure duplicate version messages are rejected.
> peer: Add duplicate version message test.

- peer/peer.go
- peer/peer_test.go
- server.go
**This requires PR #1248**.
Backported from decred/dcrd#1250.
This modifies the negotiation logic to ensure the callback has the opportunity to see the message before the peer is disconnected and improves the error handling when reading the remote version message.
It also has the side effect of ensuring the protocol version is negotiated before sending reject messages with the exception of the first message not being a version message since negotiation is not possible in that case.
This is being changed because it is useful for the server to see the message regardless in order to have the opportunity to things such as update the address manager and reject peers that don't have desired services.
> peer: Rework version negotiation.

- peer/example_test.go
- peer/peer.go
- peer/peer_test.go
- server.go
**This requires PR #1249**.
Backported from decred/dcrd#1251.
This modifies the `OnVersion` callback to allow a reject message to be returned in which case the message will be sent to the peer and the peer will be disconnected.
> peer: Allow OnVersion callback to reject peer.

- peer/example_test.go
- peer/peer.go
- peer/peer_test.go
- server.go
**This requires PR #1250**.
Backported from decred/dcrd#1252.
This modifies the server connection code to reject outbound peers that do not offer full node services.
> server: Reject outbound conns to non-full nodes.

- peer/example_test.go
- peer/peer.go
- peer/peer_test.go
- server.go
**This PR requires #1251**.
Backported from decred/dcrd#1253.
This modifies the peer code which deals with advertising service flags via the net address fields of the version message as follows:
- For outgoing connections:
- Set the local netaddress services to what the local peer supports
- Set the remote netaddress services to 0 to indicate no services as they are still unknown
- For incoming connections:
- Set the local netaddress services to what the local peer supports
- Set the remote netaddress services to the what was advertised by the remote peer in its version message
> peer: Improve net address service adverts.

- addrmgr/addrmanager.go
- peer/example_test.go
- peer/peer.go
- peer/peer_test.go
- server.go
**This is rebased on #1252**.
Backported from decred/dcrd#1254.
This consists of two commits.
The first commit exposes a new method named `SetServices` to the address manager which can be used to update the services for a known address.
The second updates server to add code which updates the address manager services for a known     address to the services advertised by peers when they are connected to via an outbound connection.  It is only done for outbound connections to help prevent malicious behavior from inbound connections.
> multi: Update addrmgr services on outbound conns.

- addrmgr/addrmanager.go
- peer/example_test.go
- peer/peer.go
- peer/peer_test.go
- server.go
**This requires PR #1253**.
Backported from decred/dcrd#1255.
This modifies the `OnVersion` handler for server peers to use a local variable for the inbound status of the peer in order to avoid grabbing the mutex multiple times.
While here, it also does some light cleanup.  There are no functional changes.
> server: Use local inbound var in version handler.

- addrmgr/addrmanager.go
- peer/example_test.go
- peer/peer.go
- peer/peer_test.go
- server.go
**This requires PR #1254**.
Backported from decred/dcrd#1256.
This changes the server peers `OnVersion` handler to only advertise the server as a viable target for inbound connections when the server believes it is close the best known tip.
> server: Only advertise local addr when current.

- btcjson/btcwalletextcmds.go
- btcjson/btcwalletextcmds_test.go
- rpcclient/wallet.go
> fix NewImportAddressCmd rescan wrong parameters

- btcec/signature.go
Ultra rare edge case where r == N.
1. L430 returns 0 so is NOT == 1 and if statement NOT entered.
2. L434 r.Sign() returns 1 (since N > 0) so if statement is NOT entered.
3. mod N function for s calculation is not performed until after an addition operation (if it were only Multiplication we would still arrive at 0 when mod N is performed, since a*N mod N is always 0. But there is an addition between that)
4. The Signature object is returned with R == curve.N...
Obviously I can't find a test case where nonceRFC6979 returns a k what when scalar Multiplied gets an x value == N... but N with both 0x02 and 0x03 DER headers is a valid point on the curve...
So the chance is not 0.
> Fix one-off bug in signRFC6979

- integration/rpctest/btcd.go
With the use of go modules, the btcdPkgPath will no longer be `github.com/btcsuite/btcd`, but end with a version string (e.g. btcd@v0.0.0-20181129140220-beb77e89572a).
This trips up build.ImportDir, which will return a ImportPath of ".", since this package cannot be found in the go path.
There are probably several ways of fixing this, by clever string magic, but seems easiest to just hardcode the btcd package name.
Relevant issue: https://github.com/golang/go/issues/26504
> integration/rpctest: make exec path compatible with modules

- addrmgr/addrmanager.go
- addrmgr/addrmanager_internal_test.go
- addrmgr/addrmanager_test.go
- addrmgr/knownaddress.go
In this commit, we update the serialized version of the AddressManager
to also store each address' service bits. This allows an address'
service bits to be properly set when read from disk, which allows
external callers to reliably filter out addresses which do not support
their required services.
> addrmgr: store address' supported service bits

- connmgr/connmanager.go
This PR fixes the case where a connection is cancelled at the time it is waiting for retry.
Before the fix the code would still attempt to connect and only after connecting successfully it will check for prior cancelation and ignore the connection.
After this fix the cancelation would be detected earlier and save the attempt to connect.
> check for cancelled connection before retry

- btcd.go
- config.go
- server.go
This PR adds a hybrid black/whitelist in order to filter for suitable user agents. Btcd's initial block download can stall intermittently due to targeting a bcash node as the primary sync peer, and not detecting that the sync has been blocked. This provides a temporary solution in order to get a btcd node fully synced, after which it is less imperative to continue filtering by user agents.
The black and whitelists can be modified in the configuration file using the tags agentblacklist and agentwhitelist. The blacklist is applied before the whitelist, using the following procedure:
1. Reject the peer if it contains a blacklisted agent substring.
1. If no whitelist is provided, accept all other peers.
1. Accept the peer if it contains a whitelisted agent substring.
1. Otherwise, reject all …
> Configurable UserAgent filtering

- netsync/manager.go
Adds stall detection when no blocks have been received from the sync
peer for at least 3 minutes.
The change backports parts of gcash/bchd#105,
though has different behavior, such as:
- Rotating the sync peer at tip.
- Only disconnecting the sync peer if they're height exceeds our own.
Since we will instead rotate the sync peer at tip, this prevents us
from disconnecting good peers while waiting for new blocks.
- Not resetting the progress time when blocks are submitted via rpc.
Closes #697. 
Closes #776. 
Closes #1024. 
Closes #1099. 
Closes #1136. 
Closes #1405. 
Closes #186. 
Closes #614.
> netsync/manager: detect stalled sync peer

- btcjson/jsonrpcerr.go
- rpcserver.go
`bitcoind`'s behavior can be referenced [here](https://github.com/bitcoin/bitcoin/blob/master/src/node/transaction.cpp#L34).
> btcjson+rpc: match bitcoind's RPC error codes for rejected transactions

- rpcwebsocket.go
In this commit, we implement an optimization that will speed up clients
that attempt to perform a rescan in the past with no addresses. If the
client doesn't have any thing to search for, then we simply exit early
and send them a rescan finished notification with the final block in our
chain.
>  rpc: skip rescan if client has no addresses or UTXOs

- rpcwebsocket.go
In this commit, we fix a bug in the rescan logic after a recent
refactoring that would cause the scanning node to potentially panic. If
the client disconnected, before the rescan was finished, then we would
return a nil `lastBlock` and `lastBlockHash`. We would then attempt to
send the rescan finished notification, causing a panic.
We remedy this by simply detecting this case (client disconnect), and
existing once again as the prior code would, pre-refactoring.
> rpc: fix rescan bug if client disconnects

- peer/peer.go
- wire/message.go
It was possible for connections to bitcoind nodes to be closed from their side if the OnVersion callback queued a message to send. This is because bitcoind expects a verack message before attempting to process any other messages. To address this, we ensure the verack is sent as part of the handshake process, such that any queued messages happen after the fact.
> peer: include verack as part of version handshake

- btcec/signature.go
> // recoverKeyFromSignature recovers a public key from the signature "sig" on the
> // given message hash "msg". Based on the algorithm found in section 5.1.5 of
> // SEC 1 Ver 2.0, page 47-48 (53 and 54 in the pdf). This performs the details
> // in the inner loop in Step 1. The counter provided is actually the j parameter
> // of the loop * 2 - on the first iteration of j we do the R case, else the -R
> // case in step 1.6. This counter is used in the bitcoin compressed signature
> // format and thus we match bitcoind's behaviour here.
Actually it's section `4.1.6 Public Key Recovery Operation` of `SEC 1 Ver 2.0`. There is no section 5.1.5.
> Correct the comment of recoverKeyFromSignature

- btcec/bench_test.go
- btcec/btcec.go
- btcec/field.go
- btcec/field_test.go
- btcec/pubkey.go
As of #1193, decompressPoint now
validates that the point is on the curve. The x and y coordinates are
also implicitly <= `P`, since the modular reduction is applied to both
before the method returns. The checks are moved so that they are still
applied when parsing an uncompressed pubkey, as the checks are not
redundant in that path.
We also optimize the decompressPoint subroutine, used in extracting
compressed pubkeys and performing pubkey recovery. We do so by replacing
the use of big.Int.Exp with with square-and-multiply exponentiation of
btcec's more optimized fieldVals, reducing the overall latency and
memory requirements of decompressPoint.
Instead of operating on bits of Q = (P+1)/4, the exponentiation applies
the square-and-multiply operations on full bytes of Q.  Compared to the …
> btcec: optimize square root using fieldVal

- btcec/pubkey.go
This commit fixes an issue introduced in the recent #1429, where
the output of SqrtVal is not normalized before using IsOdd() to compare
with the expected parity of the y-coordinate. The IsOdd() is only
guaranteed to work if the value has been denormalized, so a denormalized
sqrt >= p would report the opposite parity. We fix this by normalizing
both after compute sqrt(x^3+b) and when negating the root as directed by
the ybit.
> btcec/pubkey: normalize sqrt(x^3) before checking parity

- server.go
In this PR, we include a series of connection management fixes that were discovered in https://github.com/lightninglabs/neutrino/pull/178. Since most of the code there was inspired by `btcd`, the fixes also happen to apply here as well. Each fix has been included in its own commit along with a descriptive message of the issue it's addressing. Mainly, this PR attempts to ensure we can more aggressively connect to peers through the underlying connection manager.
> server: miscellaneous connection management fixes

- server.go
This change is needed as part of requiring peers to also send a verack message following their version message during protocol negotiation. Peers were previously added to the SyncManager before their message queues were started, causing the server to stall if a peer didn't provide a timely verack response following their version. We now do this within OnVerAck, which happens shortly before peer message queues are started.
Fixes https://github.com/btcsuite/btcd/issues/1471.
>  server: refactor OnVersion to instead add peers within OnVerAck

- btcjson/chainsvrcmds.go
- btcjson/chainsvrresults.go
- integration/bip0009_test.go
- rpcclient/chain.go
- rpcclient/chain_test.go
- rpcclient/infrastructure.go
- rpcclient/net.go
- rpcclient/rawtransactions.go
- rpcserver.go
- rpcserverhelp.go
This PR aims to remedy the breaking RPC changes introduced in `bitcoind v0.19.0`:
* https://github.com/bitcoin/bitcoin/pull/13541
* https://github.com/bitcoin/bitcoin/pull/16060
This required being able to interpret the backend version the client connects to, which wasn't previously supported. `btcd` and `bitcoind` have different methods to expose this, `GetInfo` and `GetNetworkInfo` respectively.
> btcjson+rpcclient: add compatibility for bitcoind v0.19.0

- server.go
Running with the race detector gave this.
Two goroutines were accessing the `knownAddresses` map on a `serverPeer` object:
```
==================
WARNING: DATA RACE
Read at 0x00c01cf18450 by goroutine 37:
runtime.mapaccess2_faststr()
/usr/local/Cellar/go/1.13/libexec/src/runtime/map_faststr.go:107 +0x0
main.(*serverPeer).pushAddrMsg()
/Users/nsa/go/src/github.com/btcsuite/btcd/server.go:315 +0x14b
main.(*server).handleAddPeerMsg()
/Users/nsa/go/src/github.com/btcsuite/btcd/server.go:1651 +0xce4
main.(*server).peerHandler()
/Users/nsa/go/src/github.com/btcsuite/btcd/server.go:2116 +0xbff
Previous write at 0x00c01cf18450 by goroutine 53:
runtime.mapassign_faststr()
/usr/local/Cellar/go/1.13/libexec/src/runtime/map_faststr.go:202 +0x0
main.(*serverPeer).addKnownAddresses() …
```
> server: add addressesMtx to fix race condition

- server.go
Peers are now added to the SyncManager if we receive their verack, but we'd still attempt to remove them from the SyncManager if we didn't receive it.
> server: remove peer from SyncManager on VerAckReceived

- .travis.yml
$GOPATH caching has led to flaky tests as per #1503 and #1536. The speedup is marginal and while the false negatives are a headache, false positives are potentially dangerous.
> Remove $GOPATH Caching

- mempool/estimatefee.go
Running `go fmt ./...` changes `E` to `e`. Since this has come up on #1505 and is happening as I put together a PR for #1522/#1524 and I've seen this happen to a few other people I figure we might as well get it merged in a separate pr [as per](https://github.com/btcsuite/btcd/pull/1503#discussion_r354182377) @torkelrogstad
> Formatting Fixes (go fmt)

- release/README.md
There was simply a missing "\`" in the first step of the build process.
> release: add missing back tick in build docs

- docs/json_rpc_api.md
switch btcrpcclient to rpcclient because btcrpcclient is now a sub-package of the btcd repository.
> docs/json_rpc_api: update go examples 

- connmgr/dynamicbanscore.go
- connmgr/dynamicbanscore_test.go
https://github.com/btcsuite/btcd/issues/1510
> BUG:dynamicbanscore deadlock

- btcjson/jsonrpcerr.go
This adds an error code for the `RPC_IN_WARMUP` error code defined at https://github.com/bitcoin/bitcoin/blob/master/src/rpc/protocol.h#L49 which is thrown when bitcoind has started but has not yet finished verifying recent blocks and being ready for rpc calls.
> btcjson: add RPC_IN_WARMUP error code

- btcjson/chainsvrcmds.go
- btcjson/chainsvrcmds_test.go
- btcjson/chainsvrresults.go
- btcjson/cmdinfo_test.go
- btcjson/example_test.go
- rpcclient/chain.go
- rpcserver.go
- rpcserverhelp.go
Currently, rpcclient.GetBlockVerboseTx(...) does not return raw transaction data. This is due to how GetBlockCmd is implemented in btcjson; in upstream/master, `getblock` sends two boolean parameters (`verbose` and `verbosetx`), which throws an error. 
According to the bitcoin JSON RPC documentation, `getblock` accepts two parameters: `blockhash` (as a string) and `verbosity` (as an integer). `verbosity` can be any of `0`, `1`, or `2`, with `0` being the default. 
```
getblock "blockhash" ( verbosity ) 
If verbosity is 0, returns a string that is serialized, hex-encoded data for block 'hash'.
If verbosity is 1, returns an Object with information about block .
If verbosity is 2, returns an Object with information about block  and information about each transaction. 
Arguments:
1. …
```
> Refactor GetBlockVerboseTx to reflect correct getblock RPC call parameters.

- btcjson/chainsvrwscmds.go
- btcjson/chainsvrwsntfns.go
- rpcclient/notify.go
This makes godoc and other Go tools understand deprecation notice.
Found using https://go-critic.github.io/overview#deprecatedComment-ref
> btcjson,rpcclient: use proper Deprecated comment format

- .travis.yml
- btcjson/btcdextcmds_test.go
- btcjson/btcwalletextcmds_test.go
- btcjson/chainsvrcmds_test.go
- btcjson/chainsvrwscmds_test.go
- btcjson/chainsvrwsntfns_test.go
- btcjson/cmdparse.go
- btcjson/cmdparse_test.go
- btcjson/example_test.go
- btcjson/jsonrpc.go
- btcjson/jsonrpc_test.go
- btcjson/walletsvrcmds_test.go
- btcjson/walletsvrwscmds_test.go
- btcjson/walletsvrwsntfns_test.go
- cmd/btcctl/btcctl.go
- config.go
- goclean.sh
- mempool/estimatefee.go
- rpcclient/chain.go
- rpcclient/examples/bitcoincorehttp/main.go
- rpcclient/examples/bitcoincorehttpbulk/README.md
- rpcclient/examples/bitcoincorehttpbulk/main.go
- rpcclient/infrastructure.go
- rpcserver.go
- rpcwebsocket.go
This pr aims to address #329 which has been open for a while now by adding bulk request support. This is base on from [decred#841](https://github.com/decred/dcrd/pull/841) by @davecgh
> Add Batch JSON-RPC support (rpc client & server)

- btcjson/chainsvrresults.go
As per #1522, several fields of the [`getmempoolentry`](https://bitcoincore.org/en/doc/0.19.0/rpc/blockchain/getmempoolentry/) were missing when the method was implemented #905 (since it was created using [0.14.0](https://github.com/bitcoin/bitcoin/tree/v0.14.0) as the reference implementation and weren't updated with #1484. [As per](https://github.com/btcsuite/btcd/pull/905#pullrequestreview-19612400) @davecgh on #905, `getmempoolentry` was implemented on the client, but not the server. I think with the upgrades/implementation suggested in #1522, it makes the most sense to follow the path we did there and get this merged while we put together a comprehensive up to date `getmempoolentry` server implementation based off this branch
> update GetMempoolEntryResult to v0.19.0

- btcjson/btcdextcmds.go
- btcjson/btcdextcmds_test.go
- btcjson/chainsvrresults.go
- btcjson/walletsvrcmds.go
- btcjson/walletsvrcmds_test.go
- rpcclient/chain.go
- rpcclient/mining.go
Once this PR is merged I'll open up another PR for implementing the `fundrawtransaction` RPC call. It is implemented at https://github.com/ArcaneCryptoAS/btcd/pull/2, but it needs `EstimateSmartFeeMode` from this PR for a clean backport.
> Add generatetoaddress and estimatesmartfee RPC calls

- btcjson/chainsvrcmds.go
- btcjson/chainsvrcmds_test.go
- btcjson/chainsvrresults.go
- rpcclient/chain.go
I had to implement `HashOrHeight` type because `getblockstats` RPC command takes either block height or hash and `interface{}` is not allowed in command arguments. The new type basically wraps an `interface{}` and defines JSON marshaling and unmarshaling rules.
> Implement 'getblockstats' JSON-RPC command

- cmd/btcctl/config.go
Found using https://go-critic.github.io/overview#regexpMust-ref
> cmd/btcctl: use regexp.MustCompile for constant patterns

- rpcclient/rawtransactions.go
Currently, it is not possible to use the `rpcclient` package to create a raw TX with Bitcoin Core if the transaction you're creating has no inputs. This is a realistic scenario, as you would typically call `createrawtransaction` with your outputs specified, and then follow up with `fundrawtransaction`. 
The reason the RPC call fails is that we assume the returned transaction is encoded with the new witness format that was introduced with Segwit. We solve this by simply trying both serialization formats. If its possible to detect which format is used (so we avoid doing it twice) I'll update the PR.
> Try both TX serialization formats in createrawtransaction

- cmd/addblock/config.go
- cmd/btcctl/config.go
- cmd/findcheckpoint/config.go
- cmd/gencerts/gencerts.go
- config.go
- database/cmd/dbtool/globalconfig.go
- doc.go
Current --help output is a quite confusing. This change alphabetizes the output. Also update `doc.go`, alphabetizing and adding the following entries which are currently missing:
```
--addrindex
--blockmaxweight
--blockminweight
--dropaddrindex
--dropcfindex
--droptxindex
--rpcmaxconcurrentreqs
--trickleinterval
--txindex
```
> Alphabetize --help output; add missing options to doc.go

- mempool/mempool.go
I started playing with btcd+lnd on simnet and was confronted with error message:
```
[ERR] FNDG: Unable to broadcast funding tx for ChannelPoint(<point>:0):
-22: TX rejected: transaction <tx> has witness data, but segwit isn't active yet
```
I wasn't aware of the activation period so I got quite puzzled.
Google helped. But I think the message could mention likely cause.
Newly it optionally prints something like:
```
(The threshold for segwit activation is 300 blocks on simnet, current best height is 113)
```
> Improve error message about non-active segwit on simnet

- cmd/btcctl/config.go
This adds regtest support to btcctl and fixes #1456. btcctl will respond with "cannot use -wallet with -regtest, btcwallet not yet compatible with regtest" because regtest is not yet supported in btcwallet.
> btcctl: add regtest mode to btcctl

- rpcclient/chain.go
Without this, users of this library wouldn't be able to issue GetBlock requests to nodes which haven't updated to support the latest request format, namely the use of a single `int` parameter to denote verbosity instead of two `bool`s.
I've confirmed through manual testing that these changes, along with https://github.com/btcsuite/btcd/pull/1560/, provide full compatibility for bitcoind and btcd and provide backwards compatibility for btcd.
> rpcclient: send legacy GetBlock request for backwards compatibility

- rpcclient/cookiefile.go
- rpcclient/infrastructure.go
Fixes https://github.com/btcsuite/btcd/issues/1054
> rpcclient: Add cookie auth

- btcjson/chainsvrcmds.go
- btcjson/chainsvrcmds_test.go
- rpcclient/rawtransactions.go
Prior to this, calling `CreateRawTransaction(nil, ...)` failed. We fix this, and add a test for the serialization.
> rpcclient: serialize nil inputs to empty list

- blockchain/chainio.go
Remove unnecessary slice of all block indexes and
remove DB iteration over all block indexes that
used to determined the size of the slice
> Improve chain state init efficiency

- blockchain/utxoviewpoint.go
In developing utreexo we're using btcd & libraries quite a bit.  The current exported methods for adding entries to a UtxoViewpoint don't work for utreexo though.  
`AddTxOut()` and `AddTxOuts()` both require a whole transaction, including the inputs, which are only there to calculate the txid.  In the utreexo setup, we only have the outpoint and txout data, but not the rest of the transaction we'd like to add into the UtxoViewpoint.  Directly creating one with `NewUtxoEntry()` seems like the smallest change that doesn't affect anything else in btcd.
Another way to do it would be exporting the current `addTxOut()` method, but that would conflict with the current exported `AddTxOut()` method.  (which, granted, is only used in 1 place in mempool.go, and that usage could be adapted to give …
> Add blockchain.NewUtxoEntry() 

- btcjson/chainsvrcmds.go
- btcjson/chainsvrcmds_test.go
- btcjson/chainsvrresults.go
- rpcclient/chain.go
> rpcclient: Add getchaintxstats JSON-RPC client command

- btcjson/chainsvrcmds.go
- btcjson/chainsvrcmds_test.go
- btcjson/chainsvrresults.go
- rpcclient/rawtransactions.go
> Add fundrawtransaction RPC call

- rpcclient/wallet.go
Adding `GetTransactionWatchOnlyAsync` and `GetTransactionWatchOnly` methods, to support passing the `include_watchonly` argument to [**`gettransaction`**](https://bitcoincore.org/en/doc/0.20.0/rpc/wallet/gettransaction).
The method signature is following `ListTransactionsCountFromWatchOnly` (soon to be merged), as discussed in #1589.
> rpcclient: Add GetTransactionWatchOnly method

- btcec/field.go
- btcec/field_test.go
The implementation has been adapted from the dcrec module in dcrd. The bug was initially fixed in decred/dcrd@3d9cda1 while transitioning to a constant time algorithm. A large set of test vectors were subsequently added in decred/dcrd@8c6b52d.
The function signature has been preserved for backwards compatibility. This means that returning whether the value has overflowed, and the corresponding test vectors have not been backported.
This fixes #1170 and closes a previous attempt to fix the bug in #1178.
With changes from #1178:
```
benchmark                              iter     time/iter
---------                              ----     ---------
BenchmarkFieldVal_SetByteSlice-8   27170966   40.60 ns/op
```
With this PR:  (~2.8 times faster)
```
benchmark                              iter …
```
> btcec: Avoid panic in fieldVal.SetByteSlice for large inputs

- netsync/manager.go
- server.go
Also, increase ban score on notfound and return whether `addBanScore` disconnects the peer. Backport from https://github.com/decred/dcrd/pull/2253
> server: handle notfound

- config.go
- service_windows.go
To run integration tests with `btcd` on Windows in non-interactive
environments (such as the Travis build with Windows machines), we
need to make sure we can still spawn a child process instead of only a
windows background service.
For this, we add a new command line flag called `--nowinservice` to disable creating and starting a windows service instead of running a child process.
> config+service_windows: add flag to disable win service

- CHANGES
Also updated changes for 0.20.1, and added a small note about changes since 0.12.0.
**The release date for 0.21.0 is set to Aug 10 2020**. I chose this date because it is when we (contributors) will next convene on IRC. Of course, I can update this if the release gets delayed.
I didn't include the version bump to 0.21.0 in this PR, since it should be done by the maintainer who will be doing the release. (@jcvernaleo)
See #1572 for more granular release notes. Please merge this after #1610.
> Update CHANGES file for 0.21.0 release

- blockchain/chain.go
- blockchain/thresholdstate.go
- blockchain/versionbits.go
Received this warning while syncing, and this warning is being called when >50 of the last 100 blocks have unexpected version numbers. Due to AsicBoost this is triggering many false positives.
The warning was removed from Core for 0.18.0 in https://github.com/bitcoin/bitcoin/pull/15471/.
> blockchain: remove unknown block version warning

- btcjson/chainsvrcmds.go
- btcjson/chainsvrcmds_test.go
- btcjson/chainsvrresults.go
- rpcclient/chain.go
- rpcclient/example_test.go
This is a client-only implementation of the `getdescriptorinfo` RPC call.
Added a new file `rpcclient/example_test.go` containing an example that gets embedded by godoc. Let's try to include more of these in future.
> rpcclient: Add getdescriptorinfo RPC call

- peer/peer.go
- peer/peer_test.go
This modifies the UpdateLastBlockHeight function to ensure the new
height is after the existing height before updating it in order to
prevent it from going backwards so it properly matches the intent of the
function which is to report the latest known block height for the peer.
Without this change, the value will properly start out at the latest
known block height reported by the peer during version negotiation,
however, it will be set to lower values when syncing from the peer due
to requesting old blocks and blindly updating the height.
It also adds a test to ensure proper functionality.
This is a backport of https://github.com/decred/dcrd/pull/1747
> peer: prevent last block height going backwards

- rpcserver.go
`amount` is BTC unit. ex. 0.00001234BTC
`MaxSatoshi` is satoshi unit. ex. 1234satoshi
> Fix monetary unit

- btcjson/chainsvrresults.go
- rpcserver.go
- rpcserverhelp.go
Updated the `rpcserver` handler for [**`validateaddress`**](https://bitcoincore.org/en/doc/0.20.0/rpc/util/validateaddress/) JSON-RPC command to have parity with the bitcoind 0.20.0 interface.
The new fields included are - `isscript`, `iswitness`, `witness_version`, and `witness_program`. The `scriptPubKey` field has been left out since it requires wallet access.
This update has no impact on the `rpcclient.ValidateAddress` method, which uses the `btcjson.ValidateAddressWalletResult` type for modelling the response from bitcoind.
Unfortunately, we lack a proper framework to write rpcserver tests, so here's you can test this PR:
```sh
$ go build .
$ ./btcd --testnet --rpcuser=aaaa --rpcpass=bbbb
```
In another tab,
```sh
$ cd cmd/btcctl
$ go build .
```
```sh
$ ./btcctl --testnet …
```
> rpcserver: add parity with bitcoind for validateaddress

- btcjson/chainsvrcmds.go
- btcjson/chainsvrcmds_test.go
- btcjson/chainsvrresults.go
- btcjson/helpers.go
- rpcclient/chain.go
Adds `getblockfilter` call to JSON-RPC client.
> rpcclient: Add getblockfilter JSON-RPC client command

- btcjson/walletsvrcmds.go
- btcjson/walletsvrcmds_test.go
- btcjson/walletsvrresults.go
- rpcclient/example_test.go
- rpcclient/wallet.go
Bitcoin Core [**`importmulti` (0.19.0 RPC)**](https://bitcoincore.org/en/doc/0.19.0/rpc/wallet/importmulti)
This RPC command is particularly complex, due to some parameters allowing values of different types, depending upon the expected outcome. Ones that are of interest are the `timestamp`, `range`, and `scriptPubKey` fields.
To solve the above problem, I drew inspiration from [**`HashOrHeight`**](https://github.com/btcsuite/btcd/blob/d38279ee7446d9ee17cb7242afb5ccb32c3775ec/btcjson/chainsvrcmds.go#L194-L221) in `btcjson` package, which seemed like a reasonably good solution to me.
- I have added the documentation verbatim from Bitcoin Core, with slight changes wherever I felt necessary.
- I played around with the RPC command a bit, communicating to a Bitcoin Core regtest node, and …
> rpcclient: Implement importmulti JSON-RPC client command

- Dockerfile
- docs/README.md
- docs/using_docker.md
Hi team,
i created the following Dockerfile that builds and runs btcd in a small (55MB) Alpine container. The /root/.btcd folder is mounted to a named docker volume by default. Any additional btcd argument can be passed by adding it at the end of the docker command. Very simple.
Please check the comments in the Dockerfile on how to build and run the container. It would be great to see it in the official repository and to have an official container on Docker Hub.
Best regards
/legacycode
> Add Dockerfile to build and run btcd on Docker.

- btcjson/cmdparse_test.go
- upnp.go
- wire/message.go
Without this, `btcd` fails to build in Go 1.15 with the following message:
````
./upnp.go:232:20: conversion from int to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
````
> btcd: fix conversion of int to string failing in Go 1.15

- blockchain/validate.go
txHash is only used for printing error messages and doesn't have to be calculated beforehand. This gets rid of an expensive calculation and removes a lot of gc pressure.
> blockchain: Remove unnecessary tx hash

- btcjson/walletsvrresults.go
This only adds new fields as optional, in order to make it backwards compatible with older versions of Bitcoin Core.
> btcjson: update ListTransactionsResult for Bitcoin 0.20.0

- chaincfg/params.go
- chaincfg/params_test.go
|Issue|https://github.com/btcsuite/btcutil/issues/179|
-|-
This is a first step towards allowing library packages (such as [btcutil](https://github.com/btcsuite/btcutil), but not limited to it) to register [**`SLIP-0132`**](https://github.com/satoshilabs/slips/blob/master/slip-0132.md) (or custom) HD version bytes. The version bytes itself are not included in this PR; it simply provides a public function to populate them.
Currently, the only way to register HD version bytes is by initializing `chaincfg.Params` struct, and registering it during package init. `RegisterHDKeyID` provides a way to populate custom HD version bytes, without having to create new `chaincfg.Params` instances. This is useful for library packages who want to use non-standard version bytes for serializing extended …
> chaincfg: Add RegisterHDKeyID func to populate HD key ID pairs

- btcjson/cmdparse.go
- btcjson/cmdparse_test.go
Fixes command marshalling dropping params that follow params with `nil` value. For instance the command:
```
btcjson.NewGetNetworkHashPSCmd(nil, btcjson.Int(2000))
```
Would previously marshall with empty params: `"params":[]`. Now the second optional parameter is included and padded with a `null` value: `"params":[null,2000]`.
The JSON-RPC server will substitute `null` values with the command's default values where possible.
#1591 Allows providing `null` value from command line (similarly to Core command line utility):
```
btcctl getnetworkhashps null 10000
```
`getchaintxstats` is a good example where the ability to provide `null` parameter is especially critical. Default value of the first optional parameter is only known server-side. The fix in marshalling allows taking full advantage …
> Nullable optional JSON-RPC parameters

- .github/workflows/go.yml
- .gitignore
- README.md
- goclean.sh
This modifies the `goclean.sh` script to run tests with the race detector enabled. It also enables code coverage, and uploads the results to coveralls.io.
Running tests with `-race` and `-cover` flags was disabled in 6487ba1 and 6788df7 respectively, due to some limits on time/goroutines being hit on Travis CI. Since we have migrated to GitHub Actions, and don't have those same limitations, it is desirable to enable them back.
I have also simplified the way we run code coverage in the `goclean.sh` file, by launching it directly with `go test  ...`. I'm using `-covermode atomic` flag, which is the recommended setting for running with the race detector.
Here's the coverage report on my fork: https://coveralls.io/builds/31944135
> GitHub Actions: Enable Go Race detector and code coverage

- netsync/manager.go
- server.go
When handling `MsgNotFound`, it's missing the check on `wire.InvTypeWitnessBlock` and `wire.InvTypeWitnessTx`. This PR fixes it.
> btcd+netsync: support witness tx and block in notfound msg

- btcjson/chainsvrcmds.go
- btcjson/chainsvrcmds_test.go
- btcjson/chainsvrresults.go
- rpcadapters.go
- rpcclient/net.go
- rpcserver.go
- rpcserverhelp.go
Add NodeAddresses function to rpcserverConnManager
interface for fetching known node addresses.
> Add getnodeaddresses JSON-RPC support (rpc client & server)

- btcjson/walletsvrcmds_test.go
- rpcclient/wallet.go
Added method for request ListSinceBlock with include_watchonly=true
> Added ListSinceBlockMinConfWatchOnly method.

- btcjson/chainsvrcmds.go
- btcjson/chainsvrcmds_test.go
- btcjson/chainsvrresults.go
- rpcclient/chain.go
- rpcclient/example_test.go
I have also rearranged some command structs in `btcjson/chainsvrcmds.go` alphabetically to follow the convention.
> rpcclient: add deriveaddresses RPC command

- btcjson/chainsvrcmds_test.go
This is about the bug originally reported in #1476. In fact, the fix has been made redundant thanks to support for nullable JSON-RPC params introduced in https://github.com/btcsuite/btcd/pull/1594. This PR simply adds a unit test as proof that the said bug is no longer valid.
> btcjson: add test for null params in searchrawtransactions

- btcjson/chainsvrcmds.go
- btcjson/chainsvrresults.go
- rpcclient/mining.go
- rpcserverhelp.go
Basic implementation of GetBlockTemplate which has been marked with a `TODO`
> GetBlockTemplate RPC client implementation

- btcjson/walletsvrcmds.go
- btcjson/walletsvrcmds_test.go
- btcjson/walletsvrresults.go
- btcjson/walletsvrresults_test.go
- rpcclient/example_test.go
- rpcclient/wallet.go
- txscript/standard.go
- txscript/standard_test.go
| Docs | [getaddressinfo](https://bitcoincore.org/en/doc/0.20.0/rpc/wallet/getaddressinfo) |
-|-
Fields such as `label`, and `labels->purpose` are not included, since they are deprecated, and will be removed in Bitcoin Core 0.21.
Most of the fields in the results struct are repeated in the `embedded` field if (for example) the address itself is a script embedding another address. To have minimal code duplication, I have factored them out to a private struct.
Another noteworthy thing in this PR is the custom unmarshalling I did to support loading a `script` to a `txscript.ScriptClass`, without duplicating the entire struct with raw fields. I learnt about this technique in [this article](http://choly.ca/post/go-json-marshalling) if you want to read.
Tested locally with Bitcoin Core v0.20.1. …
> rpcclient: implement getaddressinfo command

- docs/installation.md
This PR
* fixes the link to bootstrap.dat
> [docs] Fix link to using bootstrap.dat

- btcjson/walletsvrresults.go
- btcjson/walletsvrresults_test.go
- rpcclient/example_test.go
- rpcclient/wallet.go
**Note to the reviewers:**
* The [official documentation](https://bitcoincore.org/en/doc/0.20.0/rpc/wallet/getwalletinfo/) is not accurate in pointing out the optional fields, so I'm relying on the [implementation in Bitcoin Core](https://github.com/bitcoin/bitcoin/blob/v0.20.1/src/wallet/rpcwallet.cpp#L2431-L2520).
* I have not included fields that have been deprecated and will be removed soon.
> rpcclient: implement getwalletinfo command

- .github/workflows/go.yml
- README.md
- go.mod
- release/README.md
- release/release.sh
Note: this requires #1619 before it can be merged.
> ci: add go 1.15 to tests

- btcjson/chainsvrresults.go
- rpcserver.go
Follow up of #1629.
This PR populates both the `txid` and `hash` fields in the RPC server implementation.
> rpcserver: add txid to getblocktemplate response

- btcjson/chainsvrresults.go
- btcjson/chainsvrresults_test.go
- rpcclient/chain.go
- rpcclient/example_test.go
[#RunTheNumbers](https://twitter.com/search?q=%23RunTheNumbers&src=typed_query&f=live) seems to be a thing on Twitter these days. This PR adds the [**`gettxoutsetinfo`**](https://bitcoincore.org/en/doc/0.20.0/rpc/blockchain/gettxoutsetinfo/) command to the rpcclient package, which is useful for performing inflation checks in Bitcoin.
> rpcclient: implement gettxoutsetinfo command

- btcjson/chainsvrresults.go
- btcjson/chainsvrresults_test.go
- rpcserver.go
Since JSON doesn't distinguish between ints and floats in its number type, Go will fail to decode valid integers in scientific notation as noted in #1458 
1. Added a unit test for this condition that fails before the fix and passes after
2. Verified that output values and format were unchanged when running `btcctl getmininginfo`
> Fix getmininginfo unmarshal error

- btcjson/chainsvrresults.go
- btcjson/walletsvrcmds.go
- btcjson/walletsvrcmds_test.go
- rpcclient/wallet.go
Implement backupwallet, dumpwallet, loadwallet and unloadwallet.
> rpcclient: add more wallet commands

- btcjson/jsonrpcerr.go
Just some basic housekeeping - add new JSON-RPC errors and document all the exported error codes. See [source](https://github.com/bitcoin/bitcoin/blob/master/src/rpc/protocol.h).
> btcjson: add new JSON-RPC errors and document them

- btcjson/walletsvrcmds.go
- btcjson/walletsvrcmds_test.go
- btcjson/walletsvrresults.go
- rpcclient/example_test.go
- rpcclient/wallet.go
Rebased on #1645, to avoid having to resolve merge conflicts later. This PR only implements `createwallet` as a first-step towards functional options.
I find the current way of dealing with optional parameters in RPC commands very hard to maintain, and also clunky from a user's perspective. We implement one rpcclient method per optional parameter, with long-winding names, closely following the order of the parameters!
This has been previously discussed a bit in #1589.
We have multiple methods to choose from, depending upon the options you want to use. In the example below, it is impossible to specify just `watchOnly` without specifying `count`. 😞 
```go
ListTransactions(account string)
ListTransactionsCount(account string, count int)
ListTransactionsCountFrom(account string, count int, …
```
> rpcclient: implement createwallet with functional options

- integration/rpctest/rpc_harness.go
This randomizes the port selection in rpctest.New (generateListeningAddresses), which allows our builds (during heavy server use) to retry a new sim if they hit a port collision.
> randomize port

- btcjson/chainsvrcmds.go
- btcjson/chainsvrcmds_test.go
- integration/bip0009_test.go
- integration/csv_fork_test.go
- integration/rpcserver_test.go
- integration/rpctest/node.go
- integration/rpctest/rpc_harness.go
- integration/rpctest/rpc_harness_test.go
- rpcserverhelp.go
Some improvements to the integration harness:
- allow `btcd` binary to be specified instead of always building it from source
- allow listener addresses to be overwritten to avoid port collisions
- allow overwriting RPC connection retry parameters
Everything falls back to the previous behavior if not otherwise specified. Existing users will just need to specify one more parameter.
EDIT: The PR now also contains a commit that restores compatibility with `bitcoind > 0.19`! There was a side effect of #1594 that caused the `sendrawtransaction` command not to work anymore.
@Roasbeef @wpaulino
> integration: optimize harness for better itest control, restore bitcoind compatibility

- rpcclient/infrastructure.go
Add ExtraHeaders in ConnConfig struct. It's	useful when RPC provider need customized headers. For example, [blockdaemon](http://www.blockdaemon.com/) require the header X-Auth-Token.
> rpcclient: add ExtraHeaders in ConnConfig

- wire/message.go
- wire/msgsendaddrv2.go
> Add support for receiving sendaddrv2 message from a peer

- btcjson/chainsvrresults.go
- rpcserverhelp.go
Update the fields of GetBlockChainInfoResult to reflect the current state of
the RPC returned by other full-node implementations.
* InitialBlockDownload - Node is in Initial Block Download mode if True.
* SizeOnDisk - The estimated size of the block and undo files on disk.
> btcjson (client): Update fields in GetBlockChainInfoResult

- txscript/opcode.go
- txscript/script.go
- txscript/script_test.go
Through profiling, I've found that the `IsUnspendable` method is a large source of allocations during the sync process.
In an effort to reduce the allocations made by this method, and in the sync process overall, I've simply removed the part of `parseScriptTemplate` which allocates and appends to an array (which never ends up being used by `IsUnspendable`) and pointed `IsUnspendable` to that method, called `checkScriptTemplateParseable`.
To show that this actually did reduce the allocations (and runtime) of the `IsUnspendable` method, I've created a benchmark and run it on both versions of the code, once on the [`e761244`](https://github.com/btcsuite/btcd/commit/e7612446051c390a4372d7604029b1eaff8a7f1d) commit, and once on the [`0963732`](https://github.com/btcsuite/btcd/commit/096373242c2 …
> Improve gc for isunspendable method

- txscript/hashcache_test.go
Encountered this while rebasing #1684, see commit msgs for more details
> txscript/hashcache_test: fix flake due to resetting RNG

- mempool/estimatefee.go
When you provide an argument to EstimateFee(numblocks uint32) that exceeds the estimateFeeDepth (which is set to 25), you get an error message that says "can only estimate fees for up to 100 blocks from now".  The variable used in the if condition and the variable used for creating the error message should be the same.
> Fix error message returned by EstimateFee

- README.md
- blockchain/README.md
- blockchain/fullblocktests/README.md
- blockchain/indexers/README.md
- btcec/README.md
- btcjson/README.md
- chaincfg/README.md
- chaincfg/chainhash/README.md
- connmgr/README.md
- database/README.md
- database/ffldb/README.md
- database/internal/treap/README.md
- docs/code_contribution_guidelines.md
- docs/configuration.md
- docs/index.md
- integration/README.md
- integration/rpctest/README.md
- mempool/README.md
- mining/README.md
- mining/cpuminer/README.md
- netsync/README.md
- peer/README.md
- peer/doc.go
- rpcclient/README.md
- txscript/README.md
- wire/README.md
I was looking at the integration tests when I realized all of our shields are still linked to travis-ci despite us moving to github actions (#1575). While I was there, I switched the documentation links to `go.dev` since [godoc.org is now deprecated](https://blog.golang.org/godoc.org-redirect).
While we're at it probably makes sense to fix the link in the corner of the repo. @jcvernaleo I think you have permissions here, but if not can ping @Roasbeef
> docs: update shields

- go.mod
- go.sum
- integration/rpctest/memwallet.go
This is currently an issue for projects that depend on the latest version of `btcutil` and use the btcd integration test harness.
> build: update btcutil dependency

- rpcclient/net.go
Just noticed this while checking that the godoc didn't need any changes for #1706.
> rpcclient: fix documentation typo

- integration/rpctest/blockgen.go
- mining/mining.go
If we tried to include transactions having witnesses, the block would be
invalid since the witness commitment was not added.
> rpctest: add witness commitment when calling CreateBlock

- README.md
> Don't reference the readme that we don't produce

- chaincfg/params.go
On signet all previous soft forks and also taproot are always activated,
meaning the version is always 0x20000000 for all blocks. To make sure
they activate properly in `btcd` we therefore need to use the correct
bit to mask the version.
This means that on any custom signet there would need to be 2016 blocks
mined before SegWit or Taproot can be used.
cc @wpaulino, @Roasbeef.
> chaincfg: fix deployment bit numbers

- mempool/mempool_test.go
In this commit, we add an additional test case for inherited RBF
replacement. This test case asserts that if a parent is marked as being
replaceable, but the child isn't, then the child can still be replaced
as according to BIP 125 it shoudl _inhreit_ the replaceability of its
parent.
The addition of this test case was prompted by the recently discovered
Bitcoin Core "CVE" [1]. It turns out that bitcoind doesn't properly
implement BIP 125. Namely it fails to allow a child to "inherit"
replaceability if its parent is also replaceable. Our implementation
makes this trait rather explicit due to its recursive implementation.
Kudos to the original implementer @wpaulino for getting this correct.
[1]: https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2021-May/018893.html
> mempool: add additional test case for inherited RBF replacement

- CHANGES
> Update CHANGES file for 0.22.0 release

- btcjson/walletsvrcmds.go
FeeRate is expressed in BTC/kb so the correct type is *float64
Fixes #1728 
This is my first PR. Any feedback is appreciated
> btcjson: Update WalletCreateFundedPsbtOpts.FeeRate type

- mempool/policy.go
- mempool/policy_test.go
This changes isDust to IsDust so other golang projects (btcwallet
or lnd) can use the precise dust calculation used by btcd.
> mempool: export isDust for use in other projects

- README.md
- docs/contact.md
We haven't exactly decided to make the move yet, but I want this PR ready.  We have a new channel already and it does not look like freenode is a viable solution any more based on what has happened with many other channels.
> Switch irc to libera.chat

- btcec/signature.go
- btcec/signature_test.go
This adds a check to ensure that the recovered pk is not at the point of infinity
> btcec: check if recovered pk is at point of infinity

- mempool/policy.go
This commit modifies no behavior and would allow other projects to retrieve the dust limit for a particular output type before the amount of the output is known (so `IsDust` wouldn't be possible). This is particularly useful in the Lightning Network for channel negotiation.  I did not include a unit test but I did locally check the following dust limits at the current 3000sat/kvb dust relay feerate:
- p2pkh: 546
- p2sh: 540
- p2wsh: 330
- p2wpkh: 294
- p2tr: 330
> mempool: introduce GetDustThreshold to export dust limit calculation

- connmgr/connmanager_test.go
- Fixes #1748
Changes the comment to 
```go
// Now examine the status of the connection request, it should read a 
// status of ConnCanceled.
```
This should resolve the confusion.
> connmgr: Fix stale comment in TestRemovePendingConnection

- rpcclient/infrastructure.go
Motivation: When used as a library in LND, current behavior means that a
single request failing will result in the entire  process shutting down.
This adds behavior similar to the retries of persistent RPC connections
to HTTP request.
* Initial backoff: 500ms
* Linear increase
* Max retries: 10
Room for future improvement:
* Make configurable
* Add jitter
* Tests for retry behavior
---
Unfortunately due to the way Go http requests are consumed, I had to move down the construction of the request. This resulted in  `sendPostDetails` and `sendPost` becoming redundant.
> rpcclient: Add retry with backoffs to HTTP POST requests

- connmgr/tor.go
Signed-off-by: Tomasz Ziolkowski <tomasz.ziolkowski@allegro.pl>
> reduce redundant memory allocation - resolves btcsuite/btcd#1699

- integration/rpcserver_test.go
- rpcclient/mining.go
- rpcserver.go
- rpcserverhelp.go
Fixes [rpcclient issue](https://github.com/btcsuite/btcd/issues/1747) caused by using the rpcclient with bitcoind and expecting an int64, but bitcoind is [returning a float64](https://github.com/bitcoin/bitcoin/pull/7480/files).
- Change getnetworkhashps and handlers return type from an int64 to a float64 to be aligned with bitcoin core and to also avoid the overflow
- Extended rpcserver integration tests to test client methods `GetNetworkHashPS`, `GetNetworkHashPS2`, and `GetNetworkHashPS3`
> rpcclient+rpcserver+integration: GetNetworkHashPS3 must be float64

- Makefile
- blockchain/chain.go
- blockchain/common_test.go
- blockchain/thresholdstate.go
- blockchain/thresholdstate_test.go
- blockchain/versionbits.go
- btcjson/chainsvrresults.go
- chaincfg/deployment_time_frame.go
- chaincfg/params.go
- integration/bip0009_test.go
- rpcserver.go
In this PR, we further abstract our Version Bits implementation to be able to support _both_ BIP 9 time based timeouts, as well as BIP 8 block based timeouts. In order to bridge the two mechanisms, we introduces a series of new light interfaces that allow us to abstract away from when exactly a soft fork deployment "starts" and "ends". This PR doesn't yet add any new BIP 8 compatible deployments, as it's mean to be a pure refactoring that doesn't introduce any new behavior. It's also the case that BIP 8 has some extra Version Bits states that need to be added to our Version Bits implementation. 
The only thing missing from this PR is a few additional tests to confirm that no change in behavior has occurred. Reviewers should examine the change to how we define deployments that are "always …
> chaincfg+blockchain: abstract/refactor BIP 9 version bits implementation to work w/ BIP 8 block heights 

- btcutil/go.mod
- btcutil/psbt/go.mod
- go.mod
This was the version tagged that created the new `ecdsa` and `schnorr`
packages. Updating these pinned version lets importers properly use
these packages and build. Things build as is since we use replace
directive to point to the latest version _in the repo_ when we build.
> build: update to btcec v2.1.0

- btcec/go.sum
- btcutil/go.sum
- btcutil/psbt/go.mod
- go.mod
Fixes https://github.com/btcsuite/btcd/issues/1791.
> build: retract bogus tags from btcd fork

- mempool/estimatefee.go
Fixes a negative index bug that makes the node crash on chain
reorganizations.  The bug is detailed in
github.com/btcsuite/btcd/issues/1660.
A better design than just skipping the transaction would make
the fee estimator more accurate and that should implemented
at a later date.
Fixes #1660
> mempool/estimatefee: Fix negative index bug

- btcec/go.mod
- btcutil/go.mod
- btcutil/psbt/go.mod
- chaincfg/chainhash/go.mod
- go.mod
Fixes https://github.com/btcsuite/btcd/issues/1822.
After merging this PR we need to push two tags: `chaincfg/chainhash/v1.0.0` and `btcec/v2/v2.1.1`.
And I _think_ the two tags cannot be on the same commit (because go mod is just mean that way), so I'd suggest adding `chaincfg/chainhash/v1.0.0` to 7cc824e9 and `btcec/v2/v2.1.1` to 4ad74cd4.
cc @Roasbeef.
> Remove circular dependency issue between `btcec/v2` and main package

- .github/workflows/go.yml
With PR #1785 multiple coverage reports are sent to coveralls. This makes coveralls only consider the last report sent. This fix treat all reports has parallel coverage reports so they can all be compiled later by coveralls.
Coverage and after before 
* Before https://coveralls.io/builds/44996210
* After https://coveralls.io/builds/45515236
> Fixes coveralls coverage report

- btcutil/go.mod
- btcutil/go.sum
- btcutil/psbt/go.mod
- btcutil/psbt/go.sum
- go.mod
- go.sum
In this commit, we update the top level module to use the newly tagged
sub-modules. Once we remove the circular dependant in these sub-modules,
then we'll no longer have to do things like this.
> build: update to btcec/v2.1.3 and chaincfg/chainhash v1.0.1

- blockchain/thresholdstate.go
In this commit, we demote a series of log statements added while
debugging the modified BIP 9 state machine. These are rather spammy on
mainnet, so we demote the transition logs (moving to a new state) to
debug, and the remaining log (when we're still in started to trace).
> blockchain: demote BIP 9 log statements

- connmgr/tor.go
This reverts commit 780cc0889fd2f326e4a2a9b513d8d30ff37e0cd2.
Oversight on my part, that extra byte is actually used. Without this, DNS resolution via tor proxy won't work
> Revert "reduce redundant memory allocatio - resolves btcsuite/btcd#1699"

- btcjson/jsonrpc.go
This resolves https://github.com/btcsuite/btcd/issues/1711. The issue causes problems with downstream libraries if the `jsonrpc` parameter isn't included with an rpc request.
Oddly enough the comment on line 159 calls for defaulting to `RpcVersion1` but the code does not do it.
I just added in a quick check and default in the case of an empty version.
> Default to JSONRPC 1.0 if the rpcVersion empty

- btcjson/chainsvrresults.go
Update the fields of GetNetworkInfoResult to reflect the current number of inbound and outbound peer connections.
* ConnectionsIn - The number of inbound peer connections
* ConnectionsOut - The number of outbound peer connections
ref: https://github.com/bitcoin/bitcoin/pull/19405
release note: https://github.com/bitcoin/bitcoin/blob/master/doc/release-notes/release-notes-0.21.0.md#updated-rpcs
```
getnetworkinfo now returns two new fields, connections_in and connections_out, that provide the number of inbound and outbound peer connections. These new fields are in addition to the existing connections field, which returns the total number of peer connections. (#19405)
```
> btcjson: Update fields in GetNetworkInfoResult

- btcd.go
- go.mod
- ossec/ossec.go
- ossec/ossec_openbsd.go
I've created a patch to harden the daemon on OpenBSD by using [pledge(2)](http://man.openbsd.org/pledge) and [unveil(2)](http://man.openbsd.org/unveil). This way the program gets killed if any syscall is called other than the basic networking or file system ones, preventing further exploitation of a system once a program is compromised. Furthermore, the view of the file system is restricted to only access the files and directories the daemon needs.
> harden daemon on OpenBSD

- integration/rpctest/rpc_harness.go
Replaces the implementation of `generateListeningAddresses` to use `NextAvailablePort` from lntest. Would have imported directly, however this creates a circular dependency.
> rpctest: ensure rpclisten is set to an available port

- btcjson/jsonrpcerr.go
- btcjson/walletsvrcmds.go
- btcjson/walletsvrcmds_test.go
- mempool/mempool_test.go
- rpcclient/wallet.go
This adds a `AddressType` field to the `btcjson.GetNewAddressCmd` type to facilitate requesting different address types from btcwallet.
Required for https://github.com/btcsuite/btcwallet/pull/783
Partially resolves https://github.com/btcsuite/btcd/issues/1703
> btcjson: add addresstype arg to getnewaddress

- chaincfg/params.go
The existing values were copied over from the testnet deployment, which
uses a much larger miner confirmation window. As a result, the main
taproot deployment would require thousands of blocks to properly
activate in development environments.
> chaincfg: use lower custom activation threshold for regtest+simnet

- btcjson/chainsvrcmds_test.go
- btcjson/chainsvrresults_test.go
- btcjson/zmqsvrcmds.go
- btcjson/zmqsvrresults.go
- rpcclient/zmq.go
> rpcclient: add getzmqnotifications RPC

- btcd.go
If GOGC env var is explicitly set, use it. Otherwise, set GC to 10% (default).
> btcd: don't override explicitly set GOGC

- btcutil/psbt/psbt.go
- btcutil/psbt/psbt_test.go
Fixes https://github.com/btcsuite/btcd/issues/1841.
BIP-0174 states that the transaction must be in the old serialization
format (without witnesses).
https://github.com/bitcoin/bips/blob/master/bip-0174.mediawiki#specification (see first entry in table).
cc @Roasbeef, @positiveblue
Fixes https://github.com/lightningnetwork/lnd/issues/6386
> psbt: always use non witness serialization format

- btcec/go.mod
- btcec/go.sum
- btcec/schnorr/musig2/bench_test.go
- btcec/schnorr/musig2/context.go
- btcec/schnorr/musig2/keys.go
- btcec/schnorr/musig2/musig2_test.go
- btcec/schnorr/musig2/nonces.go
- btcec/schnorr/musig2/sign.go
- btcec/schnorr/signature.go
In this commit, we add a fully featured `musig2` implementation capable of generating partial signatures, combining them, and finally ensuring that the combined signature is a valid BIP-340 schnorr signature. This implementation is based off of [this spec](https://github.com/ElementsProject/secp256k1-zkp/blob/master/doc/musig-spec.mediawiki) from the `secp256k1-zkp` repo. 
I consider much of the external API to still be a WIP, but everything is functional as is. The API will likely evolve as we start to use it upstream in `lnd`, `pool`, `loop`, etc, etc. 
Before this PR is ready for merging, I want to further optimize it (adding benchmarks along the way), as during signing and nonce generation a lot of values end up being computed multiple times, when instead they can be computed once and …
> btcec/schnorr/musig2: add new musig2 implementation based on musig2 draft BIP

- btcec/fuzz_test.go
Courtesy of the Cosmos Network security team, this change
adds a fuzzer to ParsePubKey, given that Tendermint uses
this code.
/cc @elias-orijtech
> fuzz: add ParsePubKey fuzzer

- rpcclient/infrastructure.go
This PR fixes a crash that happens every time when the post errors max retries times.
> rpcclient: fix crash in http retry handler

- mempool/mempool.go
- mempool/policy.go
- mempool/policy_test.go
Export checkStandardness func so that it can be used elsewhere
> mempool: export checkStandardness func

- btcjson/walletsvrcmds_test.go
- rpcclient/wallet.go
Since the address type was [added to the btcjson and rpcclient packages](https://github.com/btcsuite/btcd/commit/061aef98af1321d2cad437afcb7dcbd562a5b3b6), but the [corresponding btcwallet PR](https://github.com/btcsuite/btcwallet/pull/783) is not yet merged, it made it clear that the rpcclient would ideally be able to work with older btcwallet versions.  That is not straightforward with the recently modified `rpcclient.Client` methods.  See https://github.com/btcsuite/btcd/issues/1843.  This change seeks to make the rpcclient's `GetNewAddress` method compatible with both old and new btcwallet apps.
This reverts the previous breaking change to the `GetNewAddress` and `GetRawChangeAddress` `rpcclient.Client` methods, and adds the methods `GetNewAddressType` and `GetRawChangeAddressType` …
> rpcclient: add getnewaddresstype and revert breaking change

- rpcclient/infrastructure.go
The fix of the retry logic (https://github.com/btcsuite/btcd/pull/1856) missed the return when the http response was nil. This PR fixes this issue.
> rpcclient: fix missing return

- btcec/btcec.go
- btcec/curve.go
- btcec/error.go
- btcec/schnorr/musig2/keys.go
- btcec/schnorr/musig2/musig2_test.go
- btcec/schnorr/musig2/nonces.go
- btcec/schnorr/musig2/sign.go
This PR fixes nonce generation to include XORing the passed secret key with the random bytes. (see: https://github.com/jonasnick/bips/blob/musig2/bip-musig2.mediawiki#nonce-generation-1)
Additionally I updated the nonce generation to 0.3.0 and added the testcases
(https://github.com/jonasnick/bips/blob/musig2/bip-musig2.mediawiki#Change_Log)
(https://github.com/jonasnick/bips/commit/f4216927a6daf796e36a53b6d2c8bc2782016d21)
I'm currently in the progress of catching up to 0.4.0
> MuSig2: Catch up to 0.4.0

- docs/configuring_tor.md
While following the guide I hit on a minor dead link:
https://archive.is/fX52n is no more
I found this for a replacement: https://community.torproject.org/onion-services/setup/
> doc: fix Tor hidden service setup link

- Dockerfile
Image fails to build on the current 1.16 tag with the error:
```
> docker build . --build-arg ARCH=amd64
...
btcd.go:21:2: //go:build comment without // +build comment
The command '/bin/sh -c set -ex   && if [ "${ARCH}" = "amd64" ]; then export GOARCH=amd64; fi   && if [ "${ARCH}" = "arm32v7" ]; then export GOARCH=arm; fi   && if [ "${ARCH}" = "arm64v8" ]; then export GOARCH=arm64; fi   && echo "Compiling for $GOARCH"   && go install -v . ./cmd/...' returned a non-zero code: 1
```
> build: bump golang base image version to 1.17

- blockchain/weight.go
- wire/msgtx.go
In this commit, we fix a bug that would cause nodes to be unable to parse a given block from the wire. The block would be properly accepted if fed in via other mechanisms.
The issue here is that the old checks for the maximum witness size, circa segwit v0 where placed in the wire package _as well_ as the tx engine. This check should only be in the engine, since it's properly gated by other related scrip validation flags.
The fix itself is simple: limit witnesses only based on the maximum block size in bytes, or ~4MB.
> wire: remove erroneous witness size check in wire parsing

- version.go
This includes the recent fix to the wire witness wire parsing bug.
> build: bump version to v0.23.2

- server.go
This is a typo fix. There is an underlying ban bug related to this that causes two btcd nodes to ban each other due to "transaction not found" errors.
> Fixed ban bug that doesn't print numTxns

- btcutil/psbt/psbt.go
This commit adds a GetTxFee method to the psbt.Packet structure. The method returns the PSBT's fee.
> btcutil/psbt: add method Packet.GetTxFee

- txscript/sign.go
- txscript/taproot.go
- txscript/taproot_test.go
In this commit, we fix an inadvertent mutation bug that would at times cause the private key passed into the tweak function to actually be *modified* in place.
We fix this by accepting the value instead of a pointer. The actual private key struct itself contains no pointer fields, so this is effectively a deep copy via dereference.
We also add a new unit test that fails w/o this change, to show that the private key was indeed being modified.
> txscript: modify TweakTaprootPrivKey to operate on private key copy

- btcec/schnorr/signature.go
- btcec/schnorr/signature_test.go
This is a fix similar to https://github.com/btcsuite/btcd/pull/1905. We'll always make a copy of the key in the local scope before passing it around elsewhere. Depending on the parity of the public key, the private key itself might need to be negated.
A similar test is added here that fails without the patch to the signature.go file.
> btcec/schnorr: use private key copy for BIP-340 signatures

- btcec/schnorr/musig2/bench_test.go
In this commit, we fix the `BenchmarkPartialVerify` test. When we moved to musig 1.0, we stopped requiring the input as an x-only key. So we need to remove the round trip serialization to force the key to be x-only.
> btcec/schnorr/musig2: fix BenchmarkPartialVerify

- btcutil/base58/base58.go
- btcutil/base58/base58_test.go
> base58: fix decoding issue

- docs/using_docker.md
As DockerHub the image is now non existant, this updates the documentation for Compose towards building your own image instead.
fixes #1833
> Update Docker documentation towards building your own image

- chaincfg/chainhash/hash.go
This PR adds a `MarshalJSON()` method to `chainhash.Hash`. As a result, when serializing structures as JSON, a chain hash will be represented as its `String()` value.
This change simplifies the JSON serialization of block and block header.
> chainhash: JSON marshal hash as string

- connmgr/connmanager.go
In the case of an error the connection struct is never deleted from the **pending** hash map.
In some testing I observed leaks of 3MB in an hour
The problem stem from the fact that the handleFailedConn does not reuse the connect but allocate a new one
> Fix memory leak in connmanager

- txscript/sign.go
- txscript/sign_test.go
- txscript/taproot.go
In this PR, we fix a bug in RawTxInTaprootSignature that would cause
the function to not properly apply the sighash flag for non-default
sighash signatures. The logic would end up applying `0x00` as a mask,
which will always be `0x00` on the other end.
The RawTxInTapscriptSignature function was correct, though it had the
ordering switched as it applies the sighash if the type doesn't equal
default.
The second commit adds tests that fail w/o the first commit. Without 
the first commit, the test fails for the keyspend sigs as they're always 
64 bytes, since the sighash wasn't added for non-default types.
> Sighash taproot keyspend bug fix

- docs/code_contribution_guidelines.md
This PR proposes an update to the Go version, specified in the contribution guidelines as per:
- The Go version, [specified](https://github.com/btcsuite/btcd/blob/ecf98ce34fbc7a707a917272afd2ca0ebfb7ee1c/README.md) in the Readme file.
- The actual PR which updated the minimum supported Go versions, namely: https://github.com/btcsuite/btcd/pull/1753.
> docs: Update Go version as per the Readme.

- txscript/script.go
IsUnspendable allows outputs, not inputs to be pruned instantly.
> txscript: Fix typo in IsUnspendable() comment

- txscript/scriptbuilder.go
- txscript/scriptbuilder_test.go
The default script builder allocates 500 bytes of memory for each script. That is quite large for most applications and therefore wastes a lot of memory when only small scripts are created. To avoid breaking backward compatibility, we add a new functional option to the NewScriptBuilder function that allows the user to specify the initial allocation size.
cc @Roasbeef, @Crypt-iQ.
> txscript: allow script builder capacity to be specified

- txscript/opcode.go
- txscript/script.go
- txscript/scriptnum.go
- txscript/scriptnum_test.go
- txscript/stack.go
- txscript/standard.go
I would like to import these functions to use in https://github.com/decred/dcrdex/pull/2196. The exact same functions are exported in dcrd, but I'd rather import from here on the off chance that something changes.
Thanks!
> Export MakeScritpNum, AsSmallInt, and IsSmallInt

- btcutil/psbt/utils.go
This adds a method to verify the utxo data of a psbt package especially the `NonWitnessUtxo | WitnessUtxo` data.
This will be used in other packages to make sure we have the correct psbt structure with all relevant input fields populated.
Relates to lightningnetwork/lnd#7527
Happy to discuss other approaches, other PRs which call this function in lnd and btcwallet would follow if we want this function in this package ?
> psbt: add verification method for utxo data

- txscript/script.go
> txscript: fix typos

- btcd.go
- config.go
Enables Go memory profiling.  If the cpuprofile shows a lot of time spent on gc, it's useful to then do a memory profile to see where the memory alloctions happen.
Unlike the --profile flag, this allows for easy generation of a memory profile for the entire duration of which btcd has been running for in various readble graphs.
> btcd: Add memory profiling flag

- blockchain/bench_test.go
- blockchain/utxoviewpoint.go
- blockchain/validate.go
Maps have a higher overhead than slices.  As slices can be used instead of maps, we avoid the overhead of making a map.
This was one of the overheads I've noticed when profiling ibd for PR #1955
> blockchain: Use slices when fetching utxos

- README.md
- docs/code_contribution_guidelines.md
- docs/installation.md
The readme suggests a minimum version of 1.16 but the go.mod requires go 1.17.
> main: Update README.md's minimum go version

- wire/msgtx.go
- wire/msgtx_test.go
- Adds `NewOutPointFromString` function in `wire` package.
- Adds unit tests for `NewOutPointFromString`
> Add wire.Outpoint parser from string

- blockchain/difficulty.go
- chaincfg/params.go
This commit emulates the behavior of Bitcoin Core introduced in https://github.com/bitcoin/bitcoin/pull/6853 that disables retargeting of the required proof of work for regtest.
Attempts to fix https://github.com/lightninglabs/neutrino/pull/256 in a less hacky way (needs a PR in that repo as well after this one has been merged).
> blockchain+chaincfg: disable retargeting for regtest

- blockchain/blockindex.go
- blockchain/chain.go
- blockchain/chain_test.go
- blockchain/chainio.go
- blockchain/difficulty.go
- blockchain/interfaces.go
- blockchain/thresholdstate.go
- blockchain/validate.go
This PR allows an external library like `neutrino` to be able to perform contextual and context-free header validation. This is achieved by introducing two new interfaces `HeaderCtx` (which replaces `*blockNode` in the relevant functions) and `ChainCtx` (which replaces `*BlockChain` in the relevant functions). A library calling into these functions needs to only satisfy the interface to be able to validate any received headers.
> blockchain: refactor and export header validation checks

- btcec/schnorr/musig2/context.go
- btcec/schnorr/musig2/musig2_test.go
Previously the early nonce generation option was not being respected when creating the context, with the `WithKnownSigners` option being used.
> musig2: fix early nonce gen option

- btcjson/chainsvrresults.go
- rpcserver.go
- rpcserverhelp.go
Bitcoin Core has added `address` field and removed `addresses` and `reqSigs` rpc response fields. The fields were deprecated on version 22 and they've been removed from version 23. For instance, the following methods are affected:
- https://bitcoincore.org/en/doc/22.0.0/rpc/rawtransactions/getrawtransaction/
- https://bitcoincore.org/en/doc/22.0.0/rpc/rawtransactions/decoderawtransaction/
- https://bitcoincore.org/en/doc/22.0.0/rpc/blockchain/gettxout/
This PR adds the new `address` and deprecates the removed fields.
Closes #1874
> Add address field (rpc client & server)

- btcec/schnorr/signature.go
The RFC used for deterministic nonce generation is rfc6979, not rfc6679. This commit fixes documentation in two places accordingly.
> schnorr: correct rfc reference in docs

- txscript/engine.go
- txscript/engine_debug_test.go
We add a new StepCallback as optional function closure on the Engine that will be called every time a step has been performed during script execution.
This is only meant to be used in debugging.
More specifically, this is used for Tapsim: https://github.com/halseth/tapsim
> txscript/engine: add execution StepCallback

- blockchain/chain.go
- blockchain/chainio.go
- blockchain/indexers/addrindex.go
- blockchain/indexers/cfindex.go
- blockchain/indexers/txindex.go
- btcd.go
- config.go
- database/ffldb/blockio.go
- database/ffldb/db.go
- database/ffldb/driver_test.go
- database/ffldb/export_test.go
- database/interface.go
- rpcserver.go
- server.go
- wire/protocol.go
- wire/protocol_test.go
Adds pruning to btcd.
1) Add `PruneBlocks()` to transaction interface. Prune blocks is a no-op when the total block file size is equal to or under the target size. If the total block files size is over the target size, oldest block files are deleted along with the block indexes that point to those block files. Returns the hashes of the deleted blocks.
1) Add SFNodeNetworkLimited.
2) Add SFNodeNetworkLimited to default services.
1) New `pruneTarget` param to indicate how much the block files should take up.l
2) Attempts to prune blocks, spend journals, and relevant indexes on every `connectBlock`
1) Added PruneBlock to Manager and implemented PruneBlock to every indexer.
1) Prune flag is defined. It limits the prune to 1536MiB as we need to guarantee 288 blocks to abide by the …
> main, wire, blockchain, indexers, ffldb: Add pruning

- chaincfg/chainhash/hash.go
- chaincfg/chainhash/hash_test.go
Recent commits 1d6e578 and 72ea23e introduced a change in the way Hashes are serialized and deserialized. This change could cause errors in downstream applications that persisted hashes serialized using the previous methods.
This introduces support for legacy-serialized hashes unmarshaling and restores the compatibility with previous versions.
> chainhash: add support to legacy-marshaled hashes

- .gitignore
- btcutil/go.sum
- rpcclient/infrastructure.go
This PR updates gitignore, go mod, and catches shutdown signal when sending RPC requests.
> rpcclient: catch shutdown signal when sending RPC requests

- integration/prune_test.go
Adds a check to make sure that prune status on getblockchaininfo returns true for pruned nodes.
> integration: add test to check prune status

- blockchain/validate.go
- blockchain/validate_test.go
Some callers only want to check the coinbase height rather than be given the height. Also reduce allocations for cb height parsing
> blockchain: export CheckSerializedHeight

- rpcclient/chain_test.go
Adding a few tests to cover `func (f FutureGetBestBlockHashResult) Receive()`.  I've noticed that `rpcclient` has 0.6% test coverage (before this PR):
```bash
$ git log -1
commit ad26585576912588d213dbe973b222fcec621546 (HEAD, origin/master, origin/HEAD)
Author: David Cardenas <47157243+davidcardenasus@users.noreply.github.com>
Date:   Tue Oct 17 02:47:09 2023 -0700
$ go-acc ./rpcclient
ok  	github.com/btcsuite/btcd/rpcclient	0.148s	coverage: 0.6% of statements in ./rpcclient
```
this PR bumps it up to 0.9%
```bash
$ go-acc ./rpcclient
ok  	github.com/btcsuite/btcd/rpcclient	0.234s	coverage: 0.9% of statements in ./rpcclient
```
I want to keep adding tests but I want to do them in their own PRs: as some tests will be larger than others, I don't want the PR(s) to be too big and unreadable.
> Added tests for FutureGetBestBlockHashResult.Receive

- btcutil/go.sum
- go.mod
- go.sum
- rpcclient/chain_test.go
Added test for client.GetChainTxStatsAsync() in rpcclient.  This sets up a test websocket server to run the tests.  Also, ensure these are run within a timeout, since they rely on concurrency.
Similar to [this other pull request](https://github.com/btcsuite/btcd/pull/2048), these changes increase the code coverage for rpcclient tests to 5.3%
```bash
go-acc ./rpcclient/
ok  	github.com/btcsuite/btcd/rpcclient	0.255s	coverage: 5.3% of statements in ./rpcclient/
```
> Added test for client.GetChainTxStatsAsync() in rpcclient.

- rpcclient/chain_test.go
now testing that GetBestBlockHashAsync sends the getbestblockhash command via websocket connection and that the channel returned can be used to send the response when it is received
> added tests for GetBestBlockHashAsync

- blockchain/blockindex.go
- blockchain/chain.go
- blockchain/chain_test.go
- btcjson/chainsvrresults.go
- docs/json_rpc_api.md
- integration/getchaintips_test.go
- rpcclient/chain.go
- rpcserver.go
- rpcserverhelp.go
getchaintips rpc call is implemented and follows the algorithm that Bitcoin Core has in https://github.com/bitcoin/bitcoin/blob/50422b770a40f5fa964201d1e99fd6b5dc1653ca/src/rpc/blockchain.cpp#L1374.
Test coverage checks that the height, block hash, branchlen, and status are correct. I also tested the rpc on regtest with blocks: 
`78b945a390c561cf8b9ccf0598be15d7d85c67022bf71083c0b0bd8042fc30d7`
`1b97df2be6c634e40a5f410f4758ba707c4452cda6f3707b4935c9e7760df965`
which both build on top of the genesis block.
```
0000002006226e46111a0b59caaf126043eb5bbf28c34f3a5e332a1fc7b2b73cf188910f467c23519a04a309fb31f27572a5e8e8eadb9f1881a7c12b30a06438bdde486c5cca6463ffff7f200100000001020000000001010000000000000000000000000000000000000000000000000000000000000000ffffffff025100ffffffff0200f2052a0100000016001 …
```
> blockchain, btcjson: Implement getchaintips rpc call

- chaincfg/params.go
Also, add mainnet seed.
I changed the DNS to .net due to issues with DNS blacklists. The .org domain will stay up for now. But I may have to take it down in the future.
> Update petertodd seed DNS to .net

- netsync/manager.go
- wire/protocol.go
- wire/protocol_test.go
isSyncCandidate is now changed to return true even if the peer is a
pruned node if and only if our chaintip is within 288 blocks of the
peer.
Rationale being that pruned nodes that signal NODE_NETWORK_LIMITED
MUST serve 288 blocks from their chaintip.  If our chaintip is within that
range, this peer can be a sync candidate even if they aren't an archival node.
> wire, netsync: change isSyncCandidate behavior

- chaincfg/chainhash/hashfuncs.go
- chaincfg/chainhash/hashfuncs_test.go
When profiling the ibd, I noticed that `TxHash()` is allocating quite a bit of memory.
I also noticed this with utreexod in the past and I resolved this by creating a new double hash function. I've benchmarked it and made is more efficient in this PR.
Benchstat for `BenchmarkTxHash()` showed a slight bit of increase in `sec/op` which is likely due to the overhead of serializing into a `hash.Hash` instead of the `bytes.Buffer` in the previous `TxHash()`. However, for real life cases, the new `TxHash()` will be faster as we're saving on the unnecessary serialization into `bytes.Buffer` as [sha256.Sum256()](https://cs.opensource.google/go/go/+/refs/tags/go1.20.4:src/crypto/sha256/sha256.go;l=252-261)will call `Write()` into the hash anyways.
The memory allocation savings is ~37% compared to …
> chainhash, wire, btcutil, main: Memory efficient txhash

- blockchain/chain.go
- blockchain/chainio.go
- blockchain/sizehelper.go
- blockchain/sizehelper_test.go
- blockchain/utxocache.go
- blockchain/utxocache_test.go
- blockchain/utxoviewpoint.go
- blockchain/validate.go
- cmd/addblock/import.go
- config.go
- database/ffldb/db.go
- database/ffldb/driver_test.go
- database/ffldb/export.go
- netsync/blocklogger.go
- netsync/manager.go
- server.go
Updated the PR and is now very different from #1373.
Main differences are:
In #1373, the view is still used as a middleman. The flow for doing block validation would be:
```
1. Make a new UtxoViewPoint.
2. Load the relevant inputs into the UtxoViewPoint from the cache.
3. Connect transactions in the UtxoViewPoint
4. Apply the connections to the cache from the UtxoViewPoint
5. Flush the cache to the database when needed
```
The problems with these approach were:
(2) is extremely expensive as there a lot of memory allocated by creating a whole new set of key/value pairs of the existing UTXOs.
(4) introduces a new code path from [view -> cache] and in turn introduces a whole new set of bugs.
The new code is different where the flow during headers-first (blocks up until the checkpoint) is: …
> blockchain, cmd, netsync, main: Add utxocache

- mining/mining.go
Enhance and tidy the code comments
> fix: enhance code comments

- blockchain/sizehelper.go
- integration/rpctest/node.go
- integration/rpctest/rpc_harness.go
This fixes two issues with the current RPC integration test framework:
- Generated test temp directories were created using a non-mutex-protected harness ID and a deprecated way to create temp directories, both is now fixed
- Because Go creates a sub process for each package that is tested, a package-global variable to track used TCP ports doesn't work reliably, especially if multiple packages are run in parallel. This PR adds a new way to issue unique TCP ports per process ID, which needs to be the parent process ID of each sub-process to work as expected.
> rpctest: integration test harness fixes

- btcutil/bench_test.go
- btcutil/block.go
- btcutil/tx.go
This is https://github.com/btcsuite/btcd/pull/2023, but with some code style fixes and added benchmarks.
> btcutil: reuse serialized tx during TxHash

- rpcclient/infrastructure.go
- wire/msgblock.go
This commit makes sure the batch requests are always GCed before sending back the responses for them. In particular,
- `removeRequest` didn't remove the item from `batchList`, which is now fixed.
- `Send` didn't remove the request from `requestMap`, which is now fixed by using `removeRequest`.
In addition, a `Copy` method is added to `MsgBlock` to fix another heap escape found in lnd's `GetBlock`.
> rpcclient: make sure batch requests are GCed

- Makefile
This pr added a new `make help` function for displaying which commonly used commands that the Makefile supported. This is useful when a new developer goes to find a helpful tool for testing or building etc.
> refactor: add `make help` to display the usage for project Makefile

- blockchain/utxocache.go
On startup when the headers-first mode is off, when receiving the first block, the periodic flush will trigger.  The lastflushtime wasn't set which resulted in the flush being triggered on the first block on restart.
Addresses #2087
> blockchain: set the lastflushtime when setting the lastflushhash

- netsync/manager.go
Noticed during ibd that there's a slight overhead for handleBlockchainNotification on mempool/fee estimator updates. Since there's no reason to be looking at this while we're not caught up, return early and avoid the calls.
> netsync: don't update mempool/fee estimator unless we're synced up

- rpcclient/infrastructure.go
Becuase the `rpcclient.Response` struct's fields are not exported we can not mirror the functionality of `newFutureError` ourselves. This is an issue especially when creating custom commands because we are forced to panic any errors in the `*Async` function. For example:
```go
func SignRawTransactionWithKeyAsync(client *rpcclient.Client, tx *wire.MsgTx, privKeysWIF []string) FutureSignRawTransactionWithKeyResult {
txHex := ""
if tx != nil {
buf := bytes.NewBuffer(make([]byte, 0, tx.SerializeSize()))
if err := tx.Serialize(buf); err != nil {
responseChan := make(chan *rpcclient.Response, 1)
responseChan <- &rpcclient.Response{result: nil, err: err} // Can not compile because 'unknown field err in struct literal of type rpcclient.Response'
return responseChan
}
txHex = …
```
> feat: Expose newFutureError for developer friendliness

- addrmgr/addrmanager_internal_test.go
Sometimes the tests in the addrmanager_internal_test will fail with: "addrmanager_internal_test.go: expected to find 5 addresses, found 4"
This is because the generated address with randAddr() may not always generate an address that's routable. If the address is not routable, that address will not be added to the manager when calling AddAddress().
This bug is fixed by creating a new function routableRandAddr() that always creates a routable random address.
> addrmgr: fix intermittent addrmanager_internal_test bug

- blockchain/utxocache.go
- blockchain/utxocache_test.go
Since BlockHeightByHash only returns the heights for blocks that are in the main chain, when a block that is stale gets pruned, this will cause an error in the block height lookup and cause an error in block processing.
Look up the node directly from the index and if the node isn't found, just skip that node. For utxoCache.lastFlushHash, if that isn't found, just force a flush.
Fixes #2121
> blockchain: don't rely on BlockHeightByHash for prune height calculations

- blockchain/chain.go
- blockchain/fullblocks_test.go
- blockchain/fullblocktests/generate.go
- blockchain/utxoviewpoint.go
- blockchain/validate.go
During reorgs, the assumption being made was that the utxocache is ignored and we're directly accessing the database for utxo set modifications.
However, after a block disconnect, the `BlockChain.chainLock`, the lock that prevents modifications to the utxo set, was being freed for the callback functions for the blockchain notifications.
https://github.com/btcsuite/btcd/blob/13152b35e191385a874294a9dbc902e48b1d71b0/blockchain/chain.go#L853-L858
If a caller calls either of the two methods below, the utxocache could be loaded with utxos that are fetched from the database:
https://github.com/btcsuite/btcd/blob/13152b35e191385a874294a9dbc902e48b1d71b0/blockchain/utxoviewpoint.go#L687-L693
https://github.com/btcsuite/btcd/blob/13152b35e191385a874294a9dbc902e48b1d71b0/blockchain/utxoviewpoint.go# …
> blockchain: fix inconsistent utxocache and database on reorg

- blockchain/utxocache.go
- blockchain/utxocache_test.go
Adds a test and fixes the bug to fix a case where a duplicate entry in the mapslice is possible.
Not sure if this is related to the other cases we've been seeing since the outpoints should never have duplicates, fixing this is good since the code is assuming that the mapslice will not have duplicates.
> blockchain: fix a bug where a duplicate entry is possible in the mapslice

- blockchain/accept.go
- blockchain/chain.go
For various b.sendNotifcation() callbacks, if a runtime panic happens, we don't get any useful debugging information since the error that happens first is the "unlock of unlocked mutex" error.
This is because we temporarily unlock the chainLock for callbacks and then relock them.  However, since the relocking code is executed after the completion of the callback, if an error happens during that callback, we never relock the chainLock.
Switching to an anonymous function and having the unlock code as a defer will ensure that the lock always relocks.
> blockchain: always relock chainLock for subscription callbacks

- rpcclient/errors.go
- rpcclient/errors_test.go
- rpcserver.go
This PR adds detailed error types so the caller can use the structured errors to gain finer control, eg, handling an error resulted from an RBF attempt.
> rpcclient: add detailed error types

- wire/msgtx.go
- wire/msgtx_test.go
This commit adds a method to MsgTx called TxID. This method returns the transaction ID (txid) of the subject transaction. This commit also adds a function for deriving the transaction ID from the double hash of the transaction.
> wire: add method TxID to MsgTx

- mining/mining.go
No need for `continue` since it's already at the end.
> chore: remove trailing continue

- rpcserver.go
- wire/msgtx.go
Add a method `ToHexStrings` to `TxWitness`. Remove stand alone function `witnessToHex(witness wire.TxWitness) []string`.
Motivation: `witnessToHex` is hard to access and to find.
> Convert `witnessToHex` into a method `ToHexStrings` on `TxWitness`

- btcjson/chainsvrcmds.go
- btcjson/chainsvrcmds_test.go
- rpcclient/rawtransactions.go
`defaultMaxFeeRate` was set to 1e8 / 10(sat/kb) as a parameter.  
But BTC/kvB is the expected value, so the units was wrong.  
This updates `defaultMaxFeeRate` to BTC/kvB and sets it to 0.1, which is the default value of Bitcoin Core.  
* https://bitcoincore.org/en/doc/26.0.0/rpc/rawtransactions/sendrawtransaction/
Because `maxFeeRate` sanity check has been added in bitcoin core v27.0 or later, sendrawtransaction cannot be executed without this change.
* https://github.com/bitcoin/bitcoin/pull/29434
Fixes https://github.com/lightningnetwork/lnd/issues/8571
> btcclient+btcjson: defaultMaxFeeRate to BTC/kvB

- btcec/pubkey.go
This commit adds a new type called `SerializedKey`.
A serialized type is useful when using public keys as map keys. This is because functionally identical public keys can have different internal representations. These differences would cause the map to treat them as different keys.
> Add new serialized pubkey type

- blockchain/blockindex.go
- blockchain/chain_test.go
IsAncestor() provides functionality for testing if a block node is an ancestor of anther block node.
Cherry-picked from [0d6a93e687e3470608cccfc58cc4a2ddb5ea8262](https://github.com/utreexo/utreexod/commit/0d6a93e687e3470608cccfc58cc4a2ddb5ea8262).
It's a part of #2154 as this method is used in utreexod code for testing invalidateblock and reconsiderblock methods on blockchain.
> blockchain: Add IsAncestor method to blockNode

- cmd/addblock/config.go
- cmd/gencerts/gencerts.go
- config.go
- database/ffldb/db.go
> chore: fix function names in comment

- config.go
I've found that the documentation of `config.AgentWhitelist` is not correct.
> docs: fix config documentation for `AgentWhitelist`

- release/release.sh
All currently released Apple computers have arm architecture and it's good to release something native for these computers.
> release: add darwin-arm64 to target binaries

- chaincfg/params.go
To summarize:
Removed two seeds: `testnet-seed.bitcoin.schildbach.de`(testnet), `seed.bitcoinstats.com`(mainnet).
One from schildbach.de is completely unreachable and is also removed in Core. bitcoinstats.com seed is reachable but returns bad results. Documented at https://github.com/bitcoin/bitcoin/issues/29911
Added seeds from Sjors on all three networks.
Added seed from Wiz on mainnet.
I can separate the commits out into different PRs if desired
> chaincfg: update dnsseeds

- blockchain/utxocache.go
- server.go
The trailing `: ` is removed from the utxocache log. It just looks better.
If the node is pruned, we now log what MiB it's pruned to. Logging alerts the user that the node is pruned and it helps for debugging purposes as well since we can now see from the logging whether or not the node is pruned.
> blockchain, main: add and fix logs

- blockchain/chain.go
- blockchain/chain_test.go
- blockchain/common_test.go
- blockchain/difficulty.go
- blockchain/fullblocktests/generate.go
- blockchain/internal/testhelper/README.md
- blockchain/internal/testhelper/common.go
- blockchain/internal/workmath/README.md
- blockchain/internal/workmath/difficulty.go
- blockchain/internal/workmath/difficulty_test.go
Depends on #2153
All of the code except for the last two commits are for refactoring code. The vast majority is just moving code from `fullblocktests` to `testhelper` so that the testing code for `InvalidateBlock()` can call the functions instead of having to copy over and duplicate functions.
The `InvalidateBlock()` method is operational and is tested but is not revealed through rpc in this PR.
> blockchain, fullblocktests, workmath, testhelper: add InvalidateBlock() method to BlockChain

- btcutil/bech32/bech32.go
a fix for issue  Public DecodeNoLimit(encoded) #2185
> Added DecodeNoLimitGeneric to bech32.go

- btcjson/cmdparse.go
`strconv.ParseFloat` will always treat `bizSize` parameter as 64 if we don't set it to 32, it's odd to set it to 0, although this won't affect the result
> refactor: set strconv.ParseFloat bitsize to 64

- blockchain/chain.go
- blockchain/chain_test.go
Adds ReconsiderBlock() on blockchain that will clear up any block validation statuses and re-validate the block. If the block is part of a longer chain, then the chain will reorganize to that chain.
Replaces #2181
> blockchain: Add ReconsiderBlock()

- integration/invalidate_reconsider_block_test.go
- rpcclient/chain.go
- rpcserver.go
- rpcserverhelp.go
Adds rpc calls for the invalidate and reconsiderblock methods on BlockChain.
Replaces #2183 and depends on https://github.com/btcsuite/btcd/pull/2196
> main, rpcclient, integration: add rpccalls for invalidate and reconsiderblock

- rpcclient/errors.go
This commit updates the error str to match the same error returned from `btcd` for both pre-0.24.2 and post-0.24.2.
> rpcclient: update error str to match both versions

- go.mod
- go.sum
- rpcclient/examples/bitcoincoreunixsocket/README.md
- rpcclient/examples/bitcoincoreunixsocket/main.go
- rpcclient/infrastructure.go
Enable the RpcClient to send  requests to Bitcoin Core over a Unix socket.
Issue #2149
> Enable the RpcClient to send requests to Bitcoin Core over a Unix socket.

- server.go
fixing https://github.com/btcsuite/btcd/issues/2202
> Fix the btcctl uptime command

- btcec/ecdsa/bench_test.go
- btcec/ecdsa/signature.go
- btcec/ecdsa/signature_test.go
There's no need for `error` since it's always `nil`.
> remove `error` return value for `SignCompact`

- database/ffldb/blockio.go
- database/ffldb/db.go
- database/ffldb/driver_test.go
On methods readBlock and readBlockRegion, the opened files were never closed which resulted in errors when attempting to delete these files on pruning on windows.  Properly closing the files avoids this error.
Doing a full block sync on windows to make sure. Definitely seems to be the fix as I'm not having any issues so far (few hours into ibd).
> ffldb: close block files

- blockchain/chainio.go
It is undefined behavior if we directly use the value from a Get call after the transaction has completed.
> blockchain: copy utxo status bytes to avoid UB

- wire/msgtx.go
- wire/msgtx_test.go
`chainhash.NewHashFromStr` will zero-pad the given string if it's smaller than 32 bytes / 64 hex chars.
That's fine, but when creating an OutPoint from a string, the TXID part of the string must be exactly 64 hex chars to (possibly) be a valid TXID. Right now, `NewOutPointFromString` accepts a TXID of less than 64 chars, and will end up padding the end with 0's.
This PR rejects incorrectly-sized TXID strings in `NewOutPointFromString`.
> wire: check TXID length before creating outpoint

- btcjson/walletsvrcmds.go
In the current code, if we provide a non-number value (e.g. `"method":"deriveaddresses","params":["A",["A","B"]]`), it might cause a panic. This PR fixes it.
> bugfix: check if both begin and end are numbers in `UnmarshalJSON`

- btcjson/chainsvrresults.go
- btcjson/chainsvrresults_test.go
Fixes #2224 and lightningnetwork/lnd#9053.
Depending on the version of Bitcoin Core, the "warnings" field in the response to getnetworkinfo is either a single string value or an array of strings.
We can easily parse those two variants with a custom type that implements an UnmarshalJSON method.
> btcjson: turn warnings into StringOrArray type

- btcec/btcec_test.go
- mempool/policy_test.go
Signed-off-by: Abirdcfly <fp544037857@gmail.com>
> delete minor unreachable code caused by t.Fatal

- rpcclient/infrastructure.go
Not sure why we did not have a timeout in the first place, but I think it makes sense. Did not choose to add it as a config value but can be changed.
> rpcclient: add timeout to http request.

- btcd.go
- config.go
Execution traces are part of the go runtime tooling and is useful to check what is slowing down the ibd.  For example, a slow ibd because of slow block downloads from peers won't show up on cpu profiling but will on a trace.
Also execution tracing has [gotten a lot better](https://go.dev/blog/execution-traces-2024) with go 1.22
> main: add flag to write execution traces

- peer/peer.go
- wire/message.go
- wire/msgsendaddrv2.go
- wire/msgsendaddrv2_test.go
- wire/msgwtxidrelay.go
- wire/msgwtxidrelay_test.go
- wire/protocol.go
IBD for new nodes were broken due to the version handshake failing between nodes that recognized wtxid based relays.  Reverting the changes that were made so that the node is able to connect to those nodes.
fixes #2280
> wire, peer: fix broken ibd

- rpcclient/infrastructure.go
This PR tries to make batchList concurrent-safe.
The `Send()` could panic at the line 1730 if c.removeRequest  returned `nil`. It could return `nil` if we try to call `Send()` concurrently.
https://github.com/btcsuite/btcd/blob/684d64ad74fed203fb846c032f2b55b3e3c36734/rpcclient/infrastructure.go#L1708-L1730
After the quick look I've noticed that there are places where the batchList is update unsafely. So, the simplest fix is just to add locks, but I'm afraid if it could break something else, because I'm not very familiar with the library.
> rpcclient: safe read and write to batch

- btcjson/register_test.go
1. **File**: `btcjson/register_test.go`
- Corrected "paniced" to "panicked".
- Improved code comments by fixing the typographical error.
- Enhanced the clarity and professionalism of the codebase.
> typo-Update register_test.go

- cmd/addblock/config.go
- cmd/findcheckpoint/config.go
- config.go
- database/cmd/dbtool/globalconfig.go
This is a [new function](https://pkg.go.dev/slices@go1.21.0#Contains) added in the go1.21 standard library, which can make the code more concise and easy to read.
> refactor: using slices.Contains to simplify the code

- addrmgr/addrmanager_internal_test.go
- cmd/findcheckpoint/config.go
- config_test.go
- database/ffldb/driver_test.go
- database/ffldb/whitebox_test.go
>TempDir returns a temporary directory for the test to use.The directory is automatically removed when the test and
all its subtests complete.
tested:
```
Running tool: /opt/homebrew/bin/go test -timeout 30s -run ^TestAddrManagerV1ToV2$ github.com/btcsuite/btcd/addrmgr
=== RUN   TestAddrManagerV1ToV2
=== PAUSE TestAddrManagerV1ToV2
=== CONT  TestAddrManagerV1ToV2
--- PASS: TestAddrManagerV1ToV2 (0.00s)
PASS
ok      github.com/btcsuite/btcd/addrmgr        0.005s
```
📝 Please see our [Contribution Guidelines](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md) for further guidance.
> multi:use t.TempDir replace os.MkdirTemp to simplify test temp dir manager

- cmd/btcctl/config.go
- rpcclient/infrastructure.go
- rpcserver.go
- wire/bench_test.go
`ioutil.ReadAll` is deprecated: As of Go 1.16, this function simply calls `io.ReadAll`
📝 Please see our [Contribution Guidelines](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md) for further guidance.
> multi: remove deprecated io/ioutil

- netsync/manager.go
When we're all caught up and we have a new peer, we'll ask for blocks from peers that we're on the same height. Since these peers don't have any blocks to send us, they don't reply and we disconnect from them as they timeout.
To prevent this, we don't ask for blocks if the chain thinks we're current and do not have a peer that reports having a higher block.
> netsync: don't ask for blocks from peers on the same block height

- Makefile
- addrmgr/cov_report.sh
- btcutil/base58/cov_report.sh
- btcutil/bloom/cov_report.sh
- btcutil/coinset/cov_report.sh
- btcutil/cov_report.sh
- btcutil/hdkeychain/cov_report.sh
Description of change / link to associated issue.
deprecation goacc
ref:https://go.dev/doc/go-get-install-deprecation
> multi: deprecation goacc

- .github/pull_request_template.md
Description of change / link to associated issue.
walkthrough `Code Style and Documentation` checklist:
pr:https://github.com/btcsuite/btcd/pull/2333 introduce this error.
> docs: update contribution link

- btcutil/psbt/psbt_test.go
- btcutil/psbt/taproot.go
Closes https://github.com/btcsuite/btcd/issues/2372
Thank you to @brunoerg for opening the issue.
---
Protect against overflows when parsing malformed Taproot BIP32 derivation fields. This ensures that deserialization fails safely if the declared number of leaf hashes would otherwise cause an integer overflow.
> psbt: overflow checks when computing Taproot BIP32 derivation min size

- go.mod
- peer/peer.go
- v2transport/chacha.go
- v2transport/go.mod
- v2transport/go.sum
- v2transport/transport.go
- v2transport/transport_test.go
In this PR, we first reduce the size of the new `v2transport` module by reducing eliminating the dep on the `wire` package, which causes the entire `btcd` repo to be brought in. As a follow up, we then update the `btcec` dep so we can eliminate the newly added replace directives. 
Once this PR is merged, we can tag the `v2transport` module, then remove the top level replace.
> v2transport: update to btcec v2.3.5, reduce module deps

- v2transport/go.mod
In this commit, we fix the module path for the new `v2transport` package. It needs the repo prefix (btcsuite/btcd).
> v2transport: fix module path

- txscript/taproot.go
- txscript/taproot_test.go
In this commit, we add more detail to the invalid tapscript merkle proof error. Before this commit, the error was blank, making such a case hard to debug. We'll now log the expected witness program, what we derived, and also the passed in tapscript root.
> txscript: add more detail to invalid tapscript merkle proof error

- server.go
- wire/msgaddrv2.go
- wire/msgaddrv2_test.go
This PR introduces some refactoring to methods like `OnGetData` and `BtcEncode`, aiming to improve readability and code health.
> Minor refactor to improve code health

- rpcclient/chain.go
`GetBlockCount` returns the height of the latest block, not the total number of blocks. The genesis block has a height of 0.
The previous description could lead to an off-by-one error for anyone relying on it.
> rpcclient: clarify GetBlockCount description

- cmd/btcctl/btcctl.go
Prints a readable error in btcctl if there's an error in reading the config.
Solves https://github.com/btcsuite/btcd/issues/2392
> Print a readable error before os.Exit(1) in btcctl

- txscript/template.go
- txscript/template_test.go
In this commit, we add a new function, `ScriptTemplate` to make the process of making custom Bitcoin scripts a bit less verbose.
ScriptTemplate processes a script template with parameters and returns the corresponding script bytes. This functions allows Bitcoin scripts to be created using a DSL-like syntax, based on Go's templating system.
An example of a simple p2pkh template would be:
`OP_DUP OP_HASH160 0x14e8948c7afa71b6e6fad621256474b5959e0305 OP_EQUALVERIFY OP_CHECKSIG`
Strings that have the `0x` prefix are assumed to byte strings to be pushed ontop of the stack. Integers can be passed as normal. If a value can't be parsed as an integer, then it's assume that it's a byte slice without the 0x prefix.
Normal go template operations can be used as well. The params argument houses …
> txscript: add new ScriptTemplate DSL for writing Scripts

- .gemini/styleguide.md
Copied from yy's diff https://github.com/btcsuite/btcwallet/pull/1014. 
Follow-up on @yyforyongyu's comment https://github.com/btcsuite/btcd/pull/2395#pullrequestreview-3003282311.
> .gemini: add `styleguide.md`

- rpcclient/errors.go
- rpcclient/errors_test.go
Fixes #2404.
If different versions of bitcoind return different error strings, we need a way to match those as well.
> rpcclient: add bitcoind version dependent error matching

- .golangci.yml
- Makefile
- btcutil/psbt/partialsig.go
- rpcclient/chain_test.go
- rpcclient/example_test.go
fix / cleanup makefile and correcting several commands.
Related to https://github.com/btcsuite/btcd/issues/2319 https://github.com/btcsuite/btcd/pull/2316
> feat: fix ci / makefile

- .github/workflows/main.yml
- Makefile
Follow-up on https://github.com/btcsuite/btcd/pull/2320#discussion_r2287153465.
> Makefile+workflows: fallback to `GOPATH/bin` on non-existent `GOBIN`
