- peer.go
This matches the Bitcoin Core commit https://github.com/bitcoin/bitcoin/commit/12a49cac0a561ada277e93549cae26a3123a6023
> Limit the number of addresses announced.

- rpcserver.go
This pull request modifies the creation of RPC results to ignore errors in script disassembly since they already contain the error string inline and the RPC results must still be generated regardless.
This was already done in the `decodescript` RPC, however the same thing was not being done in the higher level verbose transaction results.  This applies to both the `createrawtransaction` and `decoderawtransaction` RPCs.
Also, since this was the only thing that could error within those functions, the error returns and caller checking of now non-existent errors have been removed.
Fixes #210.
> Ignore error in script disassembly for RPC results.

- cmd/btcctl/btcctl.go
refs: https://github.com/davecgh/btcwallet/pull/7
> Updated to add createnewaccount, renameaccount

- .travis.yml
- goclean.sh
This pull request causes TravisCI to run several tools on each pull request and commit to help ensure the code quality remains high.  This includes gofmt, goimports, golint, go vet, the race detector, and coverage stats.
Also, it instructs TravisCI to use nicer container-based builds.
> Update TravisCI to goclean script.

- cmd/btcctl/btcctl.go
Refs: https://github.com/btcsuite/btcwallet/pull/130
Depends on https://github.com/btcsuite/btcjson/pull/41, https://github.com/btcsuite/btcwallet/pull/192
> btcctl: Add importaddress, importpubkey cmds

- goclean.sh
> Correct path to find in TravisCI goclean script.

- chainindexer.go
Related to #303. 
* Decouple logging and handling of distinct error messages for cases of
failed tx look up.
* This also fixes a bug wherein the `addrindexer` failed to lookup a tx
(since it didn't exist), but continued since the returned error was
nil.
> Separate addrindex tx fetch error messages

- blockchain/accept.go
- blockchain/validate.go
- mining.go
- wire/blockheader.go
This pull request implements the changeover logic for version 3 blocks as described by BIP0066.
> Implement BIP0066 changeover logic for v3 blocks.

- addrmgr/addrmanager_test.go
Unit tests to get a little more coverage into the addrmgr.
> Added some unit tests to addrmgr.

- mempool.go
- mining.go
This pull request modifies finalized transaction check used by the memory pool and block templates to use the network adjusted time instead of the unadjusted local time.  This helps keep the transactions accepted to the
memory pool, and hence allowed to relay, more consistent across nodes.
> Use network adjusted time for finalized tx check.

- addrmgr/addrmanager.go
This change was suggested as Countermeasure 6 in
Eclipse Attacks on Bitcoin’s Peer-to-Peer Network, Ethan
Heilman, Alison Kendler, Aviv Zohar, Sharon Goldberg. ePrint Archive
Report 2015/263. March 2015.
This mimics Bitcoin Core commit 1d21ba2f5ecbf03086d0b65c4c4c80a39a94c2ee
> Scale up addrman.

- peer.go
This mimics Bitcoin Core commit a1ba0778dd3c784046dea334e5d39f37eca264f7
> Ignore getheaders requests if not synced.

- btcjson/walletsvrresults.go
Required for btcsuite/btcwallet#262.
> btcjson: Add spendable to listunspent result.

- btcjson/chainsvrcmds.go
- btcjson/chainsvrcmds_test.go
- btcjson/chainsvrresults.go
- docs/json_rpc_api.md
- rpcserver.go
- rpcserverhelp.go
This mimics Bitcoin Core commit 076badb60f33f0c32b035de220ca14c52a423a2a
> Implement getblockheader RPC.

- btcjson/walletsvrcmds.go
- btcjson/walletsvrcmds_test.go
Adds wallet server command getwalletinfo
> btcctl: Add getwalletinfo command

- params.go
Drop seed seeds.bitcoin.open-nodes.org.
> Add new seed seed.bitcoin.jonasschnelli.ch.

- rpcserver.go
This pull request optimizes the `createVinList` function which is used to generate the JSON list of transaction inputs.  It also makes it more consistent with the `createVinListPrevOut` function.
In particular, it entails the following changes:
- Only do a single coinbase check and return right away instead of checking multiple times inside the loop over the inputs
- Use a pointer for populating the details of each entry to avoid multiple unnecessary array lookups and bounds checks
- Group all fields that populate the entry for better readability
> rpcserver: Optimize JSON raw tx input list create.

- peer/doc.go
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/531)
> peer: Correct a few types in documentation.

- peer/peer.go
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/534)
> peer: Don't stall on pongs.

- docs/README.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/542)
> add installation instructions for Gentoo

- peer/peer.go
- server.go
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/545)
> Move comment to where it belongs.

- mempool.go
This is more efficient and prevents duplicate entries which can
lead to no-longer-orphans being attempted be added to the mempool
multiple times.
Bug found by me, debugged with @davecgh, and patch from @davecgh
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/551)
> mempool:  convert orphansByPrev from a list to a map.

- peer/peer_test.go
In rare cases, the build fails due to a hang in the peer tests:
https://travis-ci.org/btcsuite/btcd/jobs/90591996#L550
From the logs, I see that two peers in `TestOutboundPeer` are trying to write to the writer belonging to the same mock connection. Fixed this by using a new connection for each peer.
Also, cleaned up a chan that was not being used.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/549)
> Fix build due to hang in peer tests

- chaincfg/params.go
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/555)
> Add checkpoint at block height 382320.

- server.go
When the peer code was refactored, the lists of peers were converted to maps however the code which runs when a peer disconnects still iterates them like a slice.  This is no longer necessary since they are maps
which means the peer can simply be looked up by its ID.
Also, the old code was comparing the map entry and the peer being removed by their pointers which could lead to potentially not properly finding the peer.  This issue is also resolved by this change since it looks up the peer by its ID.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/561)
> server: Improve handling of disconnected peers.

- config.go
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/565)
> Fix dropaddrindex flag usage message

- mining.go
Now that the memory pool minimum fee calculation code is also calculating a more precise value instead of rounding up to the nearest kilobyte boundary, the comment in `NewBlockTemplate` regarding this behavior is no longer accurate.  Thus, this removes the comment.
Also, while here, change the calculation to use an int64 instead of float since it matches the precision of the new calculation code used by the memory pool and can also avoid the need for the slower floating point math.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/558)
> mining: Remove comment and change fee calc to int.

- server.go
**This pull request requires #561.**
This fixes an issue introduced during the peer refactor where persistent peers that failed the initial connection are not retried as intended.
It also improves the retry logic as follows:
- Make the retry handler goroutine simply use a for loop instead of launching a new goroutine for each backoff attempt.  Even though goroutines are fairly cheap to create, it is much more efficient to simply loop
- Rather than dividing the const interval by 2 everywhere, just half the constant
Finally, include the address of the peer in the error message when a new outbound peer can't be created.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/562)
> server: Improve the persistent peer retry logic.

- mempool.go
- server.go
This is in preparation of moving mempool to its own subpackage.  No
functional change.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/568)
> mempool: Introduce mempoolConfig.

- peer/peer.go
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/582)
> peer: Rename variable for consistency.

- CHANGES
Reviewed changelog and fixed 2 tiny typos.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/588)
> Fix typos in changelog.

- docs/code_contribution_guidelines.md
guidelinestherin ---> guidelines therein.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/589)
> Fix inconsistent spacing.

- txscript/sigcache.go
- txscript/sigcache_test.go
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/592)
> Review and fix typos in SigCache code.

- btcec/privkey.go
Found via github.com/mvdan/interfacer.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/593)
> Replace *KoblitzCurve by elliptic.Curve

- chaincfg/params.go
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/595)
> chaincfg: Remove testnet-seed.alexykot.me, it is defunct.

- server.go
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/596)
> Bump copyright date to reflect fixes since the beginning of 2016.

- btcec/privkey.go
- params.go
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/597)
> Change copyright date for code that was updated this year(2016).

- peer/peer.go
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/608)
> peer: Simplify PushAddrMsg method loop.

- wire/message.go
- wire/msgversion.go
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/610)
> wire: Minor code clean up.

- txscript/README.md
langauge ---> language
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/613)
> txscript: Fix typo in README 📝

- rpcserver.go
This optimizes the filter address handling code in the RPC server `handleSearchRawTransasctions` path in a few ways:
- Only normalize the filter addresses provided in the command once rather than for every transaction being returned
- Reset the passes filter flag just before it's used
- Use a local for the encoded address to avoid the bounds checking overhead of accessing it from the slice
- Avoiding subsequent map lookups once the filter has already passed
Also, while here, modify a few of the related comments to match code style and consistency.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/569)
> rpcserver: Optimize filteraddr code.

- peer/peer.go
- server.go
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/599)
> Use atomic operations instead of mutexes.

- policy_test.go
Fix something goclean caught.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/619)
> Do not use unkeyed fields.

- txscript/stack_test.go
Cherry-picked from downstream decred/dcrd#12.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/620)
> Remove duplicate stack tests.

- mempool.go
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/627)
> mempool:  reduce lock contention

- database2/ffldb/dbcache.go
This removes the intermediate transaction log that was introduced as a part of the database cache as a workaround for `leveldb` batches causing massive memory usage spikes in favor of the recently introduced `leveldb` transaction interface which no longer has the memory usage issues.
This approach is preferred because it can avoid the extra memory needed for the transaction log and therefore all of the intermediate states as well.  As a result, the default cache size has been doubled since it equals roughly the same amount of overall memory usage and the flush interval has been raised as well.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/623)
> database: Remove tx log in favor of new ldb txns.

- cmd/findcheckpoint/findcheckpoint.go
This updates the `findcheckpoint` utility to work when there are not already any checkpoints.  This doesn't really matter for Bitcoin at the current time, but if a new `testnet` is created it will not have any
checkpoints to start with and this change also means the utility can work for alts.
While here, switch a couple of error prints to ensure they contain a final newline.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/631)
> findcheckpoint: Update to allow first checkpoint.

- wire/bench_test.go
- wire/common.go
- wire/common_test.go
- wire/internal_test.go
- wire/msgaddr.go
- wire/msgalert.go
- wire/msgblock.go
- wire/msgfilteradd.go
- wire/msgfilterload.go
- wire/msggetblocks.go
- wire/msggetdata.go
- wire/msggetheaders.go
- wire/msgheaders.go
- wire/msginv.go
- wire/msgmerkleblock.go
- wire/msgnotfound.go
- wire/msgtx.go
- wire/msgversion_test.go
This is a pull request to make these functions exportable as requested in issue #630. I simply did a search and replace.
Closes #630.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/633)
> wire: Export (read|write)(VarInt|VarBytes).

- rpcserver.go
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/634)
> rpcserver: Fix 9 typos in comments

- server.go
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/640)
> server: Appropriately name inbound peers map in peerState.

- server.go
This resolves issue #642.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/643)
> Fix server stalling when RPC server is not running.

- server.go
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/654)
> Cleanup and optimize handleBroadcastMsg

- txscript/engine.go
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/657)
> txscript: Correct comments on alt stack methods.

- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/669)
> travis: run tests on latest golang (1.5.4 and 1.6.1)

- btcec/ciphering.go
Recent commit https://github.com/btcsuite/btcd/commit/f893558d782396f10c2fe49a8bc73deff4a36d14 touched this file.
Lets update the copyright date too.
> Bump up copyright. Reflect recent update.

- txscript/sigcache.go
> txscript: Fix typo.

- peer/peer.go
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcd/670)
> peer: use atomics instead of mutexes

- rpctest/rpc_harness_test.go
- rpctest/utils.go
This corrects several issues with the new `rpctest` package.
The following is an overview of the issues that have been corrected:
- The `JoinNodes` code was incorrect for both mempool and blocks.
- For mempool it was only checking the first node against itself
- For blocks it was only testing the height instead of hash and height which means the chains could be different and it would claim they're synced
- The test for mempool joins was inaccurate in a few ways:
- It was generating separate chains such that the generated transaction was invalid (an orphan) on one chain, but not the other
- Mempools are not automatically synced when nodes are connected and there is a large random delay before any transaction rebroadcast happens, so it can't be relied on for the purposes of this test
- The …
> rpctest: Correct several issues in tests and joins.

- mempool/mempool.go
callers should not need to lock/unlock the mempool themselves.
> mempool: unexport the mutex

- blockchain/validate.go
This modifies the `ExtractCoinbaseHeight` function to recognize small canonically serialized block heights in coinbase scripts of blocks higher than version 2.
This allows regression test chains in which blocks encode the serialized height in the coinbase starting from block 1.
> blockchain: Support small coinbase block size

- config.go
- connmgr/README.md
- connmgr/connmanager.go
- connmgr/connmanager_test.go
- connmgr/doc.go
- connmgr/dynamicbanscore.go
- connmgr/dynamicbanscore_test.go
- connmgr/log.go
- connmgr/seed.go
- connmgr/tor.go
- docs/README.md
- log.go
- server.go
Added pkg `connmgr` and moved common connection related functionalities into it. Working on refactoring all the functionalities mentioned in #564 and fixing related bugs.
> connmgr: Add pkg and refactor

- docs/README.md
- mempool/README.md
- mempool/doc.go
This consists of two commits.  The first adds the mempool to the [Developer Resources](https://github.com/btcsuite/btcd/blob/master/docs/README.md#5-developer-resources) section of [docs/README.md](https://github.com/btcsuite/btcd/blob/master/docs/README.md).  The second adds a `docs.go`file to the [mempool](https://github.com/btcsuite/btcd/blob/master/mempool) package and fleshes out its `README.md` which previously still had that it was a work in progress.
> mempool: Add docs.go and flesh out README.md.

- server.go
This channel is no longer used since the outgoing connection logic is handled by the `connmgr` package now.
> server: Remove unused wakeup channel.

- blockchain/chain_test.go
Also compress some definitions a bit while simplifying.
> blockchain: Run gofmt -s.

- blockmanager.go
- mempool/mempool.go
- mempool/mempool_test.go
- server.go
This will provide callers more information on the accepted transaction.
> mempool:  Return type TxDesc instead of type btcutil.Tx

- peer/peer.go
> peer: Separate ping ticker functionality from outHandler.

- blockmanager.go
> bmgr: Remove unused struct fields.

- btcjson/chainsvrresults.go
- mempool/mempool.go
- mining/mining.go
- rpcserver.go
- rpcserverhelp.go
- server.go
This only adds support for handling remote peer requests.
> btcd: support feefilter requests.

- server.go
This modifies the signatures of all `serverPeer` callbacks that are provided as `peer.Listeners` to use `_` for the first parameter name which ensures the passed peer can't be used within the function and updates
all references to the server peer.
This helps ensure any overridden methods that might be defined on a `serverPeer` will be invoked where directly calling methods on the passed `peer.Peer` would not.
Also, while here, add a comment to the `OnFeeFilter` function.
> server: Ensure callbacks use the server peer.

- blockchain/validate.go
**This PR depends on #785**
This modifies the code to only enforce the fairly expensive BIP0030 (duplicate transcactions) checks when the chain has not yet reached the BIP0034 activation height (and is not one of the 2 special historical blocks that break the rule and prompted BIP0034 to being with) since that BIP made it impossible to create duplicate coinbases and thus removed the possibility of creating transactions that overwrite older ones.
This is a rather large optimization because the check is expensive due to involving a ton of cache misses in the utxoset.  For example, the following are times it took to perform the BIP0030 check on blocks 425490 - 425502 on a system with a relatively old Hitachi spinner HDD:
block 425490: 674.5857ms
block 425491: 726.5923ms
block 425492: …
> blockchain: Only enforce BIP0030 prior to BIP0034.

- blockchain/chain.go
This removes the `removeBlockNode` function since it is no longer used after the addition of `CLTV` removed block node pruning.
> blockchain: Remove unused block node removal func.

- blockchain/accept.go
- blockchain/blockindex.go
- blockchain/blocklocator.go
- blockchain/chain.go
- blockchain/chainio.go
- blockchain/difficulty.go
- blockchain/process.go
- blockchain/thresholdstate.go
- blockchain/validate.go
- blockchain/versionbits.go
This refactors the block index logic into a separate struct and introduces an individual lock for it so it can be queried independent of the chain lock.
> blockchain: Refactor main block index logic.

- docs/README.md
Invalid tokens: github had made some changes the past months, the old style is not rendering at all, so I fixed that for you. 
Other contributors can do the same for all of the project's documents.
**Thanks.**
> Fix docs/README.md

- cmd/btcctl/config.go
> btcctl: Inherit notls config from btcd.conf

- chaincfg/params.go
To be used together with https://github.com/btcsuite/btcutil/pull/100
> Add human-readable part for segwit addresses to chaincfg.Params

- chaincfg/params.go
- chaincfg/register_test.go
The IsBech32SegwitPrefix method takes a string prefix and
determines if it is a valid prefix for a Bech32 encoded segwit
address for any of the default or registered networks.
> chaincfg: Add IsBech32SegwitPrefix utility method.

- blockchain/versionbits.go
looks like bit and activationHeight needed to swap places.
> Fix the unknown new rules activation warning

- cmd/btcctl/config.go
If no existing btcctl.conf file exists, btcctl creates a default one using the RPC username and password from the btcd.conf. If the --wallet flag is passed, however, it should read from btcwallet.conf instead.
https://github.com/btcsuite/btcd/issues/875.
> Read RPC username/pass from correct config file for btcctl defaults.

- rpcserver.go
This makes the code for `getheaders` more consistent with the rest of the code in terms of making use of existing error functions and using the same RPC error codes as other handlers.
While here, it also performs the fetching of headers directly instead of using a function from server which makes it more tightly coupled.
> rpcserver: Cleanup getheaders handler.

- peer/peer.go
- peer/peer_test.go
If a peer does not support the minimum allowable protocol version, the current logic sends a reject package (despite the peer not supporting them), and may not disconnect immediately. Introduced in https://github.com/btcsuite/btcd/pull/626.
My Go code is probably not idiomatic, so feel free to tear it up. The tests in particular feel clunky.
> peer: Don't send unsupported reject to old peers.

- blockchain/notifications_test.go
This test is flaky because both NTBlockAccepted and NTBlockConnected notifications are fired and the test used to depend on the order.
> blockchain: Fix race condition in notifications_test.

- rpcserver.go
- rpcwebsocket.go
**NOTE: This PR requires #981**
This modifies all of the RPC code to use the chain parameters that are associated with the RPC server instead of the global `activeNetParams` and thus moves one step closer to being able to split the RPC server out into a separate package.
> rpcserver: Don't use activeNetParams.

- peer/peer.go
- peer/peer_test.go
- server.go
serverPeer is a problematic struct because it is local to the main package.
Working towards https://github.com/btcsuite/btcd/issues/978.
> peer: Move IsWitnessEnabled() from serverPeer to Peer.

- blockchain/chain_test.go
This cleans up the test in `TestCalcSequenceLock` in the following ways:
- Use calculated values instead of magic value so it is easier to update the tests as needed
- Make tests match the comments
- Change comments to be more consistent and fix some grammar errors
- Set `mempool` flag for unconfirmed tx tests since they are intended to mimic transactions in the mempool
> blockchain: Cleanup a few sequence lock tests.

- blockchain/chainview.go
> blockchain: Correct chainview locator comment.

- blockmanager.go
- btcd.go
- server.go
Continue working towards https://github.com/btcsuite/btcd/issues/978.
> blockmanager: Remove dependency on cfg in main package.

- txscript/script.go
This modifies `calcSignatureHash` to use a shallow copy of the transaction versus a deep copy since the actual scripts themselves are not modified and therefore don't need to be copied and adds a benchmark.
This is being done because profiling the most overall allocated space shows that the deep copy performed in `calcSignatureHash` accounts for nearly 20% of all allocations on a synced running instance.  Also, copying all of the additional data makes it more time consuming as well.
With this change, that figure drops from ~20% to ~5% of all allocations.
The following benchmark shows the relative speedups and allocation reduction as a result of the optimization on my system.  In particular, the changes result in approximately a 15% speedup and a whopping 99.89% reduction in allocations …
> txscript: Shallow tx copy for signature hash calc.

- server.go
Just moves the listener setup logic out of `newServer` and cleans it up a bit.
> server: Split some newServer logic into new methods.

- txscript/script_test.go
> Typo fix in script_test.go

- rpcclient/rawtransactions.go
This pull request adds decodescript in rpcclient.
> rpcclient: Add decodescript support.

- rpcclient/wallet.go
This PR adds the necessary type and functions for calling the addwitnessaddress method from the RPC client.
> rpcclient: implement addwitnessaddress

- txscript/standard.go
This allows redeeming parties to audit the secret size and ensure it
will be usable once revealed.
> Require atomic swap contracts to specify the secret size.

- blockchain/chain.go
This generalizes the `reorganizeChain` function in the `blockchain` package to allow it to rewind the chain in the case no attach nodes are provided or extend the chain in the case no detach nodes are provided.
It also adds several assertions to ensure the assumptions about the state hold and cleans up the handling of setting invalid ancestor nodes in the case of a failed block validation.
This resolves #1194 and resolves #1214.
> blockchain: Generalize chain reorg.

- server.go
Fixes https://github.com/btcsuite/btcd/issues/1167.
> server: Fix bug disconnecting peer on filteradd

- rpcclient/net.go
The `AddNode` command is not particularly easy to use for managing connections, this PR exposes the more useful `Node` command for the `rpcclient`.
> rpcclient: expose the Node command for RPC API.

- sample-btcd.conf
> sampleconfig: Remove floating grave accent

- docs/README.md
Fixes https://github.com/btcsuite/btcd/issues/1379
> Use go modules instead of glide

- netsync/manager.go
This commit modifies the sync peer selection to prefer peers with a
higher advertised height than our currently known best height. If no
peers are known with a higher height, we will fall back to selecting a
random peer with the same best height as our own.
The current algorithm currently selects a random peer from the union of
these two sets, while this approach will favor trying to make progress.
This will likely help in selecting a good peer once already at tip, such
as after a restart.
Backport of https://github.com/gcash/bchd/pull/96
> netsync/manager: prioritize higher height peers for sync peer

- upnp.go
Found using https://go-critic.github.io/overview#commentedOutCode-ref
> remove commented-out code

- database/ffldb/interface_test.go
> Fix comment error

- database/ffldb/db.go
> fix comment of database.Tx to match code

- docs/configure_peer_server_listen_interfaces.md
Simple note in docs for using gencerts
> Add note about using gencerts when listening on specific interfaces

- docs/README.md
I added a symlink for the default github documentation preview when entering the docs folder on github.
> Added symlink to index.md for github readme preview.

- btcec/btcec.go
Set curve name(secp256k1) in KoblitzCurve.CurveParams
Fixes #1564
> btcec: set curve name in CurveParams

- btcjson/walletsvrcmds.go
- btcjson/walletsvrcmds_test.go
- btcjson/walletsvrresults.go
- rpcclient/rawtransactions.go
Re-creating https://github.com/btcsuite/btcd/pull/1561 after I deleted it. I probably didn't need to delete it but even with running the requested git commands my branch diff vs this repo's master still had 8 or 9 commits so I made the thing from scratch off upstream/master, cherry picked and squashed the relevant commits.
> Add signrawtransactionwithwallet command interface

- blockchain/chainio.go
- database/ffldb/blockio.go
- wire/fixedIO_test.go
- wire/message.go
Found using https://go-critic.github.io/overview#unslice-ref
Reviving #1294 here because the fork has been deleted by the author.
> simplify s[:] to s where s is a slice

- btcjson/chainsvrresults.go
- rpcserver.go
> btcjson: Updated TxRawResult.Version from int32 to uint32

- Dockerfile
With this changes https://github.com/btcsuite/btcd/pull/1753/ merged in
the docker image also has to be upgraded.
> Upgraded the docker version to 1.16

- cmd/btcctl/version.go
- version.go
Alternative to https://github.com/btcsuite/btcd/pull/1802
> build: bump version to v0.23

- btcec/schnorr/signature.go
fixes https://github.com/btcsuite/btcd/issues/2017
> schnorr: bip-340 compliant verification

- txscript/sighash.go
sighah -> sighash
mesage -> message
extensiosn -> extension
algoriths -> algorithms
> fix: typos in sighash.go

- cmd/btcctl/config.go
> fix: default forward port

- btcec/schnorr/signature.go
Fix the typo correction from  #2065
> Correct comments in singature.go

- btcutil/hdkeychain/README.md
- mempool/README.md
> chore: fix typos

- rpcclient/infrastructure.go
fixes https://github.com/btcsuite/btcd/issues/2229
> rpcclient: signet support

- txscript/opcode.go
Use the change to rectify some typos.
> fix: correct the typos [skip ci]

- sample-btcd.conf
> main: add prune documentation to sample-btcd.conf

- .github/pull_request_template.md
- .gitignore
- docs/code_contribution_guidelines.md
- docs/code_formatting_rules.md
Add tailored docs for this repo, address this [comment](https://github.com/btcsuite/btcd/pull/2331#discussion_r1980839820).
> docs: update guidelines and links

- integration/rpctest/memwallet.go
- mempool/mempool.go
- txscript/hashcache.go
Use the built-in methods from the standard library to simplify the code, while also conducting a global check for replaceable cases.
> refactor: use map.Copy for cleaner map handling

- btcutil/psbt/bip32.go
- btcutil/psbt/bip32_test.go
Fixes https://github.com/btcsuite/btcd/issues/2351.
> psbt: check path minimum length

- database/ffldb/blockio.go
- database/ffldb/dbcache.go
Currently btcd keeps downloading blocks and fails to verify them if the disk is out of space. We exit immediately if we detect that the disk is out of space to ensure the database is at a recoverable state later on.
Tested by using a macbook with full disk and checking if the program shuts down as expected. Verified that it's also able to recover when given enough storage again.
> database: shut the program down immediately if we run out of disk space

- .gemini/config.yaml
Description of change / link to associated issue.
> CI: add gemini assist for code reviews

- Dockerfile
Update Dockerfile base image from Go 1.22.11 to Go 1.23.2 to match go.mod requirement.
Fixes: https://github.com/btcsuite/btcd/issues/2408
> Dockerfile: update go base image
